### ISSUE TITLE
Opacity in Windows 10

### ISSUE THREAD

**Issue by alshdavid** [zeit/hyper#1597] opened 2017-03-03 10:05 UTC
Hyper version 1.2.1 100% vanilla on Windows 10 
I haven't found any solutions

## Issue
In my hyper.js config, I have my background set to:
`backgroundColor: 'rgba(0,0,0,0.5)'`

However, it's not making the window opaque. 
Anyone having the same issue?

**Comment by gsklee** [comment] 2017-03-03 10:08
Dupe of #1556.

**Closed** 2017-03-03 10:43 UTC
