### ISSUE TITLE
crash screen with an Nvidia driver.

### ISSUE THREAD

**Issue by meotimdihia** [zeit/hyper#3023] opened 2018-05-16 03:04 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: ubuntu 16.04
- **Hyper.app version**: Hyper 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/meotimdihia/572616303a9f3eaff01b8849eec7b9d5
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
when i suspend ubuntu and start computer again, hyper screen is crash:

![selection_001_09 50 16_16_05_2018](https://user-images.githubusercontent.com/300961/40094100-36f10b40-58ef-11e8-830f-4653cdc3f302.png)

The problem just happen when i use NDIVIA binary driver:

![selection_001_09 51 27_16_05_2018](https://user-images.githubusercontent.com/300961/40094101-37208e6a-58ef-11e8-921e-3795aade7423.png)

All other programs have no problem but hyper.
I think the problem relate with Electron but i don't see the problem on Visual Studio Code.

**Comment by albinekb** [comment] 2018-05-16 06:31
Thanks for opening! Looks like a duplicate of #2876

**Closed by albinekb** 2018-05-16 06:31 UTC
