### ISSUE TITLE
Error adding Plugins

### ISSUE THREAD

**Issue by CarlosCorreaM** [zeit/hyper#2180] opened 2017-09-06 23:53 UTC
![image](https://user-images.githubusercontent.com/23535629/30139623-9450245a-9334-11e7-91f1-76507ceafb7c.png)

        -
        Hyper 1.4.3
        Electron 1.7.5
        win32 x64 10.0.15063

**Comment by CodeTheory** [comment] 2017-09-07 00:28
Due to the lack of information, I'm assuming this is a duplicate of #2173. Please follow the issue template so we have more to go off of, next time 😄

**Closed by CodeTheory** 2017-09-07 00:28 UTC
