### ISSUE TITLE
Weird colors reloading behavior

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#342] opened 2016-07-21 19:06 UTC
When I hot-loaded `hyperterm-one-light` I noticed some colors (like `cyan`) did not update correctly.
I suspect this is a bug either in hterm or our color override logic. 

cc @mike-engel since you've been working on this.

**Comment by mike-engel** [comment] 2016-07-22 00:38
Unfortunately, this looks like it's an issue with hterm. It seems hterm is setting a `style="color: rgba();` attribute right on the text node in `x-row`, which doesn't get changed when the theme gets updated. A full reload, or any colors produced after the theme changes work fine. Some screenshots below for posterity.

<details>
#### Before theme change/after theme change
![screen shot 2016-07-21 at 6 28 03 pm](https://cloud.githubusercontent.com/assets/464447/17043271/4363f690-4f72-11e6-8306-d75d160e4e94.png)

#### the suspect style attribute
![screen shot 2016-07-21 at 6 33 47 pm](https://cloud.githubusercontent.com/assets/464447/17043276/58235184-4f72-11e6-9424-10036cba800f.png)
</details>

**Comment by CodeTheory** [comment] 2016-07-26 21:09
Is this a duplicate of #294

**Comment by mike-engel** [comment] 2016-07-26 22:24
@CodeTheory Doesn't look like it. This is more an hterm bug where it won't update existing rendered colors. #294 seems to be an issue with colors being applied at all.

**Comment by chabou** [comment] 2018-04-16 22:14
Certainly fixed in our v2

**Closed by chabou** 2018-04-16 22:14 UTC
Labels: help wanted, 🐛 Type: Bug, 💚 Priority: Low
