### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by jinyu11** [zeit/hyper#2222] opened 2017-09-16 22:40 UTC
Trying to access config brings me

script c:\Users\jinyo\.hyper.js
line: 5
char: 1
error: 'module' is undefined
code: 800a1391
source: Microsoft JScript runtime error
        -
        Hyper 1.4.6
        Electron 1.7.6
        win32 x64 10.0.15063

**Comment by CodeTheory** [comment] 2017-09-16 22:43
Hi there! I think this is a duplicate of #1996, so I'm going to close this in preference of the original issue. Thanks for confirming the report though!

**Closed by CodeTheory** 2017-09-16 22:43 UTC

**Comment by jinyu11** [comment] 2017-09-16 22:47
AWESOME THANK YOU TIMOTHY
