### ISSUE TITLE
With transparent background on OSX, the header can overlap itself.

### ISSUE THREAD

**Issue by NicksWorld** [zeit/hyper#2917] opened 2018-04-24 01:08 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.13.3 mac os high seria
- **Hyper.app version**: 2.0.0 stable
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/NicksWorld/21ddb662a88fe3fdbde54aa1550d8043
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Partly

## Issue

With mac OSX the ability to make the window transparent in full screen comes with bugs. It is created by the partly-see through window. Using ```css
background-color: rgba(0, 0, 0, 0);``` I am able to make it more apparent. In the bug the header overlaps itself and a line of the terminal creating the effect of ![overlap](https://image.prntscr.com/image/Waeq1ItWR-S8N9HllvlxUw.png).

NOTE: I have the setting on my computer to hide the top bar containing the apple icon. ![setting](https://image.prntscr.com/image/FrbmaBlpSh_U2ayam0x82g.png)

**Comment by timothyis** [comment] 2018-04-24 01:09
Duplicate of #5. Thanks for confirming though. I'll update the title to make it easier to find.

**Closed by timothyis** 2018-04-24 01:09 UTC
