### ISSUE TITLE
$EDITOR is ignored when opening preferences in bash.

### ISSUE THREAD

**Issue by zpnk** [zeit/hyper#822] opened 2016-10-07 23:42 UTC
#### Platform / Shell / Hyper version

OS X, Bash,  0.8.1
#### Steps to reproduce
1. Open Hyper with a bash session.
2. Set `export EDITOR=vim` (or another editor).
3. Hit `cmd+,` to open preferences.
4. `~/.hyper.js` will have opened with `nano`.
#### What I expected

I expected `~/.hyper.js` to be opened with `$EDITOR`, in this case `vim`.
#### What happened instead

`~/.hyper.js` was opened with `nano`.
#### GIF

![example](https://d17oy1vhnax1f7.cloudfront.net/items/0p2632193J1y2s1T0G27/Screen%20Recording%202016-10-07%20at%2004.18%20PM.gif)
#### Details

The editor fallback was added in #517. At that point, the opening command looked like:
`bash -c "exec env ${EDITOR:=nano} ~/.hyper.js"'` ([src](https://github.com/zeit/hyper/pull/517/files#diff-25b2430d616b8fb31c11496b6584bb70R154))

In #575, the double quotes were switched to single quotes, with the command becoming:
`bash -c 'exec env ${EDITOR:=nano} ~/.hyper.js'` ([src](https://github.com/zeit/hyper/pull/575/files#diff-25b2430d616b8fb31c11496b6584bb70R160))

If those two commands are run directly in bash, only the one with double quotes respects the `$EDITOR`.

Two questions:
1. Can anyone else reproduce this?
2. If yes, what is the best approach to fix (keeping in mind cross-shell compatibility)?

I am happy to submit a PR once a potential solution has been agreed on. Thanks for your hard work!

**Comment by iamstarkov** [comment] 2016-10-07 23:44
same here

**Comment by rauchg** [comment] 2016-10-08 00:54
Not related to the issue, but wanted to say you have a beautiful prompt and color scheme 👍

**Comment by timneutkens** [comment] 2016-10-08 15:25
Might just be me saying weird things.. but isn't `export EDITOR=vim` heavily related to your current shell session. `cmd+,` opens a new tab, which is a new shell session with a different pid 😅

**Comment by flybayer** [comment] 2016-10-08 16:26
@zpnk you're right, single quote bash strings don't expand the variable. 

```shell
> echo ${EDITOR}
nvim

>echo '${EDITOR}'
${EDITOR}

>echo "${EDITOR}"
nvim
```

@albinekb in #575 you said your changed worked in `bash`. Did you confirm that the correct editor was opened?

**Comment by OJFord** [comment] 2016-10-09 18:06
Well, at least it opens for you!

```sh
 echo Attempting to open ~/.hyper.js with your $EDITOR
 echo If it fails, open it manually with your favorite editor!
 bash -c 'exec env ${EDITOR:=nano} ~/.hyper.js'
~$  echo Attempting to open ~/.hyper.js with your $EDITOR
Attempting to open /Users/ojf/.hyper.js with your vim
~$ 
```

This is probably a side-note, but possibly part of the problem - I'm pretty sure that should be `:-nano` above; not `:=nano`. The latter will actually assign `'nano'` to `$EDITOR`, while the former will just use it.

**Comment by muescha** [comment] 2016-10-10 16:57
and the default nano color scheme is something wrong at nano - see #838

**Comment by robodair** [comment] 2016-10-11 05:53
Works as expected for opening vscode when I've added:

```bash
export EDITOR=code
``` 
to my `.bash_profile`

Hyper runs `bash -c 'exec env ${EDITOR:=nano} ~/.hyper.js'` in a new tab so if you set `$EDITOR` in one tab the environment variable doesn't exist in the one Hyper actually executes the command in unless it's set in `.bash_profile`

**Comment by dak0rn** [comment] 2016-10-11 06:19
I can reproduce that behavior and I think it happens because bash does not evaluate `.profile`/`.bash_profile` when using `-c`. Adding `-l` forces a login shell and seems to do the trick.
![screen shot 2016-10-11 at 08 19 00](https://cloud.githubusercontent.com/assets/3854533/19260622/61332bec-8f8b-11e6-82ac-5be7e733f17b.png)

**Comment by robodair** [comment] 2016-10-11 06:21
@dak0rn is your `$EDITOR` variable in `.bash_profile` defined with or without `export`?

**Comment by dak0rn** [comment] 2016-10-11 06:22
It's defined with `export`:

```bash
#!/bin/bash
source .bashrc
export EDITOR=vim
```

**Comment by timneutkens** [comment] 2016-10-11 06:24
@dak0rn Possibly related https://github.com/zeit/hyper/issues/699

**Comment by robodair** [comment] 2016-10-11 06:31
Weird
My `.bashrc` is blank, and `.bash_profile` just has 
```bash
export EDITOR=code
```
Output:
![image](https://cloud.githubusercontent.com/assets/8318231/19260816/7d013e48-8fd8-11e6-9004-bd4d07a30db2.png)

**Comment by zpnk** [comment] 2016-10-11 20:02
Hey @timneutkens @robodair - sorry for the confusion regarding the reproduction steps. Thanks for explaining the differences in having `$EDITOR` set in `.bash_profile` vs just in the current shell session. 

I've been testing with `$EDITOR` set via my `.bash_profile`, however today I discovered that it was only setting `EDITOR=vim` without an export. Shame on me! 

Setting `export EDITOR=vim` in `.bash_profile` works for me:

![screen shot 2016-10-11 at 1 01 47 pm](https://cloud.githubusercontent.com/assets/3493970/19286513/e05ed76e-8fb2-11e6-9914-50e81bca8dc7.png)

Although this doesn't explain @dak0rn's experience. 

Adding the `-l` flag does work either way, as long as `$EDITOR` is somehow set in the profile it will still work.

![screen shot 2016-10-11 at 1 01 09 pm](https://cloud.githubusercontent.com/assets/3493970/19286489/c8070916-8fb2-11e6-9a38-561d5f6166b6.png)

Perhaps this could be a useful addition, just to make sure the edge case in covered? Are the any downsides to using `-l`?

**Comment by timneutkens** [comment] 2016-10-11 20:58
@zpnk Ah nice, so this ticket is kind of resolved by that. I agree that adding `-l` would be a good thing. Since otherwise `~/.bash_profile` shouldn't be sourced.. which could lead to `$EDITOR` not being set when opening the tab 🤔 .. on second thought... this should just function right away.. since `$EDITOR` is set by opening the new tab (when a new to is opened `--login` is added to the command automagically. see #699). Still have a feeling fixing #699 might resolve all this.

- Do note I'm not a bash user (ZSH here) and this is all from a Hyper codebase point of view 😉

**Comment by iamstarkov** [comment] 2016-10-13 00:16
`export EDITOR='whatever'` instead of `EDITOR='whatever'` solved it for me

**Comment by roelvan** [comment] 2016-12-08 04:09
This website solved my problem using oh-my-zsh: http://linuxg.net/how-to-change-the-default-editor-in-linux/

**Comment by adrianoresende** [comment] 2017-02-21 12:12
@roelvan Thanks! Solved adding `export EDITOR=sublime -w` in `~/.zshrc`

**Comment by gsklee** [comment] 2017-02-21 13:33
Looks like this issue can be closed.

**Comment by schmittyjd** [comment] 2017-05-29 03:13
I am still having this issue, opening sublime text for me when I have
```
export EDITOR=atom
```
in my ``.zshrc``

**Comment by MartyGentillon** [comment] 2017-05-29 07:03
This has been changed to use the system default editor which is controlled by your window manager.

**Comment by chabou** [comment] 2017-06-03 20:52
Thanks for your help @MartyGentillon. 
Indeed, this issue is outdated.

**Closed by chabou** 2017-06-03 20:52 UTC
