### ISSUE TITLE
Tilde(~) is causing Problems after update

### ISSUE THREAD

**Issue by Jnoack331** [zeit/hyper#2147] opened 2017-08-31 12:59 UTC
-
        Hyper [1.4.2]
        Electron 1.6.12
        darwin x64 16.7.0
        OS: Mac OSX
        shell: zsh
<img width="549" alt="bildschirmfoto 2017-08-31 um 14 57 56" src="https://user-images.githubusercontent.com/17640771/29924329-ef4d0760-8e5c-11e7-8111-785e31c8db1a.png">
<img width="227" alt="bildschirmfoto 2017-08-31 um 14 58 34" src="https://user-images.githubusercontent.com/17640771/29924330-ef520148-8e5c-11e7-815f-6bd1e91b2d31.png">

i think its related to https://github.com/zeit/hyper/issues/2140

**Comment by leo** [comment] 2017-08-31 13:04
Duplicate of https://github.com/zeit/hyper/issues/2140

**Closed by leo** 2017-08-31 13:04 UTC
