### ISSUE TITLE
need better instructions for Linux install

### ISSUE THREAD

**Issue by anthonyettinger** [zeit/hyper#1229] opened 2016-12-15 19:51 UTC
is it possible to get a ppa for Ubuntu based systems?

**Comment by pablopunk** [comment] 2016-12-15 19:53
@anthonyettinger What's wrong with the `.deb` installer? 😜

**Comment by anthonyettinger** [comment] 2016-12-15 20:48
I do not see one. Where is it documented?

**Comment by ppot** [comment] 2016-12-15 20:50
@anthonyettinger https://hyper.is/#installation

**Comment by anthonyettinger** [comment] 2016-12-15 23:03
A ppa would allow me to get updates though. installing manually with .deb is not ideal.

**Comment by toddhalfpenny** [comment] 2016-12-16 15:54
If it's a PPA, then perhaps this is a dupe of https://github.com/zeit/hyper/issues/1115 ?

**Comment by gluons** [comment] 2018-02-02 17:25
Can it be easier by [Snaps](https://snapcraft.io/)? Cross-linux system installation.

**Comment by albinekb** [comment] 2018-02-02 18:28
Yes. We were working on creating a snap but we didn't get around to. There's not much demand and supporting a snap would be extra effort for little usability, but if someone knows how, feel free to PR the snap build scripts and we can work together on getting it out there 🎉

**Comment by gluons** [comment] 2018-02-03 13:12
OK. I'm not serious about that.
I hope one day I can install Hyper via command line easily. PPA or Snaps are fine. 😄 
Love Hyper anyway. 😘

**Comment by philpalmieri** [comment] 2018-05-28 00:51
If no one else is taking this on, i'm going to start playing with it to see if i can get it running as a snap, please leave this open.

**Comment by albinekb** [comment] 2018-05-28 10:56
@philpalmieri that would be amazing, tell me if there's anything we can do to help you 🙏

**Comment by philpalmieri** [comment] 2018-05-28 12:34
I stayed up a bit last night and made a simple Node Snap - https://snapcraft.io/insultme - its actually pretty straight forward, and there are build pipline tools out of the box - ill spend some more time on it tonight and see if i can get a demo running in a dev branch.

**Comment by vinay72** [comment] 2018-08-19 17:06
Yes , it is possible to get a ppa for Ubuntu Based Systems.

**Comment by EfstathiadisDimitris** [comment] 2018-09-06 11:33
If this isn't resolved. I would like to work on it. Just tell me, if someone else is working on it..

**Comment by philpalmieri** [comment] 2018-09-06 12:43
I worked on it for a bit, but got sidetracked with work - I had it compiling to a snap - but having electron issues - go for it! - I won't be able to come back to it for a bit (might try flatpak soon though)

**Closed** 2019-01-18 23:09 UTC
Labels: good first issue, ❔ Type: Question
