### ISSUE TITLE
Scroll bar can not drag

### ISSUE THREAD

**Issue by zhea55** [zeit/hyper#1709] opened 2017-03-28 08:21 UTC
1. I run my react project
2. Webpack print a lot of message
3. I want drag the right scroll bar to scroll up, check the compile info.

but the scroll bar can't drag. Please fix, thanks!

Hyper 1.3.1
Electron 1.4.15
win32 x64 10.0.14393

**Comment by Ra1da35ma** [comment] 2017-04-04 13:25
Please this is important as a primary feature not a __plugin__

-------
thanks

**Comment by MartyGentillon** [comment] 2017-04-15 08:00
This is a duplicate of https://github.com/zeit/hyper/issues/1251

**Comment by Ra1da35ma** [comment] 2017-04-15 08:06
okay. If its a duplicate. close it

**Comment by chabou** [comment] 2017-04-15 08:15
@MartyGentillon you are on fire! 🔥 Thank you for your help!

**Closed by chabou** 2017-04-15 08:15 UTC
Labels: Type: Bug
