### ISSUE TITLE
Copy shortcut

### ISSUE THREAD

**Issue by dcharbonnier** [zeit/hyper#1304] opened 2016-12-23 11:06 UTC
version 1.0.0 on elementary os ubuntu 16.04
may be related to #1121

Shift Ctrl+C do not copy, on the first key press the text get unselected, the command in the menu work

**Comment by christoth** [comment] 2016-12-23 16:33
Shift Ctrl+C does not work for me either with v1.0.0 on Win10 x64.
As above using the the menu works.

**Comment by TylerRick** [comment] 2016-12-23 19:39
Same here. As soon as I press **Ctrl**, the text gets unselected.

**Comment by ppot** [comment] 2016-12-23 22:00
For the deselection it should be fixed in #1218 
For the `ctrl+c` that does not copy, I will make it dupe of #1121

**Closed by ppot** 2016-12-23 22:00 UTC
Labels: Is Duplicate
