### ISSUE TITLE
Crash on AltGr+W or Ctrl+Alt+W

### ISSUE THREAD

**Issue by peterdanis** [zeit/hyper#2179] opened 2017-09-06 16:20 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 7
- **Hyper.app version**: 1.4.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: tried also with default .hyper.js config
- **Relevant information from devtools**:  console in devtools does not show any errors 
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
After pressing AltGr+W or Ctrl+Alt+W hyper crashes with following error:

![image](https://user-images.githubusercontent.com/26599181/30122781-05ded152-9330-11e7-88e7-6498e49415d3.png)

**Comment by chabou** [comment] 2017-09-06 18:02
Duplicate of #2143

**Comment by chabou** [comment] 2017-09-06 18:02
Fixed in `master`

**Closed by chabou** 2017-09-06 18:02 UTC

**Comment by peterdanis** [comment] 2017-09-07 05:27
Thanks. Please consider remaping "pane:close": "ctrl+alt+w" to another key combination. On many keyboards ctrl+alt (= AltGr) is used for typing special characters. Please see: https://blogs.msdn.microsoft.com/oldnewthing/20040329-00/?p=40003

**Comment by chabou** [comment] 2017-09-07 06:09
Thank you to have pointed out this problem.
I reopened #2156. Feel free to suggest shortcut there.
