### ISSUE TITLE
Chinese characters display in an unexpected way

### ISSUE THREAD

**Issue by Phantr4x** [zeit/hyper#1740] opened 2017-04-11 06:56 UTC
![image](https://cloud.githubusercontent.com/assets/5728981/24896333/00a78112-1ec7-11e7-82e6-660d2ad4f586.png)

Hyper 1.3.1
Electron 1.4.15
win32 x64 10.0.14393

**Comment by albinekb** [comment] 2017-04-12 16:12
As a non-chinese speaker I don't see whats wrong with those, what's the expected output? @Phantr4x

**Comment by FateRiddle** [comment] 2017-04-13 01:56
characters overlap on each other, seems like each character tries to fit in the size of an alphabet letter.
The normal look should be '版本'，‘保留所有权利’， if you can see.

**Comment by teddy-error** [comment] 2017-04-13 08:06
Possibly related : #1606

**Comment by teddy-error** [comment] 2017-04-13 08:09
@albinekb Looks like duplicate of #1535

**Comment by albinekb** [comment] 2017-04-13 13:45
Thanks @teddy-error 

Closing as it's a duplicate of #1535

Thanks for the info on what's wrong 👍  There are PRs up that's working on addressing this issue.

**Closed by albinekb** 2017-04-13 13:45 UTC
