### ISSUE TITLE
Cutted font on last screen line

### ISSUE THREAD

**Issue by szachara** [zeit/hyper#1722] opened 2017-04-01 13:31 UTC
If I change font-size to 14px and font-family is `fontFamily: '"Lucida Console", monospace', `, so the font on the last screen line is cutted, similar with `Inconsolata for Powerline` font.

NodeJS: 7.8.0
Hyper: 1.3.1
OS: Windows 10

![2017-04-01 1](https://cloud.githubusercontent.com/assets/86900/24579142/c48bbcf4-16ef-11e7-93f7-fb8b0ad9a571.png)
![2017-04-01 2](https://cloud.githubusercontent.com/assets/86900/24579165/2384f5d6-16f0-11e7-8ace-176b957c73fa.png)

**Comment by MartyGentillon** [comment] 2017-04-18 22:26
This is a duplicate of https://github.com/zeit/hyper/issues/628

**Closed** 2017-04-18 22:32 UTC
