### ISSUE TITLE
Syntax errors in .hyper.js are instantly overwritten

### ISSUE THREAD

**Issue by l-mas** [zeit/hyper#2015] opened 2017-07-19 16:58 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 version 1607 build 14393.105
- **Hyper.app version**: 1.3.3
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
Having a single syntax error in .hyper.js while hyper is running will instantly overwrite the entire file with the default config. Meaning that if you forgot to put a comma after a line and saved it while hyper is running you've just lost your entire config.

**Comment by Stanzilla** [comment] 2017-07-19 22:40
Can confirm this happened to me once

**Comment by AndrewSB** [comment] 2017-07-24 21:41
Can confirm too, I keep my config file in source control though. So it wasn't too bad

**Comment by chabou** [comment] 2018-04-24 23:09
I think this is fixed in our v2. I can't reproduce.
Please open a new issue if it happens again

**Closed by chabou** 2018-04-24 23:09 UTC
Labels: 🐛 Type: Bug
