### ISSUE TITLE
Visual bug on resuming computer after hibernation

### ISSUE THREAD

**Issue by fberrez** [zeit/hyper#3199] opened 2018-08-31 07:24 UTC
- [ X ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ X ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 18.04 bionic
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/fberrez/72db694724c886a560c31427ba626f29
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

When I turn on my computer with hyper opened after a hibernation, I have a visual bug. See below:

![hyper-bug](https://user-images.githubusercontent.com/25006376/44898458-46d80400-acff-11e8-9953-918e5e548784.png)

Steps:
1- Open your Hyper terminal
2- Suspend your PC
3- Turn on your PC
4- Your Hyper terminal will have the visual bug.

**Comment by albinekb** [comment] 2018-08-31 11:49
Duplicate of #2876

**Closed by albinekb** 2018-08-31 11:49 UTC
