### ISSUE TITLE
Displaying extra command on tab completion (zsh)

### ISSUE THREAD

**Issue by nkzawa** [zeit/hyper#24] opened 2016-07-03 05:18 UTC
![axyrov1lga](https://cloud.githubusercontent.com/assets/775227/16543845/0b3b897a-40f6-11e6-9691-8f4a92e7a2e6.gif)

You cannot delete it with backspace.

**Comment by rauchg** [comment] 2016-07-03 20:37
This might be fixed by `0.2.0`. Let me know if it still happens when you upgrade.

**Comment by nkzawa** [comment] 2016-07-03 21:54
It still happens.

**Comment by rauchg** [comment] 2016-07-03 23:40
😢

**Comment by rauchg** [comment] 2016-07-05 04:20
Please retry with `0.3.1`.

**Comment by nkzawa** [comment] 2016-07-05 05:56
same 😭

**Comment by nkzawa** [comment] 2016-07-09 20:31
It's fixed when I tried the master branch.

**Comment by delvedor** [comment] 2016-07-17 10:22
Same problem here!

**Comment by brunolazzaro** [comment] 2016-07-18 21:37
Dropping a bit on info: This happens with certain ZSH themes, not all of them. It might have to do with how some themes modify the shell prompt.

**Comment by MattKetmo** [comment] 2016-07-27 13:29
I'm using ZSH too and reproduce this bug except when I remove every special **unicode characters** from the prompt (like the ➜ in `robbyrussell` theme or the "fat-arrow" in Powerline-like themes).

**Comment by yesmeck** [comment] 2016-08-10 08:17
Cann't reproduce on current master(https://github.com/zeit/hyperterm/commit/7398593bc36b9624db25f3faee21c3a35b1ca415) with zsh + robbyrussell theme , seems like fixed?

![image](https://cloud.githubusercontent.com/assets/465125/17546631/bb2da4a2-5f15-11e6-9826-908cb3e640ce.png)

**Comment by brunolazzaro** [comment] 2016-08-10 14:51
I think it is, can't reproduce either on latest versions.

**Comment by lordgiotto** [comment] 2016-08-10 15:07
Same problem here with last master and zsh 5.2.
Also for me, like @MattKetmo, removing any special unicode char from prompt fixes the issue!

**Comment by hahanbyul** [comment] 2016-08-15 18:45
I used "pure" theme and it also unicode char in the prompt. Same problem occured. Removing theme solved this issue.

**Comment by hpcodecraft** [comment] 2016-08-26 18:05
Same problem here, ZSH theme "avit".
<img width="179" alt="bildschirmfoto 2016-08-26 um 20 04 06" src="https://cloud.githubusercontent.com/assets/1476865/18015525/5ca3fcfa-6bc8-11e6-8020-340d336c8eb8.png">

**Comment by urbantrout** [comment] 2016-12-13 14:39
same problem here. hyper@1.0.0, zsh@5.3, pure-prompt@1.4.1

**Comment by dotWee** [comment] 2017-01-05 20:03
Same issue here! 

hyper@1.0.1 zsh@5.3.1 
With hyperzsh theme: https://github.com/tylerreckart/hyperzsh

**Comment by urbantrout** [comment] 2017-03-24 12:19
Fixed by adding this to my .zshrc

```
# You may need to manually set your language environment
export LANG=de_AT.UTF-8
```

**Comment by chabou** [comment] 2017-04-13 20:17
Seems fixed

**Closed by chabou** 2017-04-13 20:17 UTC
Labels: Status: Awaiting Response
