### ISSUE TITLE
new version announcement make the current version impossible to use 

### ISSUE THREAD

**Issue by dcharbonnier** [zeit/hyper#1807] opened 2017-05-10 04:32 UTC
Using the version 1.3.1 on linux
The pink "popup" is on the bottom right, covering the current editor line and no option to make it disappear.
There should at least be an option to hide it, and/or a different position.

**Comment by nbarray** [comment] 2017-05-19 19:28
Hi !
I'd like to work on that issue, yet it feels like the "expected" enhancement is not clear.

I just checked out 1.3.1 on linux and there is an [x] button available to close the "popup".

- Do you want to be able to hide it for future session when starting hyper ?
(yet if a newer version is available do you expect to see it again or not ?)
- Do you want to move it somewhere else on the term screen (then the situation is the same for other lines) ?

If we can define what we are expecting to do with this issue I'd love to work on it ;)

Cheers

**Comment by chabou** [comment] 2017-05-29 19:47
@dcharbonnier I can't reproduce it on MacOS. I have a button to hide this notification. Can you send a screenshot?

@nbarray There is a related issue: #460 to enhance this notification. It is an old issue and maybe need to be revalidated by the community.

**Comment by Lindenk** [comment] 2017-07-04 14:30
I think the idea here is to disable the notification entirely based on a setting. Anyone who manages their installation of hyper with a package manager does not ever want to receive a 'New Version Available' message.

**Comment by nhagen** [comment] 2017-11-06 14:54
I'm getting this notification for canary releases--at the very least this should only be recommending stable releases.

**Comment by chabou** [comment] 2017-11-06 19:48
@nhagen Do you have configured your update channel to receive canary release? 🤔

**Comment by nhagen** [comment] 2017-11-07 20:25
Not specifically. I'm installed via AUR on arch with an older version of the source (1.4.8). Not indication in the PKGBUILD that hyper should be tracking canary.

**Comment by scorpiodawg** [comment] 2017-12-15 01:30
On my 4K res monitor, there is no `x` to close this, but when I click somewhere near the bottom right, it went away.

**Comment by grafa** [comment] 2018-01-20 06:21
That notification is really anoying. Please add config property to turn off checking new versions.

**Comment by Stanzilla** [comment] 2018-04-23 00:09
There is a hide button now

**Closed by Stanzilla** 2018-04-23 00:09 UTC
Labels: good first issue, 🎨 Type: Enhancement, 👀 Awaiting Response, 💛 Priority: Medium, 😰 Can't Reproduce
