### ISSUE TITLE
[Windows] window does not snap to edges when dragged there

### ISSUE THREAD

**Issue by AlmirKadric** [zeit/hyper#1387] opened 2017-01-11 10:04 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: master branch
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: "default"
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
On windows 10 there is a feature which allows you to drag windows to edges (top, left, right, corners) and the window will be snapped and resized accordingly (full screen, half-screen, quarter screen)

**Comment by CodeTheory** [comment] 2017-01-11 10:07
Duplicate of #1128. Fixed in #1307.

**Closed by CodeTheory** 2017-01-11 10:07 UTC

**Comment by AlmirKadric** [comment] 2017-01-11 10:14
Thanks!!!
Wow i missed that by 4 hours :\

**Comment by jkymarsh** [comment] 2017-01-12 04:32
On 1.1.0 and snapping still doesn't work for me.

I'm seeing comments about Windows system settings interfering with snapping, but snapping works fine in other apps across my machine.
