### ISSUE TITLE
a % symbol shows up on every new tab

### ISSUE THREAD

**Issue by pingcheng** [zeit/hyper#3650] opened 2019-05-10 14:41 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.14.4
- **Hyper.app version**: 3.0.2 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
Every time when I opened a new tab or new window, a % would show up on the very first line. The old version wont have this
![Screen Shot 2019-05-11 at 12 38 51 am](https://user-images.githubusercontent.com/8447539/57535413-858d8600-7385-11e9-92e9-53652dcdcfa2.png)

**Comment by kgolinski** [comment] 2019-05-10 15:03
Take a look at this: https://github.com/zeit/hyper/issues/2144#issuecomment-489674376

**Comment by chris-c-thomas** [comment] 2019-05-10 18:47
I was having the same issue. 

<img width="543" alt="Screen Shot 2019-05-10 at 1 40 51 PM" src="https://user-images.githubusercontent.com/22353987/57549782-15054b80-732a-11e9-9fef-05dae397035e.png">

The solution for now seems to be adding `unsetopt PROMPT_SP` to your .zshrc file. 

We can probably close this issue since it's a duplicate of #2144

**Comment by ppot** [comment] 2019-05-10 21:34
Duplicate of #2144

**Closed by ppot** 2019-05-10 21:34 UTC
Labels: 👯‍♀️ Is Duplicate
