### ISSUE TITLE
Broken tilde key on german keyboard

### ISSUE THREAD

**Issue by hpohlmeyer** [zeit/hyper#2153] opened 2017-08-31 18:08 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Sierra (10.12.6)
- **Hyper.app version**: 1.4.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/hpohlmeyer/293b27027da45b31fa047ba563fd3dde
- **Relevant information from devtools** No definition for keyCode: 229
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
I am on a german keyboard layout, which "caches" the tilde key, for combination with other characters. Normally you could get the tilde character by pressing its shortcut (alt+n) and hit space. Since the tilde can not be combined with the space character, this results in the single tilde character (~). Since the last update, this behavior is broken.
The tilde key is stashed inside the text cursor and you type behind it. The only way to get the tilde character is to enter it multiple times. However, it will still be displayed inside the text cursor.

Here is a video, that should do a better job of explaining the problem:
![tilde-2](https://user-images.githubusercontent.com/6564077/29938118-fa9f337e-8e87-11e7-9176-474f93ea54dd.gif)

**Comment by moisesnandres** [comment] 2017-08-31 23:17
I was going to create a similar issue.
I also can't combine special characters with letters, for example ˜ with n or ´with e.
I'm using MacOS Sierra (10.12.6) as well.

**Comment by fecabianchi** [comment] 2017-09-01 14:22
#2140
Probably the same issue.

**Comment by lucasqueiroz** [comment] 2017-09-01 17:15
Same issue here. US International keyboard on Mac Sierra.

**Comment by chabou** [comment] 2017-09-01 17:44
Duplicate of #2140

Thank you for your feedback

**Closed by chabou** 2017-09-01 17:44 UTC

**Comment by chabou** [comment] 2017-09-01 17:45
Duplicate of #2140

**Comment by chabou** [comment] 2017-09-01 17:45
Thank you for your feedback
