### ISSUE TITLE
OS X: hyper app always running

### ISSUE THREAD

**Issue by bruc3mackenzi3** [zeit/hyper#4383] opened 2020-03-16 13:41 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- OS X Mojave 10.14.6: 
- 3.0.2: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- N/A _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- is vanilla: 
## Issue

In OS X hyper terminal is always running unless I right click it in the Dock and manually quit.  Closing the window does not kill the application.  In addition on startup Hyper is always running.

If this is expected behaviour there should be an option to disable background running.  From what I can tell there currently isn't.

I'm running OS X Mojave 10.14.6 and latest Hyper release 3.0.2.

**Comment by LabhanshAgrawal** [comment] 2020-03-16 15:15
The manual quit behaviour is default in OS X, and it also reopens apps by default on startup.

**Comment by LabhanshAgrawal** [comment] 2020-03-20 11:18
@bruc3mackenzi3 can you close this, as this is intended behaviour for macOS.

**Closed** 2020-03-22 01:20 UTC
