### ISSUE TITLE
Ctrl-based shortcuts not working in Windows

### ISSUE THREAD

**Issue by nolanlawson** [zeit/hyper#1152] opened 2016-12-13 00:46 UTC
- **OS version and name**: Windows 10 14987.1001
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [gist](https://gist.github.com/nolanlawson/db509228a0cccd32fc9d6770750821da)
- **Relevent information from devtools** : N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

Typing Ctrl-A, Ctrl-R, Ctrl-E etc. does not result in the expected behavior (e.g. start-of-line for Ctrl-A, search history for Ctrl-R). Instead Ctrl-A selects all the text and the other ones apparently do nothing.

This does not seem to be related to the underlying shell because I can reproduce in both `bash.exe` and Git Bash (`"C:\Program Files\Git\bin\sh.exe" -l`). May be related to #1058.

[Discussion on Twitter](https://mobile.twitter.com/halkeye/status/808464486411575296)

**Comment by CodeTheory** [comment] 2016-12-13 00:51
Duplicate of #1121. Please extend your issues there.

**Closed by CodeTheory** 2016-12-13 00:51 UTC
