### ISSUE TITLE
Cursor is not aligned with the text

### ISSUE THREAD

**Issue by d3lm** [zeit/hyper#2763] opened 2018-03-15 15:33 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra 10.13.1
- **Hyper.app version**: 1.4.8 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Configuration](https://gist.github.com/d3lm/c4ca3a284a1704b3d971f17b11aad030)

## Issue
I have noticed that the cursor is not 100% aligned with the text.

![image](https://user-images.githubusercontent.com/12571019/37473190-b95dfa1c-2865-11e8-9fbb-ab53cc9964da.png)

**Comment by bgw** [comment] 2018-03-19 03:12
I'm not sure what the issue is. The cursor isn't aligned with the `d`, but that's because there's an ascender and no descender for that glyph. It's more closely aligned with the arrow, though not perfectly aligned, however, that might just be because the glyph isn't perfectly aligned.

![selection_039](https://user-images.githubusercontent.com/180404/37576086-baf5f3d2-2ae7-11e8-8bc5-0acc6e148eec.png)

- Can you try this with the latest 2.x canary (https://github.com/zeit/hyper/releases)? It uses xterm.js instead of hterm, so the entire rendering pipeline is different.

- Can you try pasting a unicode block character (█) into your terminal? That should be the same height as the cursor.

**Comment by d3lm** [comment] 2018-03-21 14:15
Ok, so the canary version and the new rendering pipeline works perfectly! I really love it, because it's now exactly the same experience as in the Terminal App on Mac. The only thing that I dislike is that the scrollbar flashes up for a second when I start Hyper. It would be nice to have an option for disabling the scrollbars completely.

You guys are doing a great job! I really enjoy Hyper so far, especially now with the new rendering 👍

**Comment by albinekb** [comment] 2018-03-21 17:17
I'm closing this off as it's fixed in 2.0 🔥 Thanks for confirming 🙏

**Closed by albinekb** 2018-03-21 17:17 UTC
