### ISSUE TITLE
config.json does not update Window Position after 2nd display is unplugged

### ISSUE THREAD

**Issue by a-heryani** [zeit/hyper#1869] opened 2017-05-25 11:06 UTC
Dell XPS-9560 (3840x2160) connected via HDMI to a 27" Dell monitor running at 1920x1080. I had Hyper term window on the 27" Dell monitor. Finished for the day and shutdown all applications including Hyper. Shutdown down laptop. Disconnect HDMI.

Later in the evening at home, turned on laptop. Started VS Code, Chrome and Postman (all apps that were running on the external monitor earlier), they all came up fine with the window sizes a bit wonkey due to the resolution switch.

However the Hyper windows was not visible even though the program was running. I looked at config.json and the Window Position was set to [4000, 50]. Obviously outside of the laptop's visible area. Closed down hyper and manually changed to [0,0]. 

Not sure if this is a bug. Unable to replicate as I was working at that remote location just for today.

-

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by MartyGentillon** [comment] 2017-05-25 17:54
It's probably a bug.  But a simple workaround would be to use one of Windows' window moving keyboard shortcuts like `win+left`.

**Comment by albinekb** [comment] 2017-05-26 09:09
#1802

**Comment by mattwoolnough** [comment] 2017-05-30 23:00
`win+left` doesn't help me. I've deleting all Hyper files and reinstalling, but still the Hyper window appears off screen.   Where can the Window Position setting be found?

The values in C:\Users\<username>\AppData\Local\hyper\app-1.3.3\resources\app\config.jsconfig.js (if that's the correct place to be looking) seem to have default values on my install: 

`const winCfg = new Config({
  defaults: {
    windowPosition: [50, 50],
    windowSize: [540, 380]
  }
});`

**Comment by a-heryani** [comment] 2017-05-30 23:05
the config.json file is in \AppData\Roaming\Hyper

**Comment by mattwoolnough** [comment] 2017-05-30 23:11
Editing `%APPDATA%\Hyper\config.json` and changing 
windowPosition: [2560, 708]
to: 
windowPosition: [50, 50]

got me working again.
thanks

**Comment by Xapphire13** [comment] 2017-09-19 17:38
Same issue here, I always have to edit `%appdata%\Hyper\config.json` each time I remove monitors from my laptop, or I remote into my machine.

<kbd>Win</kbd> + <kbd>arrow</kbd> also does **not** move the Hyper window when it's outside of the available desktop space. I feel this is the bigger bug.

**Comment by ppot** [comment] 2017-09-19 23:15
I should really take time to fix this 😂.

**Comment by lauhayden** [comment] 2017-09-24 05:56
Can reproduce. If Hyper is open while 2nd monitor is disconnected, position will update. However, if Hyper is not open while 2nd monitor is disconnected, there is absolutely no way other than edition the config.json to bring the window back. <kbd>Win</kbd>+<kbd>Arrow</kbd> keys do not work, and neither does the '<kbd>Shift</kbd>+ right-click on task bar icon -> `move`' trick that usually works.

**Comment by darkdreamingdan** [comment] 2017-09-27 23:25
This is horrendous, but i found using the Task Manager to maximise seems to get it back on screen:

![image](https://user-images.githubusercontent.com/124611/30942515-889190da-a3e3-11e7-8795-3ba1ed8fcabe.png)

**Comment by darkdreamingdan** [comment] 2017-11-14 00:20
Above fix doesn't seem to work in Hyper 2.x canary releases, because there are multiple processes running.  I've found another workaround though.

1. Access the **Properties** menu of any shortcut to Hyper

- You can create a shortcut on desktop, or in a folder, and right click and choose **Properties**
- If Hyper is pinned to your start bar, close it down, then use shift+right click and choose **Properties**
- If Hyper is in Start Menu, right click, under "More" choose "Open File Location".  Then right click on the shortcut, and choose **Properties**

2. Under the **Shortcut** tab, set **Run** to `Maximised`.  Hit OK.

![image](https://user-images.githubusercontent.com/124611/32756336-6b14a2f0-c8d1-11e7-9840-f6798f075f85.png)

3. Launch with your modified shortcut, and it'll open maximised on your screen.

**Comment by chabou** [comment] 2017-11-14 08:22
When restoring, window position should be validated and corrected if needed.

**Closed** 2018-03-02 21:11 UTC
Labels: Platform: Windows, Type: Bug, help wanted

**Comment by Terrabits** [comment] 2018-06-27 16:57
My go-to for windows that are stuck off-screen is `Alt+Space` then `M` (move), then arrow keys to move the window back on screen. Also, if you move the window with the arrows, then move your mouse (I don't know why you need to use the arrows first...) it will automatically move to your mouse location.
