### ISSUE TITLE
Failure to update

### ISSUE THREAD

**Issue by drmilhous** [zeit/hyper#2004] opened 2017-07-15 22:37 UTC
I had installed Hyper previously and now it will not update.  I removed the program and re-installed the newest version.  It still says that I cannot update plugins. "Check '.hyper_plugins/npm-debug.log" for more information", but no such file exists.  Any help would be appreciated. 
-

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by CodeTheory** [comment] 2017-07-15 22:47
Node 8/npm 5? Hyper doesn't currently work with these. You can use the current master or downgrade node/npm for now until we release. Sorry 😞

**Comment by xkawi** [comment] 2017-07-16 03:59
Encountered the same issue here.

Hyper 1.3.3 (1.3.3.1754)
Node v6.11.1
npm v3.10.10
macOS Sierra (10.12.5)

**Comment by RoyHP** [comment] 2017-07-19 13:34
@CodeTheory Any idea when Hyper will release with support for Node 8/NPM 5? I haven't been able to install packages since I updated ( #1916 ). I'm not familiar with the release schedule, if there is any, but curious.

**Comment by RichDonnellan** [comment] 2017-08-03 18:10
@CodeTheory Any insight into the @RoyHP question?

Appreciate the hard work put into this application! 👏

**Comment by CodeTheory** [comment] 2017-08-11 22:42
@RoyHP @RichDonnellan Sorry for the late reply.

There will be a Hyper release _really_ soon, I promise. We're working on getting current master released as we speak. 🤞

**Comment by timothyis** [comment] 2018-02-14 14:03
Hi again, could any of you try the canary release and see if the issue is fixed?

**Comment by Stanzilla** [comment] 2018-04-23 03:12
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Closed by Stanzilla** 2018-04-23 03:12 UTC
