### ISSUE TITLE
Make fullscreen look pretty (Title bar is transparent and overlaps content on fullscreen)

### ISSUE THREAD

**Issue by leo** [zeit/hyper#5] opened 2016-07-02 09:19 UTC
Currently, the title bar looks like this:

<img width="370" alt="screen shot 2016-07-02 at 11 17 53" src="https://cloud.githubusercontent.com/assets/6170607/16539545/d6309d42-4046-11e6-80e5-aa3c32294578.png">

**Comment by dariocravero** [comment] 2016-07-02 09:59
@leo may that depend on something else on your config? I can see it right
<img width="573" alt="screen shot 2016-07-02 at 10 58 43" src="https://cloud.githubusercontent.com/assets/376268/16539749/0555b308-4044-11e6-906e-a8c2e7fa891d.png">
However, if I go with my mouse to the top I can force that view that you got
<img width="573" alt="screen shot 2016-07-02 at 10 58 38" src="https://cloud.githubusercontent.com/assets/376268/16539752/1a4189ea-4044-11e6-9f65-4c01fe70dac9.png">

**Comment by bastilian** [comment] 2016-07-02 10:11
I think there just needs to be a style applied to the title bar to cover what is beneath it.

**Comment by leo** [comment] 2016-07-02 11:10
@dariocravero Yep! The bug only appears when making the title bar visible using the cursor.

@bastilian Probably, yes! Haven't looked into implementing it yet.

**Comment by rauchg** [comment] 2016-07-02 22:46
@leo how can I reproduce this?

**Comment by leo** [comment] 2016-07-02 23:37
@rauchg Click on the green traffic light to make the app go fullscreen. After that, slowly move your cursor from the middle of the app to the menu bar at the top. At some point, the title bar (which contains the traffic lights) should show up and look like on my screenshot.

**Comment by rauchg** [comment] 2016-07-04 23:15
woah good catch @leo

**Comment by albinekb** [comment] 2016-08-06 00:34
In the latest Hyperterm release (`0.7.1`) it looks like this: 

![image](https://cloud.githubusercontent.com/assets/5027156/17453568/2888e99e-5b7e-11e6-966c-5837c78f5d53.png)

However, there's still some visual issues with tabs: 
![image](https://cloud.githubusercontent.com/assets/5027156/17453573/3e6cba42-5b7e-11e6-98dc-c647f65efc50.png)

![image](https://cloud.githubusercontent.com/assets/5027156/17453575/437f92d4-5b7e-11e6-9ef1-c853d8f0f054.png)

**Comment by efegurkan** [comment] 2016-08-06 06:38
#127 is also related i believe.

**Comment by CodeTheory** [comment] 2016-09-25 22:37
Here's my proposal.

Fullscreen reacts normally with no traffic lights:
<img src="https://cloud.githubusercontent.com/assets/1695613/18818715/13122708-8381-11e6-8b93-15c9320fc1fd.png" width="470" height="359">

And if we can detect when the user hover at the top/the menu bar with the traffic lights drops down, we apply a gradient over the HyperTerm header section:
<img src="https://cloud.githubusercontent.com/assets/1695613/18818718/39c4cec8-8381-11e6-8ac8-f2537ad10258.png" width="470" height="359">

This way the user has what they want in full screen and when the traffic lights drop down, they are accessing what they want without an ugly interaction between multiple elements.

**Comment by mattiascaricato** [comment] 2016-12-14 02:54
@CodeTheory how could I help to get this done?

**Comment by lyndsysimon** [comment] 2017-02-17 18:42
This seems to be fixed in 1.2.1.

**Comment by CodeTheory** [comment] 2017-06-24 22:19
Not fixed @leo 
![image](https://user-images.githubusercontent.com/1695613/27512285-90a581dc-5933-11e7-82d0-eff41e9ff9fe.png)

**Comment by leo** [comment] 2017-06-25 10:14
@CodeTheory That's related to the theme, isn't it? Works fine for mine. Why is the issue open again now? Have you tested with the default one?

**Comment by mxmzb** [comment] 2017-07-08 11:45
freshly installed hyper terminal without any plugins or themes on my mac shows the same issue (you have to actually fullscreen and it shows only when you move the mouse to the top edge of the display).

**Comment by CodeTheory** [comment] 2017-07-11 21:09
Yeah, the same issue applies to vanilla hyper @leo 
![image](https://user-images.githubusercontent.com/1695613/28090777-5d29b594-6685-11e7-9e4e-ef77d176f85d.png)

Custom red background set in the config:
![image](https://user-images.githubusercontent.com/1695613/28090798-734fd312-6685-11e7-8522-b39c62b34b25.png)

The title/tabs bar should ideally slide down with the bar that contains the traffic lights and has the shadow and then also the bar should have some sort of non-intrusive background like the gradient I showed before.

**Comment by ryzokuken** [comment] 2018-01-27 06:48
A ton of really erratic behavior in fullscreen really puts me off:

1. The tab bar should not have a margin/empty space for the traffic lights. It might look okay for a single tab, certainly looks ugly for multiple tabs.

2. The custom bar that slides down looks plain ugly, use the standard MacOS titlebar instead.

# Actual (Hyper 1.4.8)

<img width="559" alt="screen shot 2018-01-27 at 12 11 24 pm" src="https://user-images.githubusercontent.com/13121330/35469509-e47f88a2-035b-11e8-8d16-e9a92af5fb27.png">
<img width="562" alt="screen shot 2018-01-27 at 12 11 35 pm" src="https://user-images.githubusercontent.com/13121330/35469510-e4b648ec-035b-11e8-8c2a-e235ed321145.png">

# Expected (Firefox 58.0)

<img width="1680" alt="screen shot 2018-01-27 at 12 10 50 pm" src="https://user-images.githubusercontent.com/13121330/35469513-f2816f6a-035b-11e8-9b09-e50e3d3dbc1f.png">
<img width="1680" alt="screen shot 2018-01-27 at 12 11 01 pm" src="https://user-images.githubusercontent.com/13121330/35469514-f2b8d432-035b-11e8-9edd-aa4ff0e135aa.png">

# Final checklist of suggestions

- Keep the traffic lights when not in fullscreen
- Make the traffic lights disappear (without leaving any space) when switching to fullscreen
- When the user brings down the menubar, a thin MacOS titlebar should slide in alongside the traffic lights.

**Comment by ryzokuken** [comment] 2018-01-27 06:53
P.S. Apps like VSCode and Atom do the same, so that rules out "it must not be possible/easy in electron"

<img width="1210" alt="screen shot 2018-01-27 at 12 19 23 pm" src="https://user-images.githubusercontent.com/13121330/35469549-c8d382ec-035c-11e8-98eb-9fb864e1758e.png">
<img width="1680" alt="screen shot 2018-01-27 at 12 19 48 pm" src="https://user-images.githubusercontent.com/13121330/35469550-c9021fee-035c-11e8-81d2-ad5209998909.png">
<img width="1680" alt="screen shot 2018-01-27 at 12 19 59 pm" src="https://user-images.githubusercontent.com/13121330/35469551-c931c118-035c-11e8-9931-57b8e4b74b15.png">

**Comment by ShumailAhmed123** [comment] 2018-11-11 20:47
Hi, 
I am computer Science student. I am new to GitHub and I would like to make my first contribution. Anyone here please help me or guide to make my first contribution. 
Thanks

**Closed** 2019-09-11 02:20 UTC
Labels: good first issue, help wanted, 🎨 Type: Enhancement
