### ISSUE TITLE
Language support issue!!

### ISSUE THREAD

**Issue by sundancekid1108** [zeit/hyper#1833] opened 2017-05-16 02:35 UTC
I'm glad about this beautiful app
But I can't use Korean language
How can I Fix it??

Hyper 1.3.3
Electron 1.4.16
darwin x64 16.5.0

**Comment by albinekb** [comment] 2017-05-19 16:58
What's not working? @sundancekid1108

How to reproduce?

**Comment by albinekb** [comment] 2017-05-20 03:49
Duplicate of #410, write there what's not working and how we can test it to work on it :)

**Closed by albinekb** 2017-05-20 03:49 UTC
Labels: Status: Awaiting Response, Type: Compatibility
