### ISSUE TITLE
JavaScript error in main process

### ISSUE THREAD

**Issue by isaacs** [zeit/hyper#225] opened 2016-07-18 07:09 UTC
Seems to be triggered by the hypterterm-1password plugin, so it might be a problem with that extension.  Figured I'd share it anyhow, since probably this shouldn't be possible anyway.

```
Uncaught Exception:
Error: watch /Users/isaacs/.node-spawn-wrap-24946-c86a459da0b6 ENOENT
    at exports._errnoException (util.js:949:11)
    at FSWatcher.start (fs.js:1433:19)
    at Object.fs.watch (fs.js:1460:11)
    at Gaze._watchDir (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:288:30)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:357:10
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:422:5
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
```

**Comment by SamVerschueren** [comment] 2016-07-18 10:38
Getting the exact same error when I try to use `nyc`

```
$ nyc ava
```

**Comment by johanbrook** [comment] 2016-07-25 21:25
I got this after installing `hyperterm-colors` and `hyperterm-spacegray`:

<img width="532" alt="skarmavbild 2016-07-25 kl 23 21 26" src="https://cloud.githubusercontent.com/assets/437261/17117973/e894861c-52be-11e6-9fe1-6d864a26e29e.png">

This was for a first time install, couldn't repro for subsequent installs of the plugins.

**Comment by xjamundx** [comment] 2016-08-11 21:24
Yeah @SamVerschueren. I get this error right now and I'm runing running `ava` in another window (not-hyperterm).

**Comment by matheuss** [comment] 2016-09-01 02:14
Since this has been reported a lot of times, I'm going to mark it as `Priority: high`. 

Related/duplicates: #357, #401, #444, #542, #564, #680

**Comment by matheuss** [comment] 2016-09-01 02:22
Anyone have any insight on this? Can this exception be safely ignored?

**Comment by isaacs** [comment] 2016-09-02 21:32
I no longer believe that this is related to `hypterterm-1password`.  It's definitely got something to do with spawn-wrap and nyc.  Not clear how those are causing this error, though.

**Comment by SamVerschueren** [comment] 2016-09-03 12:12
I have the same issue with nyc without the 1password plugin.

**Comment by H1rag4mi** [comment] 2016-09-06 07:43
I have the same error without any plugins :(

**Comment by whitelynx** [comment] 2016-09-11 17:04
@isaacs If #587 and #444 actually are duplicates of this (as @matheuss has suggested by closing them in favor of this), then it doesn't even seem related to either `nyc` _or_ `spawn-wrap` directly; the paths `/Users/hq/.hyperterm_plugins/node_modules/.staging` (from #587) and `/Users/iradchenko/.google-cloud-sdk.staging` (from #444) seem unrelated. I know I've gotten this type of error without ever using `nyc`; I'm pretty sure I don't have any projects on my system which use Istanbul.

It does seem like @rauchg's [comment](https://github.com/zeit/hyperterm/issues/542#issuecomment-237086207) on #542 might be our best lead, since `gaze` does seem to be the common source of these errors, and it seems that it's watching files it shouldn't be. (ones outside the HyperTerm config directory)

**Comment by whitelynx** [comment] 2016-09-11 17:16
Pretty sure this is because [we don't handle the `error` event from `gaze`](https://github.com/zeit/hyperterm/blob/aaed99abac97a3d6b1766f194522a69e8a994bcb/app/config.js#L15). According to @shama's [comment](https://github.com/zeit/hyperterm/issues/542#issuecomment-237132139) on #542, the bug was fixed on `gaze`'s side, but that just means the error now gets emitted from the `gaze` object, instead of being unhandled on the `FSWatcher` object. We still need to handle that event in HyperTerm's code, or it will crash the process in the same way.

**Comment by deeperx** [comment] 2016-09-12 16:50
#706 Another one, probably dup, and originating from `.hyperterm_plugins` with _slightly_ different error stack.

**Comment by isaacs** [comment] 2016-09-12 22:26
@whitelynx Ah, that's interesting!  I wonder if gaze is incorrectly watching files that are being created in the home directory by spawn-wrap in folders like `~/.node-spawn-wrap-xxxxxx`, and then when the process ends and those files disappear, it freaks out with an ENOENT.

**Comment by brandondoran** [comment] 2016-09-15 23:28
I'm getting this with `nyc` as well. Here's my stacktrace:
```
Uncaught Exception:
Error: watch /Users/brandon/.node-spawn-wrap-57998-93b051b6d4bb ENOENT
    at exports._errnoException (util.js:949:11)
    at FSWatcher.start (fs.js:1433:19)
    at Object.fs.watch (fs.js:1460:11)
    at Gaze._watchDir (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:288:30)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:357:10
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:422:5
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at Object.forEachSeries (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:83:3)
```

**Comment by isaacs** [comment] 2016-09-15 23:52
I was able to work around this with the following patch:

```diff
diff --git a/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js.original b/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js
index fe80d80..b684d35 100644
--- a/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js.original
+++ b/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js
@@ -296,9 +296,9 @@ Gaze.prototype._watchDir = function (dir, done) {
           done(null, dir);
         }
       }, delay + 100);
-    })
+    }).on('error', function (err) {})
   } catch (err) {
-    return this._handleError(err);
+    return this
   }
   return this;
 };
```

Not sure if this is helpful, or should be sent upstream to gaze, or what.

**Comment by H1rag4mi** [comment] 2016-09-16 08:44
This commit on gaze seems to fix the error:
https://github.com/shama/gaze/commit/264101644d105f010e382e371db4eda0e45cbdfd

**Comment by krzkaczor** [comment] 2016-09-20 07:37
@H1rag4mi patched it manually and now it seems to fail only when `hyperterm` is in the background.

**Comment by vors** [comment] 2016-09-25 03:40
Got the same, when hyperterm was in the background
![image](https://cloud.githubusercontent.com/assets/816680/18812865/0dbe16bc-8297-11e6-8f6b-b51971da5220.png)

**Comment by tleunen** [comment] 2016-10-10 17:20
Same error, also when using nyc.

```
Uncaught Exception:
Error: watch /Users/tommy.leunen/.node-spawn-wrap-14935-c1542e645938 ENOENT
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at Gaze._watchDir (/Applications/Hyper.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:288:30)
    at /Applications/Hyper.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:357:10
    at iterate (/Applications/Hyper.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/Hyper.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
    at /Applications/Hyper.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:422:5
    at iterate (/Applications/Hyper.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/Hyper.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
```

**Comment by tleunen** [comment] 2016-10-11 14:19
@H1rag4mi I made the fix on my local app and I still have the errors :/ Looks like what @krzkaczor describes...

**Comment by jcoetzee** [comment] 2016-10-14 10:18
Don't know if this helps but I just got the same error when `mv`ing a directory just after creating it. Furthermore subsequent `mkdir`s often (but not always) throw the exception as well. I can reproduce it on my machine; although I sometimes have to do the `mv` multiple times to trigger. Also note every subsequent exception references the original dir (the one that was `mv`ed). OS X 10.11, HyperTerm 0.8.1. 
<img width="532" alt="screen shot 2016-10-14 at 12 11 49 pm" src="https://cloud.githubusercontent.com/assets/1784961/19384121/eea46eb8-9207-11e6-896f-6c48b002e3fb.png">
Steps to trigger:
```
~ $ mkdir test
~ $ mv test/ test2 #Throws exception referencing ~/test
# sometimes I need to `mv test2/ test3`, etc to reproduce.
~ $ mkdir test3 #Throws exception referencing ~/test as well
```

**Comment by rauchg** [comment] 2016-10-15 21:06
I thought we'd bumped `gaze` to fix this issue. We have to make sure it's at the latest.

**Comment by jcoetzee** [comment] 2016-10-17 09:09
I can confirm that this is still present on 0.8.2 using the method I described above to reproduce.

**Comment by shama** [comment] 2016-10-17 17:46
Hmm dang, I'll try @jcoetzee's repro steps today and see what's up.

**Comment by rauchg** [comment] 2016-10-17 17:47
@shama thanks so much for following up 🎉 let me know when I should bump and release

**Closed** 2016-10-17 23:58 UTC
Labels: Hacktoberfest, Priority: OMG Maximum, Status: Help Wanted, Type: Bug

**Comment by limeandcoconut** [comment] 2016-12-01 21:11
Is there any progress on this? I'm my office is still getting a version of this error.

**Comment by H1rag4mi** [comment] 2016-12-02 00:40
I'm also getting it, especially when doing a make and many files are being created and deleted 😟

**Comment by rauchg** [comment] 2016-12-03 07:40
What version are you running? Latest?

– @rauchg <https://twitter.com/rauchg>

**Comment by graysonwright** [comment] 2016-12-03 21:04
I'm on Hyper `0.8.3.873`, and I just got a similar error when trying to customize my startup shell command.

I was able to get a minimal reproduction of the error by setting:

```javascript
 shell: 'bash -c /bin/bash'
```

in `~/.hyper.js`. That same command works when I run it in an existing shell.

The error dialog:

<img width="420" alt="blank_skitch_document" src="https://cloud.githubusercontent.com/assets/829576/20862170/aeb0697e-b958-11e6-829c-87fa903d32e5.png">

Stacktrace:
```
Uncaught Exception:
Error: spawn bash -c /bin/bash ENOENT
    at Object.exports._errnoException (util.js:1026:11)
    at Socket.<anonymous> (/Applications/Hyper.app/Contents/Resources/app/node_modules/child_pty/lib/child_pty.js:103:15)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

**Comment by lclalalalala** [comment] 2018-06-08 15:08
I get this error for a long time. But sometimes, when the network is in good condition. It works. Nothing was changed with hyper.

**Comment by thesublimeobject** [comment] 2020-01-05 02:04
was there ever an official fix for this? i've been getting this error off and on for months now, and i can't seem to find a working fix for it?  it seems to happen most often—at least as far as i can tell—when i have some dir or another open in hyper, and i create a new dir, delete a dir, etc. so it seems linked in some way to the watch process (obviously, i guess), and the ability to refresh the current contents of the dir. i specifically noticed this, and have been able to recreate it, when i—for example—navigate to a particular dir and then add a dir through the finder. 

realistically, this wouldn't be that big of a deal, except that sometimes it just seems to get caught in a loop in itself, and once i hit "OK" the error just comes up again, and again, and again, until i just force quit the application and restart it. 

i'm on the most recent version of hyper, and my plugins are as follows—

`"dependencies": {
    "hyper-blink": "latest",
    "hyper-material-vibrancy": "latest",
    "hyper-stylesheet": "latest",
    "hyperminimal": "latest",
    "hyperborder": "latest",
    "hyper-search": "latest"
  }`
