### ISSUE TITLE
[V2] Color degredations

### ISSUE THREAD

**Issue by mike-engel** [zeit/hyper#2294] opened 2017-09-27 03:27 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.0
- **Hyper.app version**: 2.0.4 & 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mike-engel/0fcc34f787fa7875e91faf36ea19d67a
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yep. Moving my hyper.js config to another location and restarting also has bad color representations.

## Issue

While moving to 2.0, I've noticed that colors are not behaving properly anymore. In programs like Vim the colors between 2.x and 1.x are vastly different. While debugging, I also noticed that the color representations between the two versions seem to be much different.

Referring to [this gist](https://gist.github.com/XVilka/8346728) and [this script](https://github.com/robertknight/konsole/blob/master/tests/color-spaces.pl), you can see from my screenshots that there are some differences.

This may be an issue with xterm.js, so if it is, let me know and I'll move over there. Here's my [vim config as well](https://github.com/mike-engel/vimfiles/blob/master/vimrc). It's important to note that that exact vim config looks ok on 1.x, but not ok on 2.x.

Please let me know if there's any info you need. If you have some general ideas on where to start, I can work on a PR. Thanks!

**EDIT**: It seems like xterm.js [doesn't support truecolor](https://github.com/sourcelair/xterm.js/issues/484), which may be part of the problem with the color script, but doesn't explain the vim differences.

#### Vim
<details>
<img width="1440" alt="screen shot 2017-09-26 at 20 29 39" src="https://user-images.githubusercontent.com/464447/30894435-ff0942be-a300-11e7-826d-60e6ccb8f73a.png">
</details>

#### Color script
<details>

##### 2.x
![screen shot 2017-09-26 at 21 12 07](https://user-images.githubusercontent.com/464447/30894443-07318848-a301-11e7-9369-b2241be803a0.png)

##### 1.x
![screen shot 2017-09-26 at 21 12 08](https://user-images.githubusercontent.com/464447/30894446-0af08d1c-a301-11e7-9b92-3acbf265463f.png)
</details>

**Comment by MAPESO** [comment] 2017-09-27 03:57
@mike-engel Had not noticed that error, it could be due to **xterm.js** 🤔

I'll take a look at this problem.

**Comment by welnanick** [comment] 2017-09-27 18:12
I have noticed this too.

I switched to a [true-color vim theme](https://github.com/lifepillar/vim-solarized8) in 1.x due to #155 , this does not work in 2.x
I tried switching back to [my old theme](https://github.com/altercation/vim-colors-solarized) and it also is not rendering properly in 2.x

I am using [this hyper-theme](https://github.com/ghosh/hyper-solarized-dark) to get the solarized color palette

**Comment by MAPESO** [comment] 2017-09-27 21:06
@welnanick  We are working to solve the problem of colors.

**Comment by darkdreamingdan** [comment] 2017-09-27 23:38
My colours configuraion barely has any impact in Windows Bash.  I can only seem to get the window background colour working - tried the solarized theme but it also doesn't seem to work.

It seems to always force the default bash colours.

**Comment by fsegouin** [comment] 2017-10-18 16:37
I'm having the same issue with fish, some colors just don't work.

**Comment by mike-engel** [comment] 2017-10-18 18:01
fwiw I'm using fish as well. Could be an issue with how fish represents colors

**Comment by welnanick** [comment] 2017-10-18 18:06
I'm not using fish, and I am also having these issues, so unfortunately I don't think its related to fish :/

**Comment by Stanzilla** [comment] 2018-01-23 14:56
https://github.com/xtermjs/xterm.js/issues/484

**Comment by chabou** [comment] 2018-02-03 10:05
To be clear, this issue is related to 256 colors not true color.
Color Script, that tests 256 colors must render same thing in 2.x than in 1.x

**Comment by chabou** [comment] 2018-02-03 10:14
ok 3-byte color mode in script is 24-bits Truecolor. This is not supposed to work yet. So everything is ok with color script on Mac (in last canary with xterm3 too).

@mike-engel Can you try to reproduce your vim issue with our last canary?

**Comment by mike-engel** [comment] 2018-02-03 23:28
@chabou It looks like the latest canary is much better, but for some reason my vim config is still using the incorrect colors. It could be my vim config, but it is curious how different it looks with the same config. The color test, however, looks much better :smile:

### Screenshots
**Left**: Hyper 1.4.8
**Right**: 2.0.0-canary.11

#### Vim
<details>
<img width="1153" alt="screen shot 2018-02-03 at 16 21 21" src="https://user-images.githubusercontent.com/464447/35772551-ef0b17f2-08fe-11e8-81d4-0dfdbd2cb687.png">
</details>

#### Color test
<details>
<img width="1150" alt="screen shot 2018-02-03 at 16 23 49" src="https://user-images.githubusercontent.com/464447/35772562-2fcb127e-08ff-11e8-9442-0806df5db32a.png">
</details>

**Comment by chabou** [comment] 2018-02-12 20:10
@mike-engel can you confirm me that running vim with your config in Terminal or iTerm looks like hyper v1.4.8?

**Comment by mike-engel** [comment] 2018-02-13 03:26
@chabou running iterm2 stock (minus base16 ocean dark from chris simpson) with my vim theme produces what I'd expect, which matches hyper 1.4.8. Let me know if you'd like me to try anything else!

### iTerm2 v3.1.5
<details>
<img width="682" alt="screen shot 2018-02-12 at 20 24 53" src="https://user-images.githubusercontent.com/464447/36132199-0839a028-1033-11e8-976b-e5859ad5a113.png">
</details>

**Comment by chabou** [comment] 2018-02-13 14:33
Thank you for your screenshot.
I installed your config and reproduced your issue.

I tried to dig deeper into this issue and this is what I found:
Using `set termguicolors` needs to have a 24-bits (truecolor) ISO-8613-3 compatible terminal. Xtermjs isn't yet compatible. In this case, terminal render a `#303030` appromixation instead of `#2B303B` blue grey.

When `termguicolors` isn't set, it fallback on 16/256 color.

And I found that your hyper theme `hyper-base16-ocean-dark` hasn't the right colors.
If you use theses colors, you'll have same colors thant iTerm2:

**Comment by chabou** [comment] 2018-02-13 14:37
If you want to keep theme colors, I think you could use something like https://github.com/chriskempson/base16-shell with `let base16colorspace=256` vim theme parameter.

**Comment by mike-engel** [comment] 2018-02-13 17:27
Thanks @chabou. I'll take a look at my configs tonight and try to update them.

**Comment by kinglouie** [comment] 2018-02-24 17:07
On my setup this issue is not limited to vim, the colors beyond 16 are not right.
I have a base16 solarized-dark colorscheme and tested the colors with `colortest` from [chriskempson/base16-shell](https://github.com/chriskempson/base16-shell)

<details/>
<summary>hyper.js</summary>

```
module.exports = {
  config: {

    updateChannel: 'canary',

    fontSize: 15,
    fontFamily: '"MesloLGSDZ Nerd Font", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    base16: {
      scheme: 'solarized'
    },

  },

  plugins: [
    'hypersixteen'
  ],

};
```

</details>

#### 2.0.0 canary-14

<img width="769" alt="bildschirmfoto 2018-02-23 um 16 49 53" src="https://user-images.githubusercontent.com/8280409/36632936-53d01e8c-198d-11e8-8bd7-9caa4b990aea.png">

### 1.4.8

<img width="800" alt="bildschirmfoto 2018-02-23 um 16 47 31" src="https://user-images.githubusercontent.com/8280409/36632937-53ef504a-198d-11e8-9b1f-da725e860999.png">

**Comment by chabou** [comment] 2018-02-24 21:07
The main difference is for Bright_White and colors > 15.

I think that Bright_White is ok: https://github.com/winneon/hypersixteen/blob/master/src/HyperSixteen.js#L31
Maybe v1.4.8 has some side effect with this color. But now, it seems to be what solarized theme expects.

There is indeed some "regressions" with colors > 15, but this is exactly how it is looks like with iTerm.

So for me, there is no other regression than dropped truecolor support.

Vanilla 2.0.0-canary.14
![capture d ecran 2018-02-24 a 15 00 51](https://user-images.githubusercontent.com/4137761/36635023-be012f86-1973-11e8-8811-e868c1da5ced.png)

iTerm
![capture d ecran 2018-02-24 a 15 01 47](https://user-images.githubusercontent.com/4137761/36635026-c4b5fc1c-1973-11e8-8ffc-9da645b9f57e.png)

**Comment by kinglouie** [comment] 2018-02-24 21:46
strange, for me in iTerm colors > 15 are working with `base16-shell` and base16-solarized-dark.sh
Here are the dotfiles I'm using: [kinglouie/dotfiles](https://github.com/kinglouie/dotfiles)

<img width="666" alt="bildschirmfoto 2018-02-24 um 22 37 41" src="https://user-images.githubusercontent.com/8280409/36635336-570ac414-19b3-11e8-9804-26795a6cdb68.png">

**Comment by mpcsh** [comment] 2018-02-26 17:51
+1. My vim is horrendously ugly in 2.0.0-canary.14, but looked fine in 1.4.8. This is my last barrier to switching from iTerm2.

**Comment by nkzawa** [comment] 2018-03-04 00:31
👍  I used to have colorscheme on `.hyper.js`, but it doesn't work on v2 anymore.

Definition: https://gist.github.com/nkzawa/970f75de0f9f8b05524d99452dfabd54

**Comment by chabou** [comment] 2018-03-04 09:03
@nkzawa your issue is not the same. I opened an issue for it: https://github.com/zeit/hyper/issues/2728

**Comment by sethetter** [comment] 2018-04-10 14:52
For anyone using the hyper-solarized-dark plugin, I was having an issue with the background color but fixed it with this PR -> https://github.com/ghosh/hyper-solarized-dark/pull/20

Not related to the main issue here, but it at least made vim look less bad w/ solarized dark :)

**Comment by spoike** [comment] 2018-04-18 07:36
Verifying that `colors` > 15 are still the wrong colors in `Hyper 2.0.0-canary.18`.

**Comment by tehp** [comment] 2018-04-26 00:48
This issue is still occurring. I have very similar issues as @colinrcummings 
![image](https://user-images.githubusercontent.com/3845735/39279869-7fdb26f0-48b0-11e8-9503-61d96e958c44.png)
Left is the same theme running on terminal, right is the theme running on Hyper. You can clearly see that the whole window seems to be dimmed.

**Comment by cseelus** [comment] 2018-05-04 13:15
Still the same problem, even with 2.1.0-canary.1

<details>
![untitled](https://user-images.githubusercontent.com/3188392/39629899-ebd6cc84-4fad-11e8-8b0a-d1eb39d787cb.png)

</details>
1.4.8

---

<details>
![screen shot 2018-05-04 at 15 01 46](https://user-images.githubusercontent.com/3188392/39629902-f164523e-4fad-11e8-83d1-f745fdd39012.png)

</details>
2.1.0

**Comment by tehp** [comment] 2018-05-04 21:01
Using `hyper-snazzy#1.2.2` fixed the issue for me @cpetersson, but thank you for the tip. Interested to know why this broke.

**Comment by acornq** [comment] 2018-07-07 22:42
I'm having this issue with the latest version of Hyper too. No plugins. Vim colour scheme showing wrong colours

**Comment by wiktorowczarz** [comment] 2018-07-31 09:34
Any progress on the issue? Does anyone has any **temporary solutions** to the problem?

My current output:
<img width="1258" alt="screen shot 2018-07-31 at 11 29 49" src="https://user-images.githubusercontent.com/8012343/43451511-6317bd02-94b5-11e8-8f5b-fc44b54ff500.png">


Expected output:
![test](https://user-images.githubusercontent.com/8012343/43451603-9c1fb208-94b5-11e8-9722-2c6e7e7f0b26.png)

**Comment by nonsleepr** [comment] 2018-08-13 19:04
I just tried Hyper 2.0.0 (stable) on Xubuntu and Mac with `hyper-solarized-dark` and `vim-colors-solarized`. It works fine on Xubuntu but is messed up on Mac.

**Comment by victorronnow** [comment] 2018-11-07 16:02
Experiencing the same issue here. Any updates?

Hyper 2.0.0 (stable) | Hyper 1.4.8 (stable)
--- | ---
![capture d ecran 2018-11-07 a 17 00 13](https://user-images.githubusercontent.com/17050767/48143265-b560b180-e2ae-11e8-8774-02605f31392e.png) | ![capture d ecran 2018-11-07 a 17 00 18](https://user-images.githubusercontent.com/17050767/48143266-b5f94800-e2ae-11e8-9cb5-5d0071f2b654.png)

**Comment by chris542** [comment] 2018-11-14 11:02
I'm experiencing the same issue on Windows. All of my settings are identical to my mac environment, which uses iterm2, and I wanted to replicate the environment on Windows. Colors on both zsh and vim are not working correctly.

![image](https://user-images.githubusercontent.com/17423698/48478601-a4dda780-e869-11e8-8bb8-c7e0137f5db5.png)

**Comment by S-vdv** [comment] 2018-11-30 16:19
Any progress on this issue? I have exactly the same problem. However, if i comment out set termguicolors the colors become more alive. The background stays ugly brown though
![screenshot from 2018-11-30 17-16-49](https://user-images.githubusercontent.com/44851348/49301078-13ef0900-f4c4-11e8-8322-4656aaa69057.png)

**Comment by kinglouie** [comment] 2019-05-03 16:46
Fixed on xterm.js 🎉 https://github.com/xtermjs/xterm.js/pull/1895

**Comment by DonnieWest** [comment] 2019-05-03 17:55
Doesn't look like it's in a stable release yet though - https://github.com/xtermjs/xterm.js/releases/tag/3.13.0-beta1

**Comment by JoshCheek** [comment] 2019-05-06 13:00
Just downloaded hyperterm 3 to give it a shot. I tweet a lot of visual programs, some of them don't look good on hyperterm b/c of this issue, eg:

https://twitter.com/josh_cheek/status/1116321447234940928

```
ruby -eh,w=$LINES,$COLUMNS'
B=(0..20).map{[0,rand*h,rand*5,rand]}
loop{B. map!{|x,y,v,a|[(x+v),y+a=y<0?-a:a-0.1,v,a]}
$><<"\e[H"<<h.times. map{|v|w.times. map{|u|d=B. map{|x,y|Math.sqrt (w/2-(x+w/2-u)%w)**2/4+(v-y)**2}.min*9
"\e[48;2;#{d<0?0:d>255?255:d. to_i};0;0m "}*""}*"\n"}'
```

On iTerm2, it looks like this (the weird line is b/c ss is partway through a screen update): 

![image](https://user-images.githubusercontent.com/77495/57225698-be6adb00-6fd2-11e9-8c09-9778a75ddb1b.png)

On Hyperterm3 it looks like this:

![image](https://user-images.githubusercontent.com/77495/57225815-0f7acf00-6fd3-11e9-991a-147db83e02ca.png)


On the upside, it is super smooth.

**Comment by MrRio** [comment] 2019-05-06 13:13
@JoshCheek Will have a look into this.

**Comment by MrRio** [comment] 2019-05-06 14:00
@JoshCheek Looks like it's fixed in latest xterm.js when updated inside Hyper, so we just need to make sure it makes its way into the WebGL renderer.

<img width="1548" alt="Screenshot 2019-05-06 at 14 59 27" src="https://user-images.githubusercontent.com/47539/57230136-9188e900-700f-11e9-9e70-1a3e5a9d136e.png">

**Comment by DonnieWest** [comment] 2019-05-09 16:45
https://github.com/xtermjs/xterm.js/commit/e40f9249134ca3f5038fb95fd4eb5f0d036b1228

^ Looks like xtermjs just reached 3.13. Stable release that should hopefully make it into hyper's fork :)

**Comment by danteissaias** [comment] 2019-08-30 10:55
Is there any indication as to when this issue will be fixed?

**Comment by SkyaTura** [comment] 2019-10-10 13:52
Is this issue planed to be solved soon?

**Comment by Stanzilla** [comment] 2019-10-10 19:26
Try with a CI build from canary, otherwise please open a new issue

**Closed by Stanzilla** 2019-10-10 19:26 UTC
Labels: ⚡ Type: Regression
