### ISSUE TITLE
Heavy processor usage macosx

### ISSUE THREAD

**Issue by zanedev** [zeit/hyper#574] opened 2016-08-05 21:55 UTC
Anybody notice that hyperterm is getting sluggish after leaving it open for a while?  Seems to be happening regularly for me even when not running heavy processes or only one or two tabs open.  It also seems to be triggered by closing the lid and resuming it later.  This is on a macbook pro retina 15in El Capitan.  I've seen hyperterm helper go to 30-40% cpu which seems a bit excessive for a terminal app.

Hyperterm Version 0.7.1 (0.7.1.36)

I'm running wow mode and cwd plugins only.

![image](https://cloud.githubusercontent.com/assets/817344/17451476/ff88bfea-5b1b-11e6-87df-3dc3b4a711b0.png)

**Comment by albinekb** [comment] 2016-08-05 22:41
This is interesting, certainly needs more investigation. Possible it's related to #339?

**Comment by deepsweet** [comment] 2016-08-06 08:58
also #474 can be somehow related to this issue.

**Comment by zanedev** [comment] 2016-08-08 22:54
Just an update on this, it's still happening.  Here's some more info:

Definitely no issues with performance when in the same laptop session, close lid go to sleep and it starts almost reliably every time.
I'm running 2 long running tasks in hyperterm often npm processes and ssh connections.

**Comment by catskull** [comment] 2016-08-11 16:25
To chime in, I have essentially the exact same use scenario as @zanedev and I have not experienced any of these issues.

**Comment by zanedev** [comment] 2016-08-11 17:47
Thanks for the info @catskull interesting..  actually I haven't seen it since I posted that follow up :)  I don't think there was a hyperterm update since I posted that.  I'll post back if it crops up again. 

Note the way I can tell it's getting sluggish is my fan gets loud but also the wow mode cursor splash effect seems delayed/and the cursor typing/blinking is slowed down.

**Comment by zanedev** [comment] 2016-08-12 00:09
well so much for my last comment was just hit pretty hard check it out at 83.3% of my cpu had to close out everything this time almost rebooted..  The only thing I can think of is I have a lot of google chrome tabs open or the latest specific terminal process I was running was a simple webpack watch build command..

![image](https://cloud.githubusercontent.com/assets/817344/17609057/2eef40fa-5fe6-11e6-86a4-be75dc7d7ac7.png)

**Comment by zanedev** [comment] 2016-08-12 00:16
Almost seems like v8 is being overwhelmed somehow.  I am using the crap out of it heck it's become the most used library on my system most likely!

**Comment by aray12** [comment] 2016-08-17 18:50
I am having the same issue. I usually have a long running node process (webpack dev server). But what I noticed really sets it off is ngrok so seems like it could be related to ssh tunneling considering @zanedev mentioned ssh above

**Comment by zanedev** [comment] 2016-08-22 20:18
Well I'm going to have to stop using hyperterm for a bit :( its finally become too much of a pain to restart every time it slows up my machine on a regular basis.  Bummer I really liked it, I'll come back and try it a again after a few more versions.

**Comment by ryangurn** [comment] 2016-08-27 22:57
I am having the same issue with hyperterm. Please keep this thread up to date so that I know when I can start using it again.

**Comment by pokono** [comment] 2016-09-10 22:05
+1

**Comment by linkurzweg** [comment] 2016-10-24 09:45
Same here, this happens immediately after starting. CPU load is just insane, so it's unusable for me for now :/

![hyperterm](https://cloud.githubusercontent.com/assets/4902517/19640869/00e81884-99df-11e6-879a-0534e6bdec5d.png)

**Comment by uipoet** [comment] 2016-10-31 15:57
Try disabling `hyperpower` in plugins. Made a huge improvement for me on two different machines. It's a shame, I got used to the visual effect and now only reenable it when having a hacking session with my five-year-old.

**Comment by newgene** [comment] 2016-12-09 00:34
Confirmed that the same issue happens on Ubuntu 16.10 as well. Disable `hyperpower` solves the issue. CPU load dropped from ~70% down to ~10%, much better.

**Comment by bryantee** [comment] 2016-12-16 01:37
@newgene Same thing happening with me. Disabling `hyperpower` also solved. Bummer....

**Comment by ChrisCinelli** [comment] 2017-01-03 00:39
Running `top` I see 50% CPU on `Hyper Helper`

**Comment by chrisnojima** [comment] 2017-01-03 19:08
I have this as well w/o any plugins

**Comment by bitbrain** [comment] 2017-01-09 13:30
I have this as well. Same symptoms.

**Comment by bendews** [comment] 2017-01-21 03:44
I also have this issue with no plugins

**Comment by YannHulot** [comment] 2017-01-29 05:32
Same issue here, I open Hyper and 30 seconds later my fans turn on and won't stop until I close the app. Not even running a single process. Such a shame as I really like the look and feel of this terminal but unfortunately, it is unusable at the moment. Please keep me posted if there is a fix for it. Thanks Ps: disabled all the plugins as well.

**Comment by matbruc** [comment] 2017-04-10 20:15
I have this as well. It's a shame because it's a great app. Back to iTerm...

**Comment by dankonino** [comment] 2017-04-28 14:20
@matbruc just really try `hpm uninstall hyperpower`. I had troubles with that after while 100% 
just came here 've seen tried that and my hyper is 0.1% xD ! just had some time for fixing that. yesterday I fixed my problem with node running the same crazy power sometimes 130% even though quad core Mac ..

**Comment by MonsieurMan** [comment] 2017-06-28 07:59
This is the same for me here, hyperpower is loading my (it's a beast) CPU to 30%...
There is also an issue for that on hyperpower [#19](https://github.com/zeit/hyperpower/issues/19).
This has been happening for me only using Fedora, it's completely fine on Windows.

**Comment by beather** [comment] 2017-12-01 10:39
Got the same issue 👎  hyperpower runs with 80% CPU usage.

**Comment by albinekb** [comment] 2017-12-01 11:33
@chabou @rauchg should we put a warning about `hyperpower` and stop recommending it in the default config? If you search the issues for `hyperpower`, you'll get a dozen hits.

**Comment by timothyis** [comment] 2018-04-22 01:43
Haven't had activity in quite some time, other than due to hyperpower, so I'm closing this. Thanks for the issue. Please let us know if there's continued problem related to this.

**Closed by timothyis** 2018-04-22 01:43 UTC
Labels: 📊 Type: Performance
