### ISSUE TITLE
Multiple shell configurations

### ISSUE THREAD

**Issue by ek-nath** [zeit/hyper#1718] opened 2017-03-29 16:42 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 x64
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ach3/bb33b2a2874ad0fc845711e08bb25b25
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue
I'd like to run both bash.exe and cmd.exe through hyper. For this, I would like support for a cli like `--config=<path/to/.hyper.js>`. I couldn't find an existing way to do this.

**Comment by MartyGentillon** [comment] 2017-04-15 08:11
https://github.com/zeit/hyper/pull/1347

**Comment by MartyGentillon** [comment] 2017-04-15 08:44
This is a duplicate of https://github.com/zeit/hyper/issues/1147

**Comment by ppot** [comment] 2017-04-15 22:46
Closing in favor of #1147

**Closed by ppot** 2017-04-15 22:46 UTC
Labels: Is Duplicate
