### ISSUE TITLE
Broken Install

### ISSUE THREAD

**Issue by grmnn** [zeit/hyper#3049] opened 2018-05-23 08:22 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 10
- **Hyper.app version**: 2.0.0

![hyper-error](https://user-images.githubusercontent.com/30831286/40412157-d30a7150-5e72-11e8-8e3e-92f000b9cef7.png)

**Comment by rfgamaral** [comment] 2018-05-23 16:44
Duplicate of #3048?

**Comment by MAPESO** [comment] 2018-05-23 17:07
@grmnn Hi, I could try again to install it, this error should not happen :(

**Comment by grmnn** [comment] 2018-05-24 12:49
@rfgamaral I know of #3048  But there was 0 information about the Error. 

I tried it again but it doesn't work. I also tried to delete old files before installing it again.

**Comment by rfgamaral** [comment] 2018-05-24 14:11
@grmnn I'm glad you solved it. Perhaps you could know close the issue?

**Closed** 2018-05-24 14:16 UTC
