### ISSUE TITLE
Error on trying to edit preferences

### ISSUE THREAD

**Issue by JorgeSilvaBorda** [zeit/hyper#1812] opened 2017-05-11 12:39 UTC
When I go to Menú --> Edit --> Preferences, I'm getting the following message:

Error: 'module' is not defined.

Please see the attached image for more info.
Thanks.
![image](https://cloud.githubusercontent.com/assets/10128895/25949382/bcf66356-362d-11e7-8d5d-4ecb76882105.png)

-

Hyper 1.3.2
Electron 1.4.16
win32 x64 6.1.7601

**Comment by wilfreddenton** [comment] 2017-05-11 15:59
I'm having a similar issue when I try to open up preferences.

<img width="540" alt="screen shot 2017-05-11 at 11 58 15 am" src="https://cloud.githubusercontent.com/assets/1426935/25959291/3154df26-3641-11e7-9761-399a28414317.png">

Hyper 1.3.2
macOS 10.12.1

**Comment by chabou** [comment] 2017-05-11 16:23
For you both, it seems to be a problem with your native editor: Microsoft JScript and Emacs. Please be sure to have a proper software assigned to open `.js` file.

**Comment by chabou** [comment] 2017-05-11 16:24
OMG... Maybe Windows try to execute js file and not to open it @JorgeSilvaBorda .
I'll try to investigate further

**Comment by drdaeman** [comment] 2017-05-13 15:34
Yes, I believe this is what actually happens.

If `.js` files are re-associated with an editor (as the default "open" action, not "edit") then that editor is started.

**Comment by toddself** [comment] 2017-05-13 15:36
@chabou jscript isn't a native editor -- it's what windows tries to run `.js` files with by default.  This is happening when trying to open preferences up.

My editor of choice is vim, which runs in the terminal, so I have no windows association for editing .js files.

Ideally this should try to open it with notepad or some other built in editor?

**Comment by ppot** [comment] 2017-05-13 15:46
@chabou I think we should revert your PR?

**Comment by toddself** [comment] 2017-05-13 15:54
@ppot or make it smarter somehow?

**Comment by ppot** [comment] 2017-05-13 16:15
If we change to `.conf` it won't execute it. It should be `.conf` @albinekb

**Comment by pramodsvidyarthi** [comment] 2017-05-15 12:21
I get a similar issue when i open the preferences.

![hyper-error](https://cloud.githubusercontent.com/assets/8534915/26057359/f7fbf0e4-3996-11e7-8a76-5f2925e17d7e.PNG)

**Comment by Szomy** [comment] 2017-05-15 18:55
Duplicate of #1810

**Comment by riccardobevilacqua** [comment] 2017-05-17 16:01
Same issue with:
* Hyper v1.3.3
* Win 7 Enterprise 64bit

**Comment by albinekb** [comment] 2017-05-20 04:02
Let's add an option to .hyper.js to set preferred editor, and default it to notepad.exe on windows? 😄

**Comment by etudor** [comment] 2017-05-20 09:36
Same issue on: 

- Windows 10 Home 
- Hyper 1.3.3

**Comment by Stanzilla** [comment] 2017-05-23 15:41
Imo there are two solutions to this:

a) The proper way:
Include a config view similar to VSCode where it's basically a webview of the config file that lets you edit it.
This is probably tons of work but could pay off in the end since you can have the possible config values of settings as a tooltip hint and people have to go to the webpage less.
![code_2017-05-23_17-39-27](https://cloud.githubusercontent.com/assets/75278/26362633/db5ae532-3fde-11e7-9826-0424ba4251fd.png)

b) The hack:

Fall back to notepad/whatever macOS has when the default for .js files is a known bad setting. Is it even possible to detect the default file handler via JS/Electron?

**Comment by ppot** [comment] 2017-05-23 17:34
@Stanzilla I want to do an atom-like preferences setting once I did a rebuild. But It need to be step by step.

**Closed** 2017-05-26 16:23 UTC
Labels: Platform: Windows, Priority: High, Status: Help Wanted

**Comment by kallaspriit** [comment] 2017-08-28 06:55
Workaround:
1. find a random .js file on your computer.
2. right click it, choose "Open with" > "Choose another app".
3. choose an editor from the list that works for you (VSCode etc) and check "Always use this app to open .js files".

This will re-associate .js files with an editor instead of trying to execute it. Settings should open in this editor the next time you try it (CTRL+,).

**Comment by MikaelFields** [comment] 2017-09-12 14:42
I fixed this issue by selecting by default what code editor use to open js files, I just selected visual studio code and it is done! (Windows 10)

**Comment by pythlang** [comment] 2019-02-10 16:02
Just experienced this problem randomly on Mac after opening it fine in Visual Studio Code thousands of times. @kallaspriit 's solution is a good one, but it didn't work for me.

1. Find a file with a .js extension.
2. Right-click.
3. Get Info.
4.  Open with.. (select program)
5. Change all (will change all like-program extensions to open with this program).

Opens the preferences just fine.

**Comment by hirushacooray** [comment] 2019-05-26 04:47
Setting a default editor for .js files worked for me. 

Instructions for Windows 10.

1. Search for "Choose default apps by file type"
2. Scroll down and find .js file type.
3. Set default your text editor.
