### ISSUE TITLE
.hyper.js gets reset and config is lost

### ISSUE THREAD

**Issue by cytryn** [zeit/hyper#2123] opened 2017-08-29 05:22 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Mac OS Sierra**: 
- **Hyper.app 1.3.3**: 

## Issue
I am trying to setup my dev 
stuff here with oh-my-zsh so I can use hyper+zsh+vscode.

I have .hyper.js open on VSCode so I can configure my visuals. The thing is that something happens and then when I reopen Hyper to check on plugin changes, the .hyper.js file rolls back to what is original...
So I lose shell config, plugins, etc...

I get a msg that is cannot find npm
![image](https://user-images.githubusercontent.com/735750/29805530-af1bd78c-8c60-11e7-814b-4a248fb42a11.png)

But npm is working just fine on `which npm` on mac regular terminal

Any clue why is that happening?

**Comment by timneutkens** [comment] 2017-08-29 05:51
Duplicate of https://github.com/zeit/hyper/issues/1249

**Closed by timneutkens** 2017-08-29 05:51 UTC
