### ISSUE TITLE
ZSH powerline prompt not rendering properly on hyper 3.0.0

### ISSUE THREAD

**Issue by ridhwaans** [zeit/hyper#3617] opened 2019-05-07 13:41 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows10 with WSL ubuntu 16
- **Hyper.app version**: 3.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ridhwaans/3608ccd6b2afdf8d25bbfebbd0fe178c
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

![image](https://user-images.githubusercontent.com/1103336/57303507-7b306b00-70ab-11e9-8f82-1e92c165d58c.png)

Using zsh by default above, the powerline prompt is incorrectly showing a black line and shape at the front and back on hyper3. This change occurred after the update.

**Comment by cahalane** [comment] 2019-05-07 16:50
The problem does not appear to be Windows-specific, as I have encountered it on Ubuntu:
![image](https://user-images.githubusercontent.com/6553114/57317648-8063d900-70f0-11e9-8335-b96c47cc2ea1.png)

I have encountered it using both the Meslo LG M DZ for Powerline and Noto Mono for Powerline fonts.

**Comment by NathanielInman** [comment] 2019-05-07 18:10
The problem also doesn't appear to be font-specific. I have the issue on the aforementioned fonts as well as PragmataPro on macOS.
![image](https://user-images.githubusercontent.com/460990/57322520-5d71fe80-70c9-11e9-8bf3-b7b957be2ff8.png)
![image](https://user-images.githubusercontent.com/460990/57322531-6236b280-70c9-11e9-95e8-08e4ace06368.png)

**Comment by cahalane** [comment] 2019-05-07 18:30
So for some display-related reason (maybe CSS settings for legibility, maybe the actual Electron version), the start of the actual glyph no longer aligns with the start of the background, which is a problem for any theme/font that use the  arrow, and on any OS.

**Comment by LeTrovoes** [comment] 2019-05-08 01:00
Same issue here, on Ubuntu 18.04. This is a duplicate of #3575

**Comment by voronoipotato** [comment] 2019-05-08 21:16
This may be related to broken ligatures in 3.0.0

**Comment by technofantods** [comment] 2019-05-08 21:39
same issue - kubuntu 18.04

![image](https://user-images.githubusercontent.com/37778164/57410236-3d6d3880-71b8-11e9-8574-87eb77a0ce9b.png)

**Comment by cahalane** [comment] 2019-05-08 22:29
Noting that #3575 lists a workaround:
>This issue seems related to the WebGL rendering, as turning webGLRenderer to false in config seems to revert to hyper v2 behavior
>Setting webGLRenderer: false worked for me on latest Windows 10. It also restored font ligatures (with the appropriate plugin), which were also broken by the v3 release.

The behaviour isn't perfect (there's a 1px offset in the opposite direction still) but it should help resolve some of that annoyance

**Comment by technofantods** [comment] 2019-05-10 02:22
I dropped  webGLRenderer: false, right under update channel and it worked for me

**Comment by Muzical84** [comment] 2019-05-11 16:08
I made the change, at the top of my config, in the latest macOS, and I still have the problem.  Everything looks like it should in vanilla Terminal.

**Comment by cybercatgurrl** [comment] 2019-05-12 11:53
> I dropped webGLRenderer: false, right under update channel and it worked for me

Thank you! This was so irritating.

**Comment by Basster** [comment] 2019-09-29 13:50
Can confirm this issue on Ubuntu 18.04 with zsh.

> webGLRenderer: false

fixes nothing, here...

**Closed** 2019-09-30 20:15 UTC
Labels: ⚡ Type: Regression, 👆 Is Upstream

**Comment by Svetomechc** [comment] 2019-11-06 13:18
@Stanzilla why was this closed? `webGLRenderer: false` is not a solution - it's a workaround. With `webGLRenderer: true` the app is much faster (you can see it when scrolling).

**Comment by Stanzilla** [comment] 2019-11-06 17:02
It's our solution for now. until webrenderer gets more usable.

**Comment by Muzical84** [comment] 2019-11-06 17:11
It's not a workaround or a solution if it doesn't work.  As I said above, I'm still getting boxes in macOS Mojave, and yes I have reinstalled, reloaded my config, etc.  It's literally something I re-try again every few weeks because other terminal GUIs are so much harder on my eyes, but I'm stuck in iTerm2 for now.

**Comment by Stanzilla** [comment] 2019-11-06 18:17
@Muzical84 well you could test one of your CI builds https://app.circleci.com/jobs/github/zeit/hyper/2923/artifacts or switch to https://github.com/Eugeny/terminus instead. It's very well maintained.
