### ISSUE TITLE
cannot install any plugin

### ISSUE THREAD

**Issue by spacekestrel** [zeit/hyper#3620] opened 2019-05-07 14:53 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
Every time i want to install plugin, i have this messiage:

C:\Users\space\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:19153
      getProperties = memoize(() => getParsedFile().program.body[0].expression.right.properties),
                                                                                    ^

TypeError: Cannot read property 'properties' of undefined
    at memoize (C:\Users\space\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:19153:85)
    at d (C:\Users\space\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:19138:22)
    at memoize (C:\Users\space\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:19154:34)
    at d (C:\Users\space\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:19138:22)
    at Object.install (C:\Users\space\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:19184:37)
    at Args.args.command (C:\Users\space\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:9934:45)
    at Args.runCommand (C:\Users\space\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:11318:37)
    at Args.module.exports [as parse] (C:\Users\space\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:15089:10)
    at main (C:\Users\space\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:9991:18)
    at Object.module.exports.name (C:\Users\space\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:10038:1)

**Comment by rromanv** [comment] 2019-05-07 15:10
I have the same issue

**Comment by waigx** [comment] 2019-05-07 15:54
same issue here

**Comment by seergiioo6** [comment] 2019-05-07 16:07
same issue here

**Comment by MrBMT** [comment] 2019-05-08 00:43
I also have this issue. I've tried deleting the default `.hyper.js` from `%AppData%\Hyper` too and letting it regenerate and even deleting everything from the folder, it makes no difference.

**Comment by jwhipp** [comment] 2019-05-08 16:27
Running into the same issue, also Windows 10.  Tried with a default config after locating the new location of the configuration, same result.

**Comment by pcnate** [comment] 2019-05-08 16:38
what is the output of `hyper version`

have you tried this?
https://github.com/zeit/hyper/issues/3590#issuecomment-489672067

**Comment by jwhipp** [comment] 2019-05-08 16:47
Hyper version is 3.0.0.   About that comment, it states to have the plugins already installed, but I wiped all that out as part of trying a fresh start.

**Comment by Nightmarlin** [comment] 2019-05-08 17:25
![image](https://user-images.githubusercontent.com/29228454/57394796-54168e00-71be-11e9-8743-940e4a22ae0b.png)

Also unable to install plugins after trying the commented "solution"

Windows 10 Home 1809 - 17763.475

**Comment by voronoipotato** [comment] 2019-05-08 21:05
duplicate of  https://github.com/zeit/hyper/issues/3500

workaround here

**Comment by Nightmarlin** [comment] 2019-05-09 16:23
symlink solution worked:
 
> Hi,
> 
> @ZaLiTHkA Thanks!.
> 
> I have executed this, but to apply the changes in the $APPDATA/Hyper/.hyper.js file have created a symbolic link.
> 
> Example:
> 
> ```
> C:\Users\user>mklink "C:\Users\user\.hyper.js" "C:\Users\user\AppData\Roaming\Hyper\.hyper.js"
> vínculo simbólico creado para C:\Users\user\.hyper.js <<===>> C:\Users\user\AppData\Roaming\Hyper\.hyper.js
> 
> C:\Users\user>dir | findstr "hyper"
> 07/05/2019  22:39    <SYMLINK>      .hyper.js [C:\Users\user\AppData\Roaming\Hyper\.hyper.js]
> ```

[Comment here](https://github.com/zeit/hyper/issues/3500#issuecomment-490252223)

**Closed** 2019-07-30 13:40 UTC
