### ISSUE TITLE
Terminal text's style pops when moving mouse cursor

### ISSUE THREAD

**Issue by r4dian** [zeit/hyper#1598] opened 2017-03-03 12:34 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.211
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default settings / fresh install - I have changed the border colour to make it visible in screengrab.
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`.

## Issue

Style of text in WSL's bash prompt pops when the cursor moves into different UI elements (terminal pane, tabs, etc.)
![style pop on cursor entry](https://cloud.githubusercontent.com/assets/1264174/23551137/c33f126e-000c-11e7-9250-42601d2447fb.gif)

**Comment by r4dian** [comment] 2017-03-03 12:39
Also powershell's red text
![also powershell](https://cloud.githubusercontent.com/assets/1264174/23551421/65933de6-000e-11e7-8d1f-9cd2f7ba57e3.gif)

**Comment by CodeTheory** [comment] 2017-03-03 16:24
Duplicate of #1490. Please contribute to that issue instead 😄

**Closed by CodeTheory** 2017-03-03 16:24 UTC
