### ISSUE TITLE
Error at building hyperterm at windows 10 and no command line at run

### ISSUE THREAD

**Issue by CavariuX** [zeit/hyper#679] opened 2016-08-31 22:37 UTC
I updated NPM and NodeJs to their last version I cloned the project and use 'npm i' to install the dependencies. I wonder how can I build this version of HyperTerm in windows 10. I use 'npm run start' but when used theres no line where I can place a command. Also when used 'npm run pack' in windows 10 this error appears [npm-log.txt](https://github.com/zeit/hyperterm/files/448401/npm-log.txt).
Thanks.

**Comment by saitonakamura** [comment] 2016-10-15 13:40
In my case the cause of this was that `electron-builder` wants icon at least 256x256

```
Packaging for platform win32 x64 using electron 1.4.0 to dist\win-unpacked

Error: Windows icon size must be at least 256x256, please fix "C:\code\smth\hyper\build\icon.ico
"
    at C:\code\smth\hyper\node_modules\electron-builder\src\winPackager.ts:216:9
    at next (native)
    at C:\code\smth\hyper\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at tsAwaiter (C:\code\smth\hyper\node_modules\electron-builder\src\util\awaiter.ts:10:47)

    at Object.build (C:\code\smth\hyper\node_modules\electron-builder\out\builder.js:138:12)
    at Object.<anonymous> (C:\code\smth\hyper\node_modules\electron-builder\out\build-cli.js:23:
11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I upscaled `build/icon.ico` and `npm run dist` and `npm run pack` started working

**Comment by matheuss** [comment] 2016-10-31 01:12
Hey guys please check #946 – I'm closing this since both issues were solved 😄

**Closed by matheuss** 2016-10-31 01:12 UTC
Labels: Type: Compatibility
