### ISSUE TITLE
Emoji in PROMPT is causing character duplication after pressing TAB

### ISSUE THREAD

**Issue by jkulak** [zeit/hyper#3516] opened 2019-03-09 19:25 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14.3 (18D109)
- **Hyper.app version**: 2.1.2 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/jkulak/1633a8c0572aade642f050be97b1da76
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
I am using Hyper.js and oh-my-zsh. My PROMPT has an emoji (which causes the issue).

When I type a part of a command and press TAB to complete the command - and I get a list of suggestions for completion, the first letter of my command gets duplicated. Typing `ls` and pressing TAB gives:

```
🦀 ~ lls
LSCOLORS   ls         lsa        lsappinfo  lsbom      lskq       lsm        lsmp       lsof       lsvfs
```

When I type `dock` and the only option to autocomplete is `docker` it works just fine, and pressing TAB shows `🦀 ~ docker`. Pressing TAB again gives

```
🦀 ~ ddocker
docker                         docker-compose                 docker-credential-osxkeychain  docker-machine
```

Pressing enter runs `docker` command and not `ddocker` so it's only a visual issue.

The issue occurs only with  an emoji in the PROMPT. Issue doesn't occur in iTerm nor in Terminal.

**Comment by stripedpajamas** [comment] 2019-03-11 19:29
Similar experience for me, and I also only experience it when I have an emoji in the prompt. 

I am using Hyper and Bash. I don't see the issue on autocomplete (tab), but I do see it when I hit the UP arrow to go to previous commands. The first UP pulls in the previous command, the second UP has the previous command's first letter prefixing it (visual only; the command will run properly).

Example:

```
🍕 ~ vim .
🍕 ~ du -sh Downloads/
(hit UP arrow)
🍕 ~ du -sh Downloads/
(hit UP again)
🍕 ~ dvim .
```

**Comment by jkulak** [comment] 2019-05-08 21:30
Still the same in **Hyper.app version: 3.0.0** (stable)

**Comment by johnarban** [comment] 2019-05-12 05:24
I am getting the same issue in 3.0.2 (stable) on macOS mojave (version 10.14.4 (18E226)) with a simple prompt running the built-in bash (which is of course old, v3.2.57)
```bash
export $PS1="🔭> "
```

a hexdump (`echo $PS1 | hexdump`) gives
```
0000000 f0 9f 94 ad 3e 0a                              
0000006
```

This doesn't cause an problem for iTerm, so it's not a bash specific thing.

**Comment by zhao-li** [comment] 2019-07-05 21:03
in case it helps anyone else out...
@romkatv offered a fix for hyper interpreting emoji's as two character widths for a zsh prompt:
https://github.com/robbyrussell/oh-my-zsh/issues/7945#issuecomment-508724741

Essentially: `PROMPT='%{%G🦀%}'`

**Comment by elegos** [comment] 2019-11-04 10:58
Any idea on how to fix when you actually write on ZSH, like a shell commit with an emoji?

**Comment by romkatv** [comment] 2019-11-04 11:10
> Any idea on how to fix when you actually write on ZSH, like a shell commit with an emoji?

It's a bug in Hyper so it needs to be fixed in Hyper.

**Comment by elegos** [comment] 2019-11-04 22:39
I know it's a Hyper bug, that's why I'm here. As the last comment is of the 5th of July I was wondering if anything can actually be made to fix it.

**Comment by romkatv** [comment] 2019-11-05 10:04
> I know it's a Hyper bug, that's why I'm here. As the last comment is of the 5th of July I was wondering if anything can actually be made to fix it.

Apparently no one is working on fixing this bug. You can either fix it yourself and send a PR, induce someone else to fix it, or wait and hope that others will do the work of fixing/inducing.

**Comment by Stanzilla** [comment] 2019-11-05 13:30
Hey there, to verify if this is indeed a Hyper issue or upstream at https://github.com/xtermjs/xterm.js/ could you please test if another xterm.js powered terminal shows the same problem you are experiencing? I suggest using https://github.com/Microsoft/vscode for testing. Thanks!

**Comment by elegos** [comment] 2019-11-06 13:51
@Stanzilla if the VSCode terminal uses xterm.js, it seems to be an xterm.js problem (same issue). I'm going to open a bug there.

**Comment by romkatv** [comment] 2019-11-06 14:05
I can confirm that the integrated terminal in VSCode also incorrectly prints 🦀 as if it was a narrow character.

![image](https://user-images.githubusercontent.com/1282067/68304709-9f92f180-00a6-11ea-9243-d1e45ae56304.png)

Here's how it's supposed to look like (same font and shell but in GNOME Terminal):

![image](https://user-images.githubusercontent.com/1282067/68304779-c7825500-00a6-11ea-8db8-b8f766bc6d17.png)

**Comment by Stanzilla** [comment] 2019-11-06 17:02
Yup, going to close this then.

**Closed by Stanzilla** 2019-11-06 17:02 UTC
Labels: 👆 Is Upstream

**Comment by jkulak** [comment] 2020-01-21 08:22
> @Stanzilla if the VSCode terminal uses xterm.js, it seems to be an xterm.js problem (same issue). I'm going to open a bug there.

Can you please link the issue you reported for xterm.js?

**Comment by philippnoah** [comment] 2020-02-26 17:55
`PROMPT='%1{🤖%} '` did the trick for me, could somebody confirm?

Credit to:
[(https://unix.stackexchange.com/questions/90772/first-characters-of-the-command-repeated-in-the-display-when-completing)]
