### ISSUE TITLE
Sluggish delete performance on Windows

### ISSUE THREAD

**Issue by tiborsaas** [zeit/hyper#1174] opened 2016-12-13 13:20 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- Windows 10
- 1.0

## Issue
Holding backspace does not always delete all text from the prompt. 

![e](https://cloud.githubusercontent.com/assets/342688/21141772/42bc2d90-c13f-11e6-8550-6cc869b80f35.gif)

**Comment by stefanivic** [comment] 2016-12-13 13:26
@tiborsaas strange. Works fine for me. 
![](http://i.imgur.com/cxQI7Uz.gifv)

**Comment by jonathandelgado** [comment] 2016-12-13 15:48
I can replicate this issue, appears hyper sometimes becomes out of sync when using backspace and arrow keys.

This might be related to https://github.com/Microsoft/vscode/issues/7345

**Comment by styfle** [comment] 2016-12-13 16:19
I also have this problem and it happens with arrow keys as well. What I see in the input and what shows up after I hit enter are not always the same.

**Comment by nkpfstr** [comment] 2016-12-13 19:08
I have this issue as well, but only when using Git Bash as my shell. When using cmd or PowerShell, delete works consistently as expected.

**Comment by Tyriar** [comment] 2016-12-13 23:03
To confirm what @nkpfstr, I have only observed this on non-cmd/PS shells in VS Code.

**Comment by appleskin** [comment] 2016-12-14 19:20
I've experienced this issue running cygwin bash.  The same type of thing can happen when clearing the buffer.

**Comment by celevra** [comment] 2016-12-20 21:23
i'Ve also experienced this with cygwin

**Comment by damien122** [comment] 2016-12-21 08:41
OS version and name: windows 10 x64

Hyper.app version: 1.0.0

for me the same problem with git bash and cmd ... sometimes the last two or three chars are not deleted and then after pressing enter, they are not interpreted as a command. For hyper it is like you press enter on an empty line.

**Comment by ashelley** [comment] 2017-01-09 19:06
Can confirm using "C:\Program Files\Git\bin\bash.exe" as my shell causes backspace to not work properly.

Step 1)

1) enter in long string of text into terminal
2) hold backspace

Expected results:

Back space deletes all characters

Actual results: Position of cursor seems laggy and "bounces back" while deleting.  End result is that you end up with a cursor position that it out of sync from what it should be and it looks like all text has not been deleted.

**Comment by Tyriar** [comment] 2017-01-16 05:51
This should be fixed in tomorrow's VS Code Insiders build using the beta build of node-pty. The next version of node-pty will include the long time coming winpty upgrade which fixes a host of issues, so I'm just verifying the current build and then waiting on the fix for https://github.com/rprichard/winpty/issues/96 (which affects WSL/Bash on Windows) before I publish the new version :tada:

**Comment by martinsustek088** [comment] 2017-01-27 10:19
I can confirm, that in Windows 1.9.0-insider build (commit 2c96...3f2f) in Git-bash shell backspace and left and right arrow keys works as it should.
With exception of unicode (multibyte) characters - they are displayed normally but for backspace/arrow keys they counts as multiple characters.
![vscode-terminal-unicode](https://cloud.githubusercontent.com/assets/9684125/22367479/0dc4efee-e482-11e6-8407-01196f648413.gif)

**Closed** 2018-04-23 00:03 UTC
Labels: 📊 Type: Performance, 🖼 Platform: Windows
