### ISSUE TITLE
Plugins and config lost after upgrade

### ISSUE THREAD

**Issue by kierenj** [zeit/hyper#3633] opened 2019-05-08 16:00 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Don't remember, where can I find this file?
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: ?

## Issue
I installed the latest version, now all my setup is gone.  Using the wrong shell, font, etc.

**Comment by Roki100** [comment] 2019-05-08 16:16
same here -_-

**Comment by FatehAK** [comment] 2019-05-08 16:18
There is a change in the config file location from %UserProfile%\.hyper.js to %AppData%\Hyper\.hyper.js. So just copy over the old config file and replace the new file

**Comment by kierenj** [comment] 2019-05-08 16:21
Can I suggest an urgent hotfix to copy this?

**Comment by Roki100** [comment] 2019-05-08 16:22
also we have to copy hyper plugins btw

**Comment by pcnate** [comment] 2019-05-08 16:34
several similar issues exist. some confusion exists because plugins and themes are both plugins that do different things. i don't think a hotfix would be a good idea to simply copy a file as many have already copied or changed it in the new location. I'd suggest editing the new config file with the values you want from the old one as new options are not added to the config file.

In powershell:

    Copy-Item $env:userprofile\.hyper.js $env:appdata\hyper\.hyper.js

**Comment by FatehAK** [comment] 2019-05-08 16:42
btw two new options are added -

Description: 
Choose either `'vertical'`, if you want the column mode when Option key is hold during selection(Default) or `'force'`, if you want to force selection regardless of whether the terminal is in mouse events mode (inside tmux or vim with mouse mode enabled for example).
`macOptionSelectionMode: 'vertical',`

Description:
Whether to use the WebGL renderer. Set it to false to use canvas-based rendering (slower, but supports transparent backgrounds)
`webGLRenderer: true,`

**Comment by voronoipotato** [comment] 2019-05-08 21:10
likely duplicate of https://github.com/zeit/hyper/issues/3589

**Comment by kierenj** [comment] 2019-05-08 21:24
humm, @pcnate how is this not the most major production issue which needs hotfixing? its a configurable terminal first and foremost, and clicking the upgrade link in the app seemingly loses all of that configuration?

**Comment by voronoipotato** [comment] 2019-05-08 21:31
@kierenj plugins can't be installed at all #3500  . Always back up all configs, I mean it's very bad that something deletes it but, clearly not the worst problem happening right now imho. If I could have plugins, them being deleted on update would be a mild inconvenience.

**Comment by JonWallsten** [comment] 2019-05-09 04:57
My .hyperjs config file as well as the all the backups created during installation was already reset. Non of them contained the actual config from before the update. Also the plugins folder, where I had a modified theme was removed.

**Comment by Stanzilla** [comment] 2019-10-10 22:00
Yeah they really rushed the last release, sorry for that.

**Closed by Stanzilla** 2019-10-10 22:00 UTC
