### ISSUE TITLE
"G" everywhere with nano on latest canary version

### ISSUE THREAD

**Issue by Metrakit** [zeit/hyper#3320] opened 2018-12-11 13:41 UTC
Hi,

- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Mojave 10.14
- **Hyper.app version**: Hyper 2.1.0-canary.3 (canary)

## Issue
I'm facing a weird issue, when im trying to edit a file with `nano`, I meet the letter `G` everywhere. Here's a screen : 
![capture d ecran 2018-12-11 a 14 33 26](https://user-images.githubusercontent.com/3305600/49804345-9db79580-fd52-11e8-9723-0879ed164eed.png)

Its write GGGG GGG on the top of the window and the bottom where there's the actions shorcuts.

On canary 2, there's no mistakes

**Comment by Tyriar** [comment] 2018-12-11 14:13
Root cause https://github.com/xtermjs/xterm.js/pull/1739, fixed in https://github.com/zeit/hyper/pull/3319

**Comment by chabou** [comment] 2018-12-11 14:24
Thank you @Tyriar for this triage.

**Closed by chabou** 2018-12-11 14:24 UTC

**Comment by Metrakit** [comment] 2018-12-11 14:31
yeah thanks @Tyriar , sorry I have only search issues on the Hyper project.
