### ISSUE TITLE
Close panes shortcut

### ISSUE THREAD

**Issue by ortonomy** [zeit/hyper#2159] opened 2017-09-02 05:38 UTC
I can open as many vertical splits, and horizontal splits as my window can manage...

but how do I close them / remove split pane view? Vanilla terminal can do this?

**Comment by chabou** [comment] 2017-09-02 05:58
Please use our issue template!

**Comment by chabou** [comment] 2017-09-02 05:58
Duplicate of #2145

**Closed** 2017-09-02 05:59 UTC
