### ISSUE TITLE
Git automerge - nano edit fail

### ISSUE THREAD

**Issue by dadema** [zeit/hyper#1279] opened 2016-12-20 08:32 UTC
- [ X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MAC OS SIERRA 10.12.2
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
When git open the automerge editor (Nano) I write commit, than I use `ctr+O` (writeout) to save info and when I use `ctr+X` (exit) to close, hyper doesn't close nano and I don't understand how to go on with terminal .. 
I try to use another pc with Ubuntu 16. Same problem with the same hyper version 1.0.0 . I can't close nano after commit message.
I try to edit hosts with nano (`sudo nano /etc/hosts`), hyper open nano, add new host, and everythings is ok!
Where I'm doing wrong when git open auotmerge editor ?

**Comment by Specro** [comment] 2016-12-20 11:04
Have you tried <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>X</kbd>?

Dupe #1069

**Comment by nbolten** [comment] 2016-12-20 20:09
This is a dupe of #1069 and #1132. Basically, `hyper` uses <kbd>Ctrl</kbd> as its mod key by default on Windows and Linux, which is not ideal. This does not impact Mac users, as <kbd>Cmd</kbd> is used there.

I've put in a pull request at #1191 and would appreciate any confirmations/feedback you can provide there.

**Comment by dadema** [comment] 2016-12-27 22:30
Great!! `Ctrl` `Shift` `X ` Also on Linux (ubuntu 16)
@Specro Thanks :+1:

**Comment by ppot** [comment] 2017-08-15 00:09
close in #1876

**Closed by ppot** 2017-08-15 00:09 UTC
Labels: Type: Bug
