### ISSUE TITLE
Default install issues

### ISSUE THREAD

**Issue by blackxored** [zeit/hyper#1728] opened 2017-04-04 22:52 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.4
- **Hyper.app version**: 1.3.1.1628
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: no hyper.js / default
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes, I'm totally clean

## Issues

* Weirdness with right prompt inside tmux.
Outside tmux:
![](https://www.dropbox.com/s/zgz797ngyy4q6v3/Screenshot%202017-04-05%2000.45.31.png?dl=1)
Inside tmux:
![](https://www.dropbox.com/s/wllcavy2n17yask/Screenshot%202017-04-05%2000.46.24.png?dl=1)

No powerline support obviously, when I load the font (Inconsolata for Powerline) this happens:

* Cursor is weird compared to letters: 
![](https://www.dropbox.com/s/yu0gm2ock0826kj/Screenshot%202017-04-05%2000.47.59.png?dl=1)
* Bottom of tmux window gets cut out:
![](https://www.dropbox.com/s/gvo7yz1gcw7h5e4/Screenshot%202017-04-05%2000.48.31.png?dl=1).

I really like how extensible and open this is, but really, I can't really jump if it's unusable from the start, not the first time I've tried. Here's iTerm in comparison (same font, same tmux config, a bit of fancy background but that's about it): 

![](https://www.dropbox.com/s/6gjksizfyktrjmu/Screenshot%202017-04-05%2000.50.42.png?dl=1)

**Comment by MartyGentillon** [comment] 2017-04-15 08:07
This is a duplicate of https://github.com/zeit/hyper/issues/1722

**Comment by MartyGentillon** [comment] 2017-04-18 22:35
Though not entirely.... The issue where the text that should be on the right side of the screen isn't in that bug.  The bottom of tmux getting cut is covered by it though.

**Comment by blackxored** [comment] 2017-07-17 22:53
It's been a while. I managed to fix a thing or two since the last time I tried Hyper.
Here are some issues that remain though:

1. Prompt gets corrupted inside tmux (doesn't happen outside) as in characters are being "eaten". I happened to figure out it's because of my lambda symbol, hence I'm assuming yet another Unicode glyph trouble?

1st prompt:

![](https://www.dropbox.com/s/wqq4b32uhcvo9re/Screenshot%202017-07-18%2000.48.14.png?dl=1)

2nd prompt: (exactly the same, just removes the symbol)

 ![](https://www.dropbox.com/s/0zq4wsaj07h6mx4/Screenshot%202017-07-18%2000.46.21.png?dl=1)

2. Bottom of powerline still corrupted (tmux 2.5):

![](https://www.dropbox.com/s/b3y9blctspbsiov/Screenshot%202017-07-18%2000.49.08.png?dl=1)

3. Underline of items doesn't align properly. I always thought of why does it look different, and it's because there's no space between the line and the text, causing (in my case) even letters to get cut off from the underlining.
Look at the g here:
 
![](https://www.dropbox.com/s/48lru5cqc4k2abt/Screenshot%202017-07-18%2000.50.46.png?dl=1)

Here's iTerm in comparison (slightly bigger font, but shouldn't matter): 

![](https://www.dropbox.com/s/og0mjizcuywbhgl/Screenshot%202017-07-18%2000.51.14.png?dl=1)

Can some please shed some light into this issues? I'd be willing to help diagnose and yeah I speak JavaScript 😂

**Comment by ppot** [comment] 2017-08-14 00:36
There is no images?

**Comment by blackxored** [comment] 2017-08-14 13:20
Github cache seems to be having a day, images are there.

Links (viewable): 

* https://www.dropbox.com/s/wqq4b32uhcvo9re/Screenshot%202017-07-18%2000.48.14.png?dl=0
* https://www.dropbox.com/s/0zq4wsaj07h6mx4/Screenshot%202017-07-18%2000.46.21.png?dl=0
* https://www.dropbox.com/s/b3y9blctspbsiov/Screenshot%202017-07-18%2000.49.08.png?dl=0
* https://www.dropbox.com/s/48lru5cqc4k2abt/Screenshot%202017-07-18%2000.50.46.png?dl=0
* https://www.dropbox.com/s/og0mjizcuywbhgl/Screenshot%202017-07-18%2000.51.14.png?dl=0

**Comment by Stanzilla** [comment] 2018-04-23 00:55
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Closed by Stanzilla** 2018-04-23 00:55 UTC
