### ISSUE TITLE
unable to page scroll using alt using tmux

### ISSUE THREAD

**Issue by fpereira1** [zeit/hyper#472] opened 2016-07-28 00:16 UTC
Hi,

Just logging an issue that I am unable to scroll pages by holding the `alt` in tmux.  Line scroll works fine (without holding the `alt` key)

I am using version 0.7.1.36 on mac.

Otherwise, for me, tmux works great 👍

**Comment by rauchg** [comment] 2016-07-28 00:18
It's tricky because we also use alt as a modifier for alt -> arrows I believe. @marcbachmann

**Comment by fpereira1** [comment] 2016-07-28 00:19
This could be related to #213

**Comment by albinekb** [comment] 2016-07-28 00:28
https://github.com/zeit/hyperterm/blob/master/lib/hterm.js#L32
tmux uses the meta-key right?

**Comment by koresar** [comment] 2016-07-28 03:11
I'm using the following key combination to page up in OSX:
* Ctrl+B
* Fn+Up and Fn+Down

**Comment by fpereira1** [comment] 2016-07-28 03:53
@koresar you're right, that works! I have just always used:

- Ctrl+B
- Alt+Up and Alt+Down

**Comment by CodeTheory** [comment] 2016-07-29 13:04
@fpereira1 Does this mean the issue is resolved?

**Comment by suitupalex** [comment] 2016-07-29 19:51
@CodeTheory I'd say that using Fn+Up and Fn+Down (which are actually the same thing as the Page Up and Page Down keys on most laptops) is just a workaround.

This issue is more a duplicate of #213.

**Comment by fpereira1** [comment] 2016-07-29 21:44
@CodeTheory, as @rauchg pointed out, `alt` is used as a modifier to control jump to previous words in the terminal (PR #217).  I guess the issue is that `alt` is not being sent to the hterm.   This is not an issue for me anymore because of the workaround.

**Comment by matheuss** [comment] 2016-07-30 04:23
Closing: 
> This is not an issue for me anymore because of the workaround.

**Comment by rauchg** [comment] 2016-07-30 04:28
@fpereira1 I do want to reconsider whether alt instead of command is a good idea, and whether we should send alt to the terminal. @marcbachmann

**Comment by btipling** [comment] 2016-12-22 05:34
My tmux scrolling with mousewheel setup doesn't work at all. Sometimes freezes hyper. 😞 


In my tmux.conf I have:
`set -g mouse on`

**Comment by chabou** [comment] 2017-04-19 22:28
I think it is fixed.
(related to `altIsMeta` and `cmdIsMeta` options)

Feel free to reopen if not

**Closed by chabou** 2017-04-19 22:28 UTC
