### ISSUE TITLE
Input display appears delayed by 1 line after lots of rapid output

### ISSUE THREAD

**Issue by brucedjones** [zeit/hyper#2178] opened 2017-09-06 15:59 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate. It may be related to #571 

- Windows 10: 
- 1.4.3: 
-
 [gist](https://gist.githubusercontent.com/brucedjones/c6c2601b46363d7b12d08ea3f7337bd0/raw/439643ffedea909986dc9f15ce38b707cdea92b0/hyper.js) 
- N/A
- Is Vanilla 

## Issue
After lots of rapid commandline output, the display of my inputs appears to be delayed by one line. I can still enter commands in to the terminal, and if I press Enter, they are executed. However, anything I enter into the prompt is not displayed until I press Enter.

This may be related to #571, however the rendered does not appear to crash on my machine. 

This is reproduced by doing the following:
```
python
while True:
  print('hello')
<Enter>
<wait a few seconds>
<ctrl+c>
<observe odd behavior>
```

**Comment by chabou** [comment] 2017-09-06 21:14
Will be fixed by Hyper v2, using `xterm`instead of `hterm`
I juste tested your HTR on `xterm` and there is no problem.

**Comment by brucedjones** [comment] 2017-09-07 14:23
Ah great, thank you. I've confirmed this my end too.

**Comment by petertdinh** [comment] 2017-09-12 17:48
@chabou How do I switch my Hyper to use xterm instead of hterm?

**Comment by albinekb** [comment] 2017-09-15 09:45
@petertdinh clone this repo, run `git checkout xterm` and follow the directions in the readme to compile from source 👍  Hop into the community slack -> [![Slack Channel](http://zeit-slackin.now.sh/badge.svg)](https://zeit.chat/) if you get stuck, need help or just wanna chat 👋

**Comment by timothyis** [comment] 2018-04-22 02:11
Since you confirmed Xterm fixed your issue, @brucedjones, and we've now launched v2, this should be fixed! I'm going to go ahead and close this, but please re-open if the issue still persists.
Thanks for the submission! 🙌

**Closed by timothyis** 2018-04-22 02:11 UTC
Labels: 🏚 Hterm bug
