### ISSUE TITLE
Notification about the release of previous version

### ISSUE THREAD

**Issue by anticore** [zeit/hyper#3106] opened 2018-06-25 16:10 UTC
- [x] Your Hyper.app version is **2.1.0-canary.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:
N/A

  - **Is the issue reproducible in vanilla Hyper.app?**
Is Vanilla.

## Issue
Just installed Hyper version 2.1.0-canary.2. On startup I get a notification about 2.0.0 being ready. This notification shows every time Hyper is started. I'm wondering if:

- This notification should not be present since 2.1.0 is a higher version than the one being announced;
- Update notifications should be configurable - there should be a setting to disable them.

 - **Hyper version**: undefined "2.1.0-canary.2"

 - **OS ARCH VERSION:** linux x64 4.10.0-42-generic
 - **Electron:** 1.8.4  **LANG:** en_US.UTF-8
 - **SHELL:** /bin/bash   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 10,
  "fontFamily": "Monaco, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "normal",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(106,118,251,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(106,118,251,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": false,
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true
}

          {
  "plugins": [],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by albinekb** [comment] 2018-06-25 16:36
Hi! You need to change `"updateChannel": "stable"` to `"updateChannel": "canary"`, duplicate of #2704

**Closed by albinekb** 2018-06-25 16:36 UTC
