### ISSUE TITLE
Updating the plugins results in an error on windows.

### ISSUE THREAD

**Issue by schartz** [zeit/hyper#1217] opened 2016-12-15 05:18 UTC
Trying to update the plugins results in a warning notification saying please check 

~/.hyper-plugins/npm-debug.log

I tried checking my home directory 

C:\Users\<my_username>\.hyper-plugins

but there was no file with the name npm-debug.log

Just in case if its relevant, I dont have any previous nodeJS installation on my windows machine.

-

Hyper 1.0.0
Electron 1.4.7
win32 x64 10.0.10240

**Comment by jonathandelgado** [comment] 2016-12-15 05:39
Dupe of #1166

**Comment by ppot** [comment] 2016-12-15 05:41
Yes closing in favor of @1166

**Closed by ppot** 2016-12-15 05:41 UTC
Labels: Is Duplicate
