### ISSUE TITLE
Link to linux version not found - website

### ISSUE THREAD

**Issue by iheartkode** [zeit/hyper#1067] opened 2016-12-01 19:58 UTC
https://hyper-updates.now.sh/download/linux  returns "Version not found: latest"

**Comment by kleinfreund** [comment] 2016-12-01 20:20
Duplicate of https://github.com/zeit/hyper/issues/799

Use the search first, please.

**Comment by matheuss** [comment] 2016-12-01 20:36
Thank you @kleinfreund

**Closed by matheuss** 2016-12-01 20:36 UTC

**Comment by iheartkode** [comment] 2016-12-01 20:50
I used search, it returned no results for me. :+1:

**Comment by matheuss** [comment] 2016-12-01 20:51
Don't worry @iheartkode 🙌
