### ISSUE TITLE
Packaging Hyper + Ubuntu PPA

### ISSUE THREAD

**Issue by nhejazi** [zeit/hyper#825] opened 2016-10-08 20:27 UTC
Have been using Hyper/HyperTerm for a while on macOS (Sierra) and Ubuntu (14.04). Before the recent name change to Hyper (as of v0.8.0), there was a working [Brew Cask](http://caskroom.io) formula. Are there currently any plans to properly set up packaging (via a PPA) for streamlining installs via `apt-get`?

**Comment by flybayer** [comment] 2016-10-08 22:29
Yeah, this is a duplicate of #799 :)

**Closed** 2016-10-11 01:02 UTC
