### ISSUE TITLE
Windows: cannot copy to clipboard using keyboard

### ISSUE THREAD

**Issue by warpdesign** [zeit/hyper#1153] opened 2016-12-13 00:48 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 (14986)
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Yes
## Issue

Cannot copy selected text using the keyboard

How to reproduce:
--
- Select some text using the mouse
- Press ctrl+shift +c

What happens ?
--
The moment I press ctrl / shift, the text is unselected, so nothing is copied to the clipboard when the full shortcut ctrl+shift+c is pressed.

Note that selecting some text with the mouse, then using the `select -> paste` menu works, the problems seem to be with the keyboard only.

**Comment by CodeTheory** [comment] 2016-12-13 00:52
Duplicate of #1121. Please contribute to that issue.

**Closed by CodeTheory** 2016-12-13 00:52 UTC

**Comment by rahilwazir** [comment] 2016-12-13 13:26
@CodeTheory FWIW, this issue also exists in Linux Fedora. Should I create a new issue?

**Comment by CodeTheory** [comment] 2016-12-13 13:27
No, @rahilwazir. I just added the label for Linux to #1121. Thanks for informing me!
