### ISSUE TITLE
Text does not wrap

### ISSUE THREAD

**Issue by TAQ2** [zeit/hyper#917] opened 2016-10-21 10:23 UTC
when you have a long command and then decrease the size of the terminal the text does not wrap

**Comment by iamstarkov** [comment] 2016-10-21 10:55
duplicate of #476, check it out

**Comment by matheuss** [comment] 2016-10-21 10:56
Thank you @iamstarkov ☺️

**Closed by matheuss** 2016-10-21 10:56 UTC

**Comment by TAQ2** [comment] 2016-10-21 11:02
thanks for the help :)
