### ISSUE TITLE
Cursor position & PS1 emoticon

### ISSUE THREAD

**Issue by JoaoFOliveira** [zeit/hyper#954] opened 2016-11-01 22:18 UTC
- [X] I am on the 0.8.3 Hyper.app version
- [X] I have searched the 280 of this repo and believe that this is not a duplicate

- macOS Sierra (10.12): 
- 0.8.3: 
- Is vanilla: 

## Issue

Just downloaded Hyper for my Mac, and this happens:

![issue](https://media.giphy.com/media/3oriO5C5TKxq9tfhTO/giphy.gif "Issue")

You can see 2 issues: the cursor is dislocated from the $ prompt, and on a new tab, whenever an emoticon is set, it doesn't render correctly.

My bash_profile has the following exports:
export PS1="\[\033[32m\]\h@\[\033[33;1m\]\W\[\033[m\] 😎  $ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

**Comment by CodeTheory** [comment] 2016-11-01 22:27
Cursor position is a duplicate of #577
Second issue is a duplicate of #645

**Closed by CodeTheory** 2016-11-01 22:27 UTC
