### ISSUE TITLE
Can't type " or ' on US Int

### ISSUE THREAD

**Issue by JuHwon** [zeit/hyper#518] opened 2016-07-30 16:40 UTC
When i am typing with the `U.S. International - PC` layout of my mac i cant type the caracter `'` or `"`  neither can i type `~`  nor ` ` ` though. :(  This is kind of a dealbreaker for me.

**Comment by YuriBrunetto** [comment] 2016-07-30 16:50
same for me :(

**Comment by MrRio** [comment] 2016-07-30 16:53
Try set it to just U.S.?

**Comment by MrRio** [comment] 2016-07-30 16:55
<img width="456" alt="screen shot 2016-07-30 at 17 54 47" src="https://cloud.githubusercontent.com/assets/47539/17271829/c332f05c-567e-11e6-8351-f27a78088ec5.png">

On International - PC those keys show in orange for some reason

**Comment by YuriBrunetto** [comment] 2016-07-30 17:00
@MrRio setting to just `U.S` worked for me. but, my native language is PT-BR and some words require special characters like `ção`, `é`

Those keys shows in orange because of this special characters, right after you type ' and type a certain char, it automatically type the special character.

**Comment by JuHwon** [comment] 2016-07-30 17:37
yeah U.S. does work ofc. 
Though there is a reason why i have selected the US International layout like YuriBrunetto explained.
This is the only application with which i got problems. :/

**Comment by MrRio** [comment] 2016-07-30 18:05
I've put together a patch for this. Ideally we'd add in full support for the modifiers, but this makes it at least usable for now.

**Comment by tleunen** [comment] 2016-08-15 21:14
Master is a bit better now, indeed, but still not optimal :/ Hopefully we can get a fix for this :)

**Comment by douglascamata** [comment] 2016-08-19 16:02
So bad that such a basic bug like this is still present. First thing I did when I installed HyperTerm: open config file with Vim to add plugins and I noticed that I couldn't type `'` or `"` 😢

**Comment by frdmn** [comment] 2016-09-25 20:08
I can confirm, `~` doensn't work with german keyboard layout. :(

**Comment by duivvv** [comment] 2016-09-25 20:22
also doesn't work on AZERTY (belgian keyboard) should be alt+n

**Comment by rainerborene** [comment] 2016-10-26 15:49
This is my keyboard layout. Most of the accents and special characters doesn't work as expected.
![screen shot 2016-10-26 at 13 48 20](https://cloud.githubusercontent.com/assets/101501/19733476/de4cf4fc-9b82-11e6-803a-22694c37bf85.png)

**Comment by magnli10** [comment] 2016-11-07 16:00
Does not work with norwegian keyboard layout as well  
![screen shot 2016-11-07 at 17 00 11](https://cloud.githubusercontent.com/assets/1397204/20064637/a510fc1e-a50b-11e6-8daf-8649699e840b.png)

**Closed** 2016-11-16 18:44 UTC
Labels: Priority: OMG Maximum, Type: Compatibility
