### ISSUE TITLE
AltGr keyshortcuts don't work

### ISSUE THREAD

**Issue by httpsterio** [zeit/hyper#2869] opened 2018-04-18 14:25 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Latest Windows 10 (1709)
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/httpsterio/0f6393b4b91b9b9a0990532cf231b809
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
There are a few characters I can't type with the latest Hyper, basically any number + AltGr except 0 and + won't work. I can't type @, { etc. 

I've tried rebooting my machine, another keyboard, another terminal. It seems like it's an issue with Hyper.

**Comment by Stanzilla** [comment] 2018-04-23 23:42
So we have a keymaps system where everything is customizable, does this help you? See https://hyper.is/#keymaps

**Comment by httpsterio** [comment] 2018-05-08 09:52
Well, not really. I mean, shouldn't the keyboard layouts work as usual? On MacOS there's no issues with typing @ for example in the terminal, but on Windows it's not possible.

**Comment by Stanzilla** [comment] 2018-05-08 11:15
Well I can not reproduce, that's my problem.

**Comment by steph-ben** [comment] 2018-10-04 08:41
This is a duplicate of https://github.com/zeit/hyper/issues/3107

**Closed** 2019-09-30 20:23 UTC
Labels: 👀 Awaiting Response, 🖼 Platform: Windows
