### ISSUE TITLE
Copying line-break also copy the inserted newline. (shouldnt)

### ISSUE THREAD

**Issue by neolectron** [zeit/hyper#1911] opened 2017-06-07 09:52 UTC
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **w10 last build**: 
- **Hyper.app 1.3.3**: 
- **Link of a [Gist](https://gist.github.com/neolectron/ac8932a448efc36139bb14bf0daa6a9b) with the contents of my .hyper.js**: 
- **The issue is reproducible in vanilla Hyper.app**:
## Issue
 When I have long lines, hyper fit them on screen with a newline. (OK)
but when i copy it, it copy the "fake newline" . and it shouldnt. (very annoying)

DEMO : 

https://puu.sh/wdgbY/1b6991a482.gif

Thanks for help :)

**Comment by yolo3301** [comment] 2017-10-18 18:12
Facing the same annoying issue all the time.

**Comment by albinekb** [comment] 2017-10-18 18:17
Hi! Could you please try the `canary` release channel, learn how to switch at https://zeit.co/blog/canary

In 2.x (coming soon ™️) we have replaced the whole terminal rendering library from `hterm` to `xterm.js`, xterm is much more mature and there's a chance this is an issue with `hterm`.

However this could also be something wrong with hyper, but please check if you can reproduce it in 2.x and we'll take it from there 💪

**Comment by carragom** [comment] 2017-11-09 05:25
Hi there, having this same issue, using 2.1.1 on Windows 10 with WSL. This problem looks similar to microsoft/vscode#23142 and seems to be solved in xtermjs/xterm.js#443. Will this be fixed on the next release?

**Comment by chabou** [comment] 2017-11-09 06:56
`hyper` v2.1.1 uses `xtermjs` v2.9.2 and has already this patch, landed in `xtermjs` v2.8.0.

**Comment by carragom** [comment] 2017-11-09 06:59
Excellent news. But then I have no idea why it is not working.

**Comment by mcrump001** [comment] 2018-01-29 21:56
I too am experiencing this issue with the latest version of hyper.js.  Are there any updates on this?

**Comment by jleaders** [comment] 2018-04-11 23:00
I have the same issue, Hyper 1.4.8 on Windows 10

**Comment by chabou** [comment] 2018-04-12 07:14
@jleaders It has been fixed in our canary (upcoming v2). See #1448

**Closed by chabou** 2018-04-12 07:14 UTC
