### ISSUE TITLE
Chinese Language support please

### ISSUE THREAD

**Issue by ShineSmile** [zeit/hyper#2014] opened 2017-07-18 08:04 UTC
Input Chinese character with Sougou Pinyin IME doesn't work well.
 The width of Chinese character displayed is not enough.
-

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by Sanster** [comment] 2017-07-25 07:52
@ShineSmile Check https://github.com/zeit/hyper/issues/2012
```
 termCSS: '.wc-node{width:16px !important}',
```

**Comment by ShineSmile** [comment] 2017-07-27 04:04
@Sanster Thanks. The problem of display has been resolved. 

But I still can't input Chinese character with IME.
Nether Sougou Pinyin IME nor Microsoft Pinyin works.

**Comment by Hypnoes** [comment] 2017-08-01 07:08
And also in non-English mode, you should type twice to input one character. 😆

**Comment by hunnble** [comment] 2017-08-04 07:54
Also, after pasting some Chinese characters, I found that these characters were rendered twice

**Comment by yuezy3** [comment] 2017-09-27 10:45
Well, I think this is very serious issue. 
This app can't display (properly) and input Unicode Char??!!

**Comment by yuezy3** [comment] 2017-09-27 10:45
Well, I think this is very serious issue. 
This app can't display (properly) and input Unicode Char??!!

**Comment by albinekb** [comment] 2017-09-27 12:10
@yuezy3 the problem is, to fully support chinese and other double-width languages we need to have someone that knows chinese and can read it, It's really hard for me or someone else that doesn't know anything about this language to fix all the things that are wrong, and at the same time make sure that we don't accidentally break anything, as we can't know how it's supposed to be.

TL:DR
To fully support chinese, we need a chinese maintainer...

**Comment by Piping** [comment] 2018-04-10 06:47
Hi, I would like to take a look on the code itself. Any guide for implementing double-width characters?

**Comment by chabou** [comment] 2018-04-10 10:17
I think that this issue has been fixed in our canary (upcoming v2).
@Piping This is handled directly by `xtermjs`: https://github.com/xtermjs/xterm.js/

**Closed by chabou** 2018-04-10 10:17 UTC
