### ISSUE TITLE
Broken first line rendering in VIM (parseUntilStringTerminator_ aborts)

### ISSUE THREAD

**Issue by L-A** [zeit/hyper#1037] opened 2016-11-23 14:51 UTC
- [x] I am on version `1.0.0`
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- [x] The issue is reproducible in vanilla Hyper.app

- **OS version and name**: OS X 10.12.1 (Sierra)
- **Hyper.app version**: [`1.0.0`](https://github.com/zeit/hyper/commit/833383a1cc655690f008aaba70527542f6399499)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/L-A/7a674f3ebb88fa5fbfb78bfdc89bc2ed
- **Relevant information from devtools**:
See right under the screenshots

### This issue was introduced in da4858a76e4faad6e5ee49f9cebf80e3fa981de4

Here is the expected result of opening a given file with `vim` (from 0.8.3):
![screen shot 2016-11-23 at 09 40 44](https://cloud.githubusercontent.com/assets/861964/20565928/61a1e648-b161-11e6-99a7-c9f0494fee68.png)

Here is what is displayed after da4858a76e4faad6e5ee49f9cebf80e3fa981de4:
![screen shot 2016-11-23 at 09 40 21](https://cloud.githubusercontent.com/assets/861964/20565937/6b70b8d4-b161-11e6-9100-3193c952c3f0.png)

Note that the cursor is actually positioned on the first character of the line, and will start re-rendering proper characters once I start moving it.

The very first character on screen (at position 0,0), seems to never be redrawn unless I replace it completely.

From the devtools for this very file:

```javascript
parseUntilStringTerminator_: aborting: embedded escape: 6 +q436f
bundle.js:36390 Ignored ESC code: "\\"
bundle.js:36352 parseUntilStringTerminator_: aborting: embedded escape: 6 +q6b75
bundle.js:36390 Ignored ESC code: "\\"
bundle.js:36352 parseUntilStringTerminator_: aborting: embedded escape: 6 +q6b64
bundle.js:36390 Ignored ESC code: "\\"
bundle.js:36352 parseUntilStringTerminator_: aborting: embedded escape: 6 +q6b72
bundle.js:36390 Ignored ESC code: "\\"
bundle.js:36352 parseUntilStringTerminator_: aborting: embedded escape: 6 +q6b6c
bundle.js:36390 Ignored ESC code: "\\"
bundle.js:36352 parseUntilStringTerminator_: aborting: embedded escape: 6 +q2332
bundle.js:36390 Ignored ESC code: "\\"
bundle.js:36352 parseUntilStringTerminator_: aborting: embedded escape: 6 +q2334
bundle.js:36390 Ignored ESC code: "\\"
bundle.js:36352 parseUntilStringTerminator_: aborting: embedded escape: 6 +q2569
bundle.js:36390 Ignored ESC code: "\\"
bundle.js:36352 parseUntilStringTerminator_: aborting: embedded escape: 6 +q2a37
bundle.js:36390 Ignored ESC code: "\\"
bundle.js:36352 parseUntilStringTerminator_: aborting: embedded escape: 6 +q6b31
bundle.js:36390 Ignored ESC code: "\\"
```

**Comment by L-A** [comment] 2016-12-12 18:20
Sad heads up: As of 1.0.0 (2b3c49b), this is still true.

**Comment by Deseao** [comment] 2016-12-20 21:42
+1, I'm seeing this as well.

**Comment by juandjara** [comment] 2016-12-20 21:56
+1. Happens every time I do this:

1. Open vim (.hyper.js in this case)
2. Edit a line
3. Exit vim
4. Open the same file again
5. The line I edited is overlapped with this strange line shown in the picture from the first comment

However this strange line disappears with vim scrolling

**Comment by L-A** [comment] 2016-12-20 22:08
@ppot Edited to point out that it was introduced in da4858a76e4faad6e5ee49f9cebf80e3fa981de4.

**Comment by saadq** [comment] 2016-12-25 11:15
Same issue here.

![screen shot 2016-12-25 at 6 10 30 am](https://cloud.githubusercontent.com/assets/5678694/21470872/f88ad77a-ca68-11e6-922b-4d4953b4e729.png)

Not ideal, but as a temporary fix, you can currently just scroll down in the file until the first line is not visible, and then scroll back up which should make the first line rendered properly:

![screen shot 2016-12-25 at 6 13 46 am](https://cloud.githubusercontent.com/assets/5678694/21470890/502f6dce-ca69-11e6-8d69-bca7c10da5f2.png)

**Comment by josephstover** [comment] 2016-12-29 17:53
+1, I am having the same problem

**Comment by L-A** [comment] 2016-12-31 04:20
I'm digging into this a bit more. It's definitely related to `vim-airline`, and probably `hterm`'s handling of the problematic output. Ref → https://github.com/vim-airline/vim-airline/issues/393

Disabling `vim-airline` makes all symptoms disappear. The character sequence that's rendered on the first line is actually data that's appended to Airline's printed line in Vim. This also explains why it inherits its last span's color and background.

If any of you want to try, you can add the following line to your `.vimrc` (the line really ends at `=`, you just want to assign nothing):

    set t_RV=

Source: http://cygwin.1069669.n5.nabble.com/Bad-XTerm-Vim-coloring-td68948.html

**Comment by Anzumana** [comment] 2017-03-16 09:24
did not use the plugin so did not have the issue either.

**Comment by paulmolluzzo** [comment] 2017-05-03 17:39
Confirming this issue persists and this fix works:

> If any of you want to try, you can add the following line to your `.vimrc` (the line really ends at `=`, you just want to assign nothing):
> 
> ```
> set t_RV=
> ```

**Comment by oguzbilgic** [comment] 2017-08-22 17:21
As far as I can tell, this still seems to be an issue.

**Comment by TooTallNate** [comment] 2017-09-25 20:57
https://github.com/zeit/hyper/issues/2281 was a duplicate of this one.

**Comment by Stanzilla** [comment] 2018-04-23 01:11
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Closed by Stanzilla** 2018-04-23 01:11 UTC
Labels: 🐛 Type: Bug
