### ISSUE TITLE
Exception thrown on open of preferences

### ISSUE THREAD

**Issue by davealexis** [zeit/hyper#2562] opened 2017-12-30 00:42 UTC
I just installed Hyper on Windows 10.  Any attempt to open the preferences (either Ctrl-, or Edit -> Preferences menu) causes a "Windows Script Host" error dialog with the following information:
Script: c:\users\<my user>\.hyper.js
Line: 5
Char: 1
Error: 'module' is undefined
Code: 800A1391
Source: Microsoft JScript runtime error

        -
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.16299

**Comment by MAPESO** [comment] 2017-12-30 18:42
@davealexis I will review your problem, when I have relevant information I will let you know 😸

**Comment by MAPESO** [comment] 2017-12-31 01:51
@davealexis 

**Hyper**: 1.4.8
**OS**: Windows 10
![26513869_1207082559435332_168188576_o](https://user-images.githubusercontent.com/16585386/34458474-e4803888-ed99-11e7-8a3a-d2dad294b354.png)

You could try to remove Hyper and reinstall it 🤔

If the error persists, let me know 🙏

**Comment by davealexis** [comment] 2018-01-01 14:56
Tried re-installing and got the same problem.
Then I got to thinking why it seems to be trying to run the .hyper.js file with Windows Scripting Host.  From your screenshot, it seems as if the file just gets opened in the default "open with" handler (Notepad, in your case).  Sure enough, for some reason my system was set to open .js files with Windows Scripting Host!  I changed the default to Atom, just for giggles, and now the preferences file gets opened  for edit from within Hyper.  :)

A good feature to have might be to build a basic editor into Hyper for the preferences file.

**Comment by MAPESO** [comment] 2018-01-01 15:39
@davealexis We will consider it 😺 

If the problem is solved, you can close the issue.

**Comment by kasper3** [comment] 2018-01-08 05:32
@MAPESO, I got caught into same issue and ended up on this thread. The default file handler of JS on Windows is Windows Scripting Host. Can this issue be re-purposed as a feature request to what @davealexis is suggesting? Hyper can use it's own instance to display the prefs.

Slack has an impressive preference view for example:

<img src="https://biz30.timedoctor.com/images/2017/04/slack-preferences.png" width="60%" />

**Comment by albinekb** [comment] 2018-01-23 13:38
This is fixed in the latest canary release! https://github.com/zeit/hyper/releases/tag/2.0.0-canary.11

**Closed by albinekb** 2018-01-23 13:38 UTC
