### ISSUE TITLE
Copying a high-lighted selection in the terminal removes the high-lighted selection

### ISSUE THREAD

**Issue by BChip** [zeit/hyper#990] opened 2016-11-13 02:08 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS Loki and Elementary**: 
- **Hyper.app latest**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Copying a high-lighted selection in the terminal removes the high-lighted selection.

Ex: Highlight something in the terminal, copy it, and the selection is gone. 

Most modern user interfaces face this problem

**Comment by ppot** [comment] 2016-11-16 01:13
@BChip I can't reproduce this error on the laster hyper.app

**Comment by BChip** [comment] 2016-11-16 02:44
@ppot Are you on Elementary OS (Ubuntu based)? It could just be my OS.

**Comment by ppot** [comment] 2016-11-16 02:52
@BChip I'm on macOS

**Comment by ppot** [comment] 2016-11-17 23:09
@BChip Are you copying with `ctrl+c`

**Comment by BChip** [comment] 2016-11-17 23:12
Yes @ppot and I will create a GIF later tonight to show

**Comment by ppot** [comment] 2016-11-25 04:19
@BChip Friendly ping 🎉

**Comment by askl56** [comment] 2016-12-19 12:46
Having this same issue on Ubuntu 16.10

**Comment by ppot** [comment] 2016-12-19 22:14
closed in PR #1218 :)

**Closed by ppot** 2016-12-19 22:14 UTC

**Comment by askl56** [comment] 2016-12-19 23:40
@ppot i only installed Hyper yesterday so that seems unlikely

**Comment by ppot** [comment] 2016-12-19 23:58
@askl56 #1218 is in the next release! so 1.0.1 ;) comping soon this week or next!

**Comment by askl56** [comment] 2016-12-20 10:50
Ah cool thanks @ppot
