### ISSUE TITLE
Spacing incorrect

### ISSUE THREAD

**Issue by moongod101** [zeit/hyper#886] opened 2016-10-16 05:03 UTC
![image](https://cloud.githubusercontent.com/assets/13918481/19415352/c08c5014-93a0-11e6-9faf-297c5aebe586.png)

**Comment by CodeTheory** [comment] 2016-10-18 15:05
Could you provide some more information here? What exactly is it that's not spaced properly here? Multiple things?

**Comment by moongod101** [comment] 2016-10-18 17:32
The text i type will be in the middle at my BLOCK cursor

**Comment by revelt** [comment] 2016-10-25 08:36
@moongod101 this is a Hyper's feature, not a bug. That's how block-style cursor behaves!

![cursor](https://cloud.githubusercontent.com/assets/8344688/19678621/644faf24-9a96-11e6-962b-3d7a6ddd77ed.gif)

@moongod101 Please either clarify further or close this Issue ticket.

**Closed** 2016-10-25 08:39 UTC
Labels: Status: Awaiting Response
