### ISSUE TITLE
cursor offset in terminal

### ISSUE THREAD

**Issue by vshvydky** [zeit/hyper#1858] opened 2017-05-22 08:00 UTC
![image](https://cloud.githubusercontent.com/assets/19645253/26297861/e804f7cc-3ee5-11e7-8a1d-40548e562688.png)
After the update of Windows 10 before the creators update in the terminal there is a constant offset after the line is moved.
-

Hyper 1.3.2
Electron 1.4.16
win32 x64 10.0.15063

**Comment by albinekb** [comment] 2017-05-26 07:11
see https://github.com/Microsoft/vscode/issues/19665
duplicate of #1790

**Closed by albinekb** 2017-05-26 07:11 UTC
