### ISSUE TITLE
https://hyper.is/ linux download url not working

### ISSUE THREAD

**Issue by ciroreed** [zeit/hyper#855] opened 2016-10-11 15:37 UTC
https://hyper-updates.now.sh/download/linux

:(

**Comment by rakeen** [comment] 2016-10-11 15:40
Download it from [github](https://github.com/zeit/hyper/releases)

**Comment by CodeTheory** [comment] 2016-10-11 15:53
_Please_ use the search bar. We've had multiple duplicates of this very recently.

Duplicate of #799.

**Closed by CodeTheory** 2016-10-11 15:53 UTC
