### ISSUE TITLE
Alt issues

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#213] opened 2016-07-17 21:19 UTC
To continue the now closed PR https://github.com/zeit/hyperterm/pull/201
We might have introduced a regression with alt handling.

> On german layout, ~ doesnt show up for alt/opt + n. i can hack it there while typing alt + shift + n and deleting the unicodes before the ~.

cc @patrickhaug @marcbachmann @teemuteemu

**Comment by nfcampos** [comment] 2016-07-17 21:55
another alt behaviour still not resolved is alt + arrow to move between word boundaries

**Comment by marcbachmann** [comment] 2016-07-17 22:41
Umlauts are also still a problem. (ALT + u ... u)
Here's how iTerm handles them. I have no idea how hterm manages to swallow those inputs.
![umlauts](https://cloud.githubusercontent.com/assets/431376/16903472/6e5e2b36-4c7f-11e6-80de-411d93ffcb73.gif)

**Comment by nfcampos** [comment] 2016-07-17 23:17
@marcbachmann can you check if #214 fixes that for you?

**Comment by unluisco** [comment] 2016-07-18 01:52
other is alt + ñ to get: ~
I'm latin american, so I use the letter Ñ to get ~

**Comment by mxstbr** [comment] 2016-07-18 07:03
I can confirm that `ALT + n` on a german keyboard doesn't work to insert ~. Typing Umlauts directly (in this case ü) ends in this:

![screen shot 2016-07-18 at 09 02 43](https://cloud.githubusercontent.com/assets/7525670/16907759/745683ca-4cc6-11e6-8b88-077d14618c66.png)

**Comment by petetnt** [comment] 2016-07-18 07:43
Heh, same issue with finnish keyboard layout and tildes, where `~` comes from `alt+¨` (the key with `^` as `shift+key`).

**Comment by michaeljosephrosenthal** [comment] 2016-07-18 10:47
Broke `alt+` behavior for `;, h, j, k, z` for me, so I reinstalled `0.5.0`. Would be very good if rolling back an update was as seamless as installing one

**Comment by marcbachmann** [comment] 2016-07-18 10:56
> Broke alt+ behavior for ;, h, j, k, z for me, so I reinstalled 0.5.0. Would be very good if rolling back an update was as seamless as installing one

What's the expected behavior?

**Comment by michaeljosephrosenthal** [comment] 2016-07-18 11:04
@marcbachmann they were mapped to various commands in `tmux`. `alt+;` = command line, `alt+hjkl` = pane switching, and `alt+z` = prefix

**Comment by mxstbr** [comment] 2016-07-18 12:56
To elaborate, `~` wasn't working in 0.5 for me either, not sure about umlauts!

**Comment by suitupalex** [comment] 2016-07-18 15:37
I'd also like to add that `alt+1` or any of the layout command variants (2-5 and space) are also not being registered.

**Comment by Vistur** [comment] 2016-07-25 06:55
Same issue with spanish keyboard: `alt + ñ` != `~`

**Comment by kasperlewau** [comment] 2016-07-28 07:14
Same deal for Swedish & Danish layouts on early 2015 MBP's. `alt` does not want to play ball.

**Comment by deepsweet** [comment] 2016-07-28 12:21
having this in tmux config works fine in iTerm but not in Hyperterm:

```
# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
```

**Comment by benoitzohar** [comment] 2016-07-29 07:12
Same issue with french keyboard:   alt + n != ~

This is a deal breaker for me :/

(in version 0.7.1)

**Comment by whitelynx** [comment] 2016-08-19 01:11
I think part of the problem has to do with how legacy terminals were implemented, and what capabilities a modern terminal emulator needs to... well, emulate. 😛 

As mentioned [in the XTerm Control Sequences documentation](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Alt-and-Meta-Keys), the "Alt" key is often used to emulate the "Meta" key that is missing from most modern machines.
- On older 8-bit ASCII terminals, [Alt would set the highest bit in the generated byte](https://en.wikipedia.org/wiki/Alt_key#Evolution), allowing you to generate characters with ASCII codes in the 128-255 range, instead of the 0-127 range. (this is rather similar to Mac OS X's behavior of [allowing you to type a different set of characters when holding Option/Alt](https://en.wikipedia.org/wiki/Alt_key#Mac_OS_X), and similar to [the "AltGr" key on international keyboards](https://en.wikipedia.org/wiki/AltGr_key))
- Other terminals instead prefix each character with an Esc character (`^[`) when Alt is held down.

One big reason for terminals _not_ to interpret Alt+character sequences as alternate characters (AltGr behavior) is so that keyboard shortcuts using the Alt key can be bound in terminal programs. (see [this article on the Vim wiki for several examples, and more information on the problem](http://vim.wikia.com/wiki/Get_Alt_key_to_work_in_terminal)) On the other hand, that makes things more difficult for international users who rely on the ability to type certain characters with AltGr-style behavior.

If you're interested, I've collected some (currently rather incomplete) information about how various terminals handle different key combinations, and [shared it in this spreadsheet](https://docs.google.com/spreadsheets/d/1E1tH3j6hY65Q4-yu0ZY7AR6igLxuQWwlOLHMbkUhwb0/edit?usp=sharing). I'm planning on moving the data into a database, and having a terminal program that will ask the user to press certain keys in order to fill out information for different terminals.

----

It seems to me that the most sensible route for a terminal app to take is to provide user-configurable key bindings. (I've already wanted this in hyperterm, since I'm primarily a PC user, but now having to work in Mac OS X is driving my muscle memory insane; I'd _really_ like to remap some of the standard bindings hyperterm provides) I started working on a plugin to allow this, but so far I haven't had much luck even duplicating the built-in keybindings. If I get it working, I'll push it to GitHub and announce it here.

**Comment by beane** [comment] 2016-08-31 04:35
I tend to use `alt`+`b` to navigate backwards between words, which in HyperTerm produces a funky `∫` character. I had the same issue when configuring iTerm, which was solved thanks to the option to map `alt` to `+Esc`. Would love to see that option in HyperTerm!

**Comment by beane** [comment] 2016-08-31 05:30
**Update:** Just discovered how to bind `Alt-b` and `Alt-d` on OS X (and probably other Linux machines as well).

I added the following lines to my `~/.inputrc`:
```
# `Alt-b` to nav back a word
"\xe2\x88\xab":"\eb"
# `Alt-d` to deleted back a word
"\xe2\x88\x82":"\ed"
```

You can also write
```
$ bind '"\xe2\x88\xab"':'"\eb"'
$ bind '"\xe2\x88\x82"':'"\ed"'
```
to temporarily have those bindings in any given session.

Helpful [SO answer](http://stackoverflow.com/a/4201274)
[Script](https://gist.github.com/beane/40a1a355bf221e426dcd3210969b4e50) for finding what characters you need for binding from a surprisingly useful [random 2005 internet page](http://ps-ax.org/docs/tech/Bash_bind.htm)

I think this will probably work on any terminal you're using, which is kind of cool, but it would still would be awesome to have a configurable option HypterTerm!

**Comment by whitelynx** [comment] 2016-09-11 16:42
@beane That will work for bash, but not for some other shells or terminal apps. For instance, in fish, you'd have to use [its `bind` command](http://fishshell.com/docs/current/commands.html#bind) (which has a different syntax than readline's `bind`), and in Vim, you'd probably want to use [`CTRL-V` in insert mode](http://vimdoc.sourceforge.net/htmldoc/insert.html#i_CTRL-V) to get the right bindings. [Screen](https://www.gnu.org/software/screen/manual/html_node/Bindkey.html#Bindkey) and [tmux](http://man.openbsd.org/OpenBSD-current/man1/tmux.1) (and therefore Byobu) use the `bind-key` command in their configs.

It'd still be easiest if HyperTerm had a way to configure its keybindings so we could set it up to produce keycodes that are expected by most terminal apps, instead of having to configure each one separately.

**Comment by molovo** [comment] 2016-09-26 20:25
I have `alt + shift + left/right` mapped to switch windows in tmux, and this doesn't work in Hyperterm (but does in Terminal.app and iTerm). `alt + left/right` to move between words *does* work though, so it's the `shift` modifier that breaks it.

@whitelynx +1 for configurable keybindings. Will resolve a lot of these issues fairly easily.

**Comment by aharris88** [comment] 2016-09-26 21:57
I think #686 will fix this issue.

**Comment by molovo** [comment] 2016-09-27 08:07
@aharris88 You're right, I think it will. Thanks

**Comment by flybayer** [comment] 2016-10-04 21:36
Can this be closed now?

**Comment by aharris88** [comment] 2016-10-05 00:07
I believe so. It works for me.

**Comment by ekmartin** [comment] 2016-10-05 01:25
#686 doesn't fix the tilde problem though, right?

**Comment by aharris88** [comment] 2016-10-05 02:37
I don't think so, but maybe #761 did.

**Comment by kevinSuttle** [comment] 2016-11-03 14:57
I noticed <kbd>⌃</kbd><kbd>⌥</kbd><kbd>⇥</kbd> doesn't select panes, either, with or without <kbd>⇪</kbd>.

**Comment by k1sul1** [comment] 2016-11-23 08:57
Neither <kbd>~</kbd> or <kbd>^</kbd> work for me on MacOS Sierra. Finnish keyboard layout. 

Combination for <kbd>~</kbd> is <kbd>alt</kbd> + <kbd>^</kbd>, and combination for <kbd>^</kbd> is  <kbd>shift</kbd> + <kbd>^</kbd>.

Considering that shift and alt keys work just fine for other characters, I think this is an issue with the <kbd>^</kbd> key. 

I can type capital letters and <kbd>@</kbd> just fine for example. On MacOS <kbd>@</kbd> is generated by pressing <kbd>alt</kbd> + <kbd>2</kbd>

Picture of the keyboard for clarity: 

![keyboard](http://i.imgur.com/bsE8FlE.jpg)

Is there a proper workaround for this? I've been able to cope without ~ by using $HOME (pretty cumbersome but no pain, no gain), and I've somehow managed to survive in Vim without the <kbd>^</kbd> key, even if switching files between is not efficient.

**Comment by rauchg** [comment] 2016-11-23 17:08
This is already being addressed @k1sul1. Soon you'll get an update with the fix!

**Comment by winneon** [comment] 2016-11-23 21:54
I'll be looking forward to that myself! I've been trying to use Hyper as my main terminal lately, but some of the small kinks like alt / option not acting as a meta key are really making life difficult.

**Comment by matheuss** [comment] 2016-11-30 19:56
Closing since it was fixed via #1006 🙌

**Closed by matheuss** 2016-11-30 19:56 UTC

**Comment by iamjwc** [comment] 2017-01-06 16:03
After the fix, I'm still having issues with navigating forward and backward by word boundaries. I added one more rule to @beane's suggestion of using `~/.inputrc` to get moving forward by word boundaries working:

```
# `Alt-b` to nav back a word
"\xe2\x88\xab":"\eb"
# `Alt-d` to delete back a word
"\xe2\x88\x82":"\ed"
# `Alt-f` to nav forward a word
"\xc6\x92":"\ef"
```

**Comment by nwshane** [comment] 2017-01-09 17:46
@deepsweet Did you discover a workaround to enable using the alt-key for tmux shortcuts in Hyper? I'm having this problem as well.

I use Alt-h/j/k/l to move between tmux panes, and I'm not able to use those shortcuts in Hyper, which makes it unusable for me. If anyone has advice on how to fix this issue, it'd be much appreciated.

**Comment by flybayer** [comment] 2017-01-11 23:22
@nwshane Alt-h/j/k/l is working for me to switch tmux panes with `modifierKeys: { altIsMeta: true }` in `.hyper.js` and [this tmux config](https://github.com/flybayer/dotfiles/blob/master/tmux.conf).

**Comment by beane** [comment] 2017-01-12 22:41
Is anybody else still having issues with `alt-b` or `alt-f`? They still produce `∫` and `ƒ` respectively.

Setting `modifierKeys: { altIsMeta: true }` didn't help.

The relevant iTerm config lets your map `alt`to `+Esc` (whatever that means -- it seems to function like `Meta` and also `Esc`).

<img width="391" alt="screen shot 2017-01-12 at 2 39 50 pm" src="https://cloud.githubusercontent.com/assets/3802588/21911309/20ec601a-d8d5-11e6-9375-1c1bd7fdb656.png">

**Comment by whitelynx** [comment] 2017-01-12 23:06
@beane: "+Esc" means that for example pressing Option+F will send Esc+f, or `^[f`. This is probably what most people who use virtual terminals in X11 are used to. The "Meta" option should produce the Meta emulation behavior I described above (setting the 8th bit in the produced characters), and "Normal" should give you the standard MacOS behavior of typing extended characters.

**Comment by beane** [comment] 2017-01-13 21:51
@whitelynx good to know! I just want hyper to let me configure that 😭

**Comment by cbrwizard** [comment] 2017-05-08 13:22
Putting `modifierKeys: { altIsMeta: true }` in `.hyper.js` helped make Alt work in neovim on my Mac, thanks!

**Comment by sebm** [comment] 2017-11-16 00:33
This appears to have been reintroduced as of at least 2.1.1.

**Comment by flybayer** [comment] 2017-11-16 15:26
Yes @sebm, I'm unable to use alt key bindings in Neovim.

**Comment by saamalik** [comment] 2017-12-30 21:22
Does anyone know how to get `alt+.` to paste the last argument from the previous command? I tried `modifierKeys: { altIsMeta: true }` but this didn't work.

**Comment by olealgoritme** [comment] 2019-11-20 16:33
altIsMeta: true 
vim: alt + arrow keys NOT working
