### ISSUE TITLE
Cutoff text with overflowing chars…

### ISSUE THREAD

**Issue by hedefalk** [zeit/hyper#1434] opened 2017-01-20 13:20 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [-] "I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate" - I have searched and do believe but it's pretty hard since there are 427 open issues…

- **OS version and name**: OSX latest
- **Hyper.app version**: 1.1.0.1408
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/hedefalk/c1d4303baf4f3acaebe680df58eb4f0e

## Issue
I get weird cut-off text at the bottom row when I have used some special characters for git status in zsh:

![screen shot 2017-01-20 at 14 19 27](https://cloud.githubusercontent.com/assets/116520/22150816/7ad31e10-df1b-11e6-80c9-613ed722c0f4.png)

I'm pretty sure the reason is some pixel calculation that gets messed up because of the topmost arrow pushing everything down, right?

**Comment by CodeTheory** [comment] 2017-02-03 03:32
Hi there! This is a duplicate of #628. Please contribute to that issue instead.

**Closed by CodeTheory** 2017-02-03 03:32 UTC
