### ISSUE TITLE
Hyper fails to install correctly if homedir contains symlink

### ISSUE THREAD

**Issue by PoisonousJohn** [zeit/hyper#1944] opened 2017-06-17 14:59 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Enterprise Version 1703
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: doesn't exist
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: wasn't able to collect since can't launch app
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
Got an error during installation:
![image](https://user-images.githubusercontent.com/1488281/27253900-0340a8e2-5386-11e7-8c95-646fbe966f3b.png)
And can't launch an app. My .bash_profile is a symlink to .bashrc, created in windows bash. And if I rename it, error occurs again.

If I remove symlink, everything works fine.

**Comment by cerebrate** [comment] 2017-06-27 20:13
Should be fixed by pull #1960.

**Comment by colbin8r** [comment] 2017-07-11 19:36
I use WSL and I have a symlink from in my `%userprofile%` to the WSL `$HOME` so I can move files in easily.  I get an error just like @IvanFateev has, except it breaks on the symlink.

**Comment by Stanzilla** [comment] 2018-04-23 02:15
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Closed by Stanzilla** 2018-04-23 02:15 UTC

**Comment by thedonquixotic** [comment] 2018-07-17 21:56
I am having the same problem as this person. I will open a new issue for it.

**Comment by thedonquixotic** [comment] 2018-07-19 10:59
I have opened a new issue for it, uninstalled everything and reinstalled everything and I can confirm that the issue is the symlink. The issue can be found here: https://github.com/zeit/hyper/issues/3132

@Stanzilla 

@colbin8r  you guys find any solutions for this thing?
