### ISSUE TITLE
Opening file preferences asks me to open the .js file locally

### ISSUE THREAD

**Issue by angelsix** [zeit/hyper#1986] opened 2017-07-09 12:14 UTC
Latest Hyper from website, open on Windows machine. Menu -> Edit -> Preferences ... pops up with the windows file execute dialog with Windows Script Engine as the top result. Clicking ok then tries to execute the javascript file on the machine with an error:

---------------------------
Windows Script Host
---------------------------
Script:	C:\Users\conta\.hyper.js
Line:	5
Char:	1
Error:	'module' is undefined
Code:	800A1391
Source: 	Microsoft JScript runtime error

---------------------------
OK   
---------------------------

-

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by LucaT1** [comment] 2017-07-09 13:33
The fix for this is already in master. Will be solved on next release. Duplicate of #1812

**Closed** 2017-08-18 04:18 UTC
Labels: Is Duplicate
