### ISSUE TITLE
Windows encoding issue

### ISSUE THREAD

**Issue by n-chardon** [zeit/hyper#1364] opened 2017-01-09 10:21 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 8.1 
- **Hyper.app version**: 1.0.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
On Windows 8.1 with FR-fr locale, encoding in incorrect : 
![2017-01-09 11_18_03-hyper](https://cloud.githubusercontent.com/assets/14290657/21763312/9885f94e-d65d-11e6-982f-0b27ddf77c58.png)

**Comment by drdaeman** [comment] 2017-05-14 13:41
This is probably a duplicate of #528.

**Comment by Stanzilla** [comment] 2018-04-24 00:11
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Closed by Stanzilla** 2018-04-24 00:11 UTC
