### ISSUE TITLE
Line at the bottom of the terminal is not aligned properly

### ISSUE THREAD

**Issue by tleunen** [zeit/hyper#628] opened 2016-08-17 15:08 UTC
The last line of my terminal is sometimes "cut", like we don't see the bottom of some characters like (`q` or `p`).
<img width="128" alt="screen shot 2016-08-17 at 11 02 04 am" src="https://cloud.githubusercontent.com/assets/1972567/17741546/9af09e42-646a-11e6-8298-63ab8d998e75.png">

It's not always the case in all my terminal windows, maybe it's related when the terminal has tabs. Will try to find better repro.

**Comment by jamox** [comment] 2016-08-18 17:01
That's even worse than what I'm seeing (in #373)

**Comment by jairtrejo** [comment] 2016-08-31 05:02
Hello! Just wanted to report the same problem, it happens to me with powerline for tmux (pretty bad)
<img width="813" alt="screenshot 2016-08-30 10 41 55" src="https://cloud.githubusercontent.com/assets/210225/18116527/587d0526-6efd-11e6-996c-6b72d2bf8df4.png">
or with just tmux (not as bad, but still misaligned):
<img width="773" alt="screenshot 2016-08-30 22 00 35" src="https://cloud.githubusercontent.com/assets/210225/18116534/630ffe6c-6efd-11e6-9c29-5fa585774253.png">

**Comment by fingermark** [comment] 2016-09-26 19:22
Can confirm that this happens with "Times New Roman" as well.  The only fix I found was to adjust the line-height, as suggested by @davegomez in my "duplicate" ticket.

```
termCSS: 'x-row {line-height: 1}',
```

**Comment by jamox** [comment] 2016-09-26 19:39
Awesome, I can confirm that it fixed it for me!

**Comment by tleunen** [comment] 2016-10-08 20:32
Tested with the recent 0.8.1 version and still have the issue.
<img width="220" alt="screen shot 2016-10-08 at 4 29 40 pm" src="https://cloud.githubusercontent.com/assets/1972567/19215746/72257446-8d74-11e6-991c-367a7eaf7e7b.png">

```
fontSize: 12,
fontFamily: 'Menlo, "DejaVu Sans Mono", "Lucida Console", monospace',
```

And I also confirm that changing the line-height fixes the issue.

**Comment by davegomez** [comment] 2016-10-08 20:45
I can't reproduce the issue @tleunen. Have you tried disabling your extensions in case you are using one or maybe tweaking you configuration (using the default one), etc?

I have tried different fonts (even the ones you mention) and  themes but nothing.

**Comment by tleunen** [comment] 2016-10-08 20:53
It's not an issue that occurs 100% of the time :/ Maybe 3 times of 5 I'd say.

I believe I'm using the default config:
<details>
```
module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 12,

    // font family with optional fallbacks
    fontFamily: 'Menlo, "DejaVu Sans Mono", "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.75)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BLOCK',

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: 'rgba(0, 0, 0, 0.75)',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    shell: '',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyperterm.org/#cfg
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: [],

  // in development, you can create a directory under
  // `~/.hyperterm_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
};
```
</details>

**Comment by unicolet** [comment] 2016-10-19 06:55
on a fresh install (only changed the shell to tmux) I see the same issue. The `termCSS` fix above did it for me.

os: ubuntu 16.04 LTS

**Comment by yock** [comment] 2016-10-27 15:02
The `termCSS` setting did not fix this issue for me.

![screenshot 2016-10-27 10 33 32](https://cloud.githubusercontent.com/assets/306343/19771467/08761480-9c31-11e6-835e-89c9d811a7cc.png)

I've narrowed it down to a single character in my prompt:

`ツ`

I'm using a `zstyle` prompt theme by Nadav Shatz called "Smiley" which uses the katakana character to indicate that the previous command exited with a status of zero. Non-zero return codes (errors) are indicated on the prompt with the heavy multiplication sign `✖`.

I'd imagine there are more than just katakana which would cause this, and it might even depend on the font configuration as well. Here's my Hyper configuration for good measure.

```
module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 14,

    // font family with optional fallbacks
    fontFamily: 'Cousine, Menlo, "DejaVu Sans Mono", "Lucida Console", monospace',

    // terminal cursor background color (hex)
    cursorColor: '#F81CE5',

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // some color overrides. see http://bit.ly/29k1iU2 for
    // the full list
    colors: [
      '#000000',
      '#ff0000',
      '#33ff00',
      '#ffff00',
      '#0066ff',
      '#cc00ff',
      '#00ffff',
      '#d0d0d0',
      '#808080',
      '#ff0000',
      '#33ff00',
      '#ffff00',
      '#0066ff',
      '#cc00ff',
      '#00ffff',
      '#ffffff'
    ]
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: [
    'hyperterm-solarized-light'
  ],

  // in development, you can create a directory under
  // `~/.hyperterm_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
};
```

**Comment by jsatk** [comment] 2016-10-28 01:08
this cuts off my tmux status bar by about 1/3/

**Comment by borisrorsvort** [comment] 2016-10-28 08:36
Same here you're supposed to see 2 underscore here. They are hidden
Version 0.7.1 (0.7.1.36)
![screenshot 2016-10-28 10 31 53](https://cloud.githubusercontent.com/assets/39081/19800003/e8de9e0c-9cf9-11e6-88af-cdbbf2536d01.png)

**Comment by davegomez** [comment] 2016-10-28 10:49
Can you guys provide steps to reproduce it? I couldn't so far.

**Comment by yock** [comment] 2016-10-28 12:21
Try adding the katakana character to your command prompt. @davegomez

**Comment by borisrorsvort** [comment] 2016-10-28 12:24
@davegomez for me it's all the time. Though I just tried `termCSS: 'x-row {line-height: 1}'` and this fixes the problem

**Comment by jimgraham** [comment] 2016-10-30 22:54
I get this when I use `Consolas` as my font.

**Comment by robertboloc** [comment] 2016-12-15 09:07
In my case this seems to be caused by the CSS `overflow: hidden` being applied to the last line. This only happens why I set my font to "Ubuntu Mono" so I suspect it's something that only happens with certain fonts.

Thanks

**Comment by shreyasminocha** [comment] 2017-01-09 07:26
I am facing the same issue on Version 1.0.1 (1.0.1.1369). I'm running zsh with only the `hyperterm-material` plugin. My case is similar to that of @borisrorsvort. I'll try the hack he suggested.

**Comment by aersoares81** [comment] 2017-03-21 18:36
Hi, have you tried adding `padding: '12px 14px 18px 14px'` to the` ~/.hyper.js`? It helped me

**Comment by szachara** [comment] 2017-04-19 05:08
Steps to reproduce, If I change font-size to 14px and font-family is fontFamily: '"Lucida Console", monospace',, so the font on the last screen line is cutted, similar with Inconsolata for Powerline font. I think the problem will be that the height is not recomputed right.

**Comment by chabou** [comment] 2017-04-19 07:48
Will maybe resolved by #1745

**Comment by chabou** [comment] 2017-04-19 20:07
@szachara 
I can't reproduce, can you give more details about your configuration (shell, OS, hyper version etc...)

**Comment by chabou** [comment] 2017-04-19 20:45
@szachara Can you try to reproduce on master? #1745 has been merged into it

**Comment by szachara** [comment] 2017-04-21 12:30
I tried with master and still cutted @chabou 

Try your self with `fontFamily: '"Lucida Console", monospace'` and font-size 14px, the x-row heigh or line-height is too low compared to `Menlo` font.

**Comment by MartyGentillon** [comment] 2017-04-24 22:09
@szachara What os are you using?

**Comment by szachara** [comment] 2017-04-25 06:08
NodeJS: 7.8.0
Hyper: 1.3.1
OS: Windows 10

**Comment by mihaliak** [comment] 2017-05-18 13:16
Same problem here with fresh install just changed font settings`Inconsolata For Powerline` font and `14px` fontSize.

NodeJS: v7.10.0
Hyper: Version 1.3.3 (1.3.3.1754)
OS: MacOS Sierra 10.12.5

**Comment by mojoaxel** [comment] 2017-06-05 13:20
I have the same problem with 1.3.3:
![image](https://cloud.githubusercontent.com/assets/600565/26785144/4964592e-4a01-11e7-8741-c3daa43bb274.png)
As you can see the underscore is hidden.

**Comment by jamo** [comment] 2017-06-05 13:27
This: ```termCSS: 'x-row {line-height: 1}'``` in `~/.hyper.js` used to fix it a while back

**Closed** 2017-06-16 07:58 UTC
Labels: Can't Reproduce, Status: Help Wanted, Type: Bug
