### ISSUE TITLE
Alt+enter to toggle fullscreen

### ISSUE THREAD

**Issue by borela** [zeit/hyper#2977] opened 2018-05-04 18:25 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/borela/8793f0bb6f18fdb1c54002488134fe28
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
By default, most apps on windows use `alt+enter` to toggle fullscreen but hyper is using F11, how can I change it? I tried:

```
  keymaps: {
    "window:toggleFullScreen": "alt+enter"
  },

**Comment by chabou** [comment] 2018-05-04 18:29
Did you try with other keys?
Is it `alt+enter` combination that doesn't work? or action remapping?

**Comment by borela** [comment] 2018-05-05 11:43
Any key combined with `alt` alone does not work, you can try `alt+a`, `alt+b`...

**Comment by rfgamaral** [comment] 2018-05-09 11:46
I'm afraid that's not quite true. I mean, I'm having the same exact issue as described in the OP, but this works just fine:

```
keymaps: {
    'window:devtools': 'alt+enter'
  },
```

I'm guessing the issue is on the `window:toggleFullScreen` rebind, I can't get it work with any binding besides `f11`.

**Comment by chabou** [comment] 2018-05-09 13:31
@rfgamaral Hahahah found the bug (Fixed in #2995)... Thank you for your valuable feedback 🙏

**Comment by rfgamaral** [comment] 2018-05-09 13:43
No problem, that's why open-source was invented 😃

**Closed** 2018-05-09 13:51 UTC

**Comment by borela** [comment] 2018-05-09 15:43
Thank you @chabou  :D
