### ISSUE TITLE
Drag the file/folder to get the path does not work after update

### ISSUE THREAD

**Issue by OrdinaryWitch** [zeit/hyper#3642] opened 2019-05-09 10:03 UTC
- [ ] Your Hyper.app version is **3.0.0**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

 - **Hyper version**: undefined "3.0.0"

 - **OS ARCH VERSION:** darwin x64 17.7.0
 - **Electron:** 3.1.3  **LANG:** undefined
 - **SHELL:** /bin/bash   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true
}

          {
  "plugins": [],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by stromcon** [comment] 2019-05-09 10:34
Please check open issues, 3 post before yours there is it : https://github.com/zeit/hyper/issues/3637

**Comment by skllcrn** [comment] 2019-05-09 13:15
Duplicate of #3582

**Closed** 2019-07-03 13:24 UTC
