### ISSUE TITLE
Not showing scroll bar 

### ISSUE THREAD

**Issue by ansarirahilJP** [zeit/hyper#1654] opened 2017-03-14 07:04 UTC
Whenever i need to check previous data on console i could not find scroll bar to scroll up I'm using hyper on Windows 8.1 64bit 

Hyper 1.2.1
Electron 1.4.7
win32 x64 6.2.9200

**Comment by cg-cnu** [comment] 2017-03-14 11:21
@ansarirahilJP Its working fine on centos 7 with hyper 1.3.1.
Can you try the latest release?

**Comment by MartyGentillon** [comment] 2017-04-15 08:02
This is a duplicate of https://github.com/zeit/hyper/issues/1540

**Comment by ppot** [comment] 2017-04-15 22:49
Closing for #1540

**Closed by ppot** 2017-04-15 22:49 UTC
Labels: Is Duplicate
