### ISSUE TITLE
Text overlap

### ISSUE THREAD

**Issue by FAKER-A** [zeit/hyper#2119] opened 2017-08-25 09:54 UTC
-

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

![image](https://user-images.githubusercontent.com/25676164/29709307-68f3afe0-89be-11e7-864c-1179a4f5b2e9.png)

**Comment by OmgImAlexis** [comment] 2017-08-31 02:26
Duplicate of https://github.com/zeit/hyper/issues/283

**Comment by CodeTheory** [comment] 2017-08-31 13:32
Thanks @OmgImAlexis. Closing in favour of #283.

**Closed by CodeTheory** 2017-08-31 13:32 UTC
