### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by hyper2321** [zeit/hyper#3286] opened 2018-11-12 08:48 UTC
Whenever I try to install a new theme, it says "<theme> is already installed". 

How can I change the theme?

Thanks

**Comment by heewa** [comment] 2018-12-20 18:39
Looks like a dupe of #2942. Looks like for now you need to edit your config (`.hyper.js`) to remove or comment out all the themes (listed as plugins) except the one you want to use.

**Closed** 2019-10-10 19:55 UTC
