### ISSUE TITLE
Unable to launch Hyper 1.4.3.88

### ISSUE THREAD

**Issue by thomas-alrek** [zeit/hyper#2169] opened 2017-09-04 12:51 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.16
- **Hyper.app version**: 1.4.3.88
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [https://gist.github.com/thomas-alrek/c13821656b9a55ecbef310be336b8446](https://gist.github.com/thomas-alrek/c13821656b9a55ecbef310be336b8446)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: Unable to open devtools
- **The issue is reproducible in vanilla Hyper.app**: I have not been able to test this

## Issue

When launching Hyper,  no windows er created. The only menu item is Quit.

If you launch the app from macOS default Terminal, this info is written to stdout/stderror:

```
/Applications/Hyper.app/Contents/MacOS/Hyper 
Plugin hyperterm-alternatescroll (1.3.0) loaded.
Plugin hyperterm-lastpass (1.0.1) loaded.
Plugin hyperlinks (0.5.0) loaded.
Plugin hyper-statusline (1.7.3) loaded.
Plugin hyper-alt-click (0.1.1) loaded.
Plugin hyper-material-theme (2.0.5) loaded.
hypercwd: no config file found at ~/.hypercwdrc.json
Plugin hypercwd (1.1.0) loaded.
running in prod mode
electron will open file:///Applications/Hyper.app/Contents/Resources/app.asar/index.html
Error while loading devtools extensions TypeError: Cannot read property 'theme' of undefined
    at Object.exports.decorateConfig.config [as decorateConfig] (/Users/thomasalrek/.hyper_plugins/node_modules/hyper-material-theme/index.js:17:18)
    at modules.forEach.plugin (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:286:30)
    at Array.forEach (native)
    at decorateObject (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:284:11)
    at Object.exports.getDecoratedConfig (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:317:10)
    at createWindow (/Applications/Hyper.app/Contents/Resources/app.asar/index.js:105:25)
    at installDevExtensions.then (/Applications/Hyper.app/Contents/Resources/app.asar/index.js:161:3)
    at <anonymous>
```

**Comment by CodeTheory** [comment] 2017-09-04 12:53
This looks like an issue for `hyper-material-theme` 🤔 

Perhaps removing that from Hyper will make it work so I'm not sure we can fix it 😅

**Comment by chabou** [comment] 2017-09-04 12:57
Duplicate of #2080

**Closed** 2017-09-04 12:57 UTC
