### ISSUE TITLE
Context menu is showing Hyper but trows an error when clicked

### ISSUE THREAD

**Issue by lednhatkhanh** [zeit/hyper#1165] opened 2016-12-13 06:59 UTC
This issue's related to this: #1133 

I'm facing this issue on windows 10 when I build the app from source (latest commit, master).

But, after removing and reinstall using the .exe file downloaded from [here](https://hyper.is/#installation), it started working fine.

Nodejs: 7.2.1 64 bit
Windows 10 64bit.

Note that this also happends with GritKraken (another Electron app), so I think that there should be some problems with Electron or something. Vscode's still working fine tho.

**Comment by kilianso** [comment] 2016-12-13 07:42
Step 1 : Type "regedit" in start menu

Step 2 : Run the registry editor

Step 3 : Navigate to HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\Background\shell\Hyper\command

Step 4 : Right-click on "REG_SZ" entry and choose modify

Step 5: Enter the Path to Hyper, like: C:\Users\username\AppData\Local\app-1.0.0\Hyper.exe

Unfortunately Hyper doesn't navigate directly to the "open here" directory. This should be fixed too.

**Comment by Specro** [comment] 2016-12-13 14:13
@lednhatkhanh Hyper adds/removes the context menu entry only during install/uninstall. That's why your entry may have been broken.

@kilianso I can't seem to reproduce this. Is this on Windows 10? Could you share your config?

**Comment by nsna** [comment] 2016-12-14 12:13
@kilianso opening in the current directory can be fixed by adding "%V" as an argument in the command key:
`"C:\Users\<username>\AppData\Local\hyper\app-1.0.0\Hyper.exe" "%V"`

You can also change the text that is displayed in the context menu by adding a value to the parent Hyper key such as "Open Hyper Here".

Windows reg export:

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\Hyper]
@="Open Hyper Here"

[HKEY_CLASSES_ROOT\Directory\Background\shell\Hyper\command]
@="\"C:\\Users\\Astreaz\\AppData\\Local\\hyper\\app-1.0.0\\Hyper.exe\" \"%V\""
```

**Comment by shanselman** [comment] 2017-03-12 05:10
I just hit this also. The default reg key is getting erased on update. Perhaps something wrong with the squirell update?

**Comment by EsSpricht** [comment] 2017-07-18 12:12
Somehow the command: "C:\Users\<username>\AppData\Local\hyper\app-1.0.0\Hyper.exe" "%V" was not working for me. Hyper showed up but not at the correct path. 

So I changed it to: 
C:\Users\xxx\AppData\Local\hyper\Hyper.exe  --process-start-args="-p %V"

**Comment by djalmajr** [comment] 2017-08-02 15:16
@EsSpricht's solution works for me

**Comment by Stanzilla** [comment] 2018-04-24 00:14
Fix by https://github.com/zeit/hyper/pull/1831

**Closed by Stanzilla** 2018-04-24 00:14 UTC
Labels: 🖼 Platform: Windows
