### ISSUE TITLE
auto-scroll terminal on mouse drag

### ISSUE THREAD

**Issue by jonathanmiller** [zeit/hyper#698] opened 2016-09-08 17:55 UTC
Select text in the terminal with a mouse and drag the mouse to the top or bottom of the terminal ( if not already scrolled to the top or bottom, respectively ). My expectation would be for the terminal to automatically scroll in the drag direction so the selection block can include previously off screen text.

Hyperterm does not auto-scroll when the mouse hits the content area edges. I haven't found a configuration flag ( just in case it was disabled by default ) nor any plugin that appears to introduce this functionality.

HyperTerm 0.7.1 on OSX 10.11.6

**Comment by ppot** [comment] 2016-09-17 04:35
Interesting! Il take a look!

**Comment by shawninder** [comment] 2016-11-02 19:32
I noticed this as well. Combined with #820, it seems it is now impossible to select text which overflows the terminal window. I think this fact should increase the priority on this issue as some use-cases become unsupported.

**Comment by yousefissa** [comment] 2017-04-24 19:29
Anyone still having this issue?

**Comment by shawninder** [comment] 2017-04-26 16:22
Yes, I just reproduced this problem with Version 1.3.1 (1.3.1.1628) on macOS Sierra 10.12.3

**Comment by jrhorn424** [comment] 2017-05-11 16:39
Reproduced.

- macOS 10.12.4 (16E195)
- Hyper Version 1.3.2 (1.3.2.1744)

**Comment by RoyHP** [comment] 2017-06-21 13:15
Still has this issue. Considering most people select large amounts of text that overflows the window in their terminal, this is really important if Hyper is going to achieve mass adoption.

- macOS 10.12.5
- Hyper Version 1.3.3 (1.3.3.1754)

**Comment by SmugZombie** [comment] 2017-06-27 20:39
Also experiencing still.

* Windows 10 x64
* Hyper Version 1.3.3 (1.3.3.772)

**Comment by DronePT** [comment] 2017-07-11 00:15
I've found a "temporary" solution that works for me (OSX).

1. Select some text

**Comment by anweiss** [comment] 2017-10-10 14:52
+1 to including this feature

**Comment by kenorb** [comment] 2018-02-21 10:58
Same with Hyper 1.4.8 (stable)

Reproducible steps:

1. Run `seq 1 1000`.
2. Scroll up.
3. Then try to select lines from 1 to 1000. Not possible.

**Comment by jonathanmiller** [comment] 2018-04-27 14:15
This request looks as it has been addressed in hyper@2, at leaast on macOS. thank you!

**Comment by albinekb** [comment] 2018-04-27 20:58
Fixed in v2 👍

**Closed by albinekb** 2018-04-27 20:58 UTC
Labels: help wanted, 🛠 Type: Feature Request
