### ISSUE TITLE
Console freezing with large outputs

### ISSUE THREAD

**Issue by cByst** [zeit/hyper#1062] opened 2016-12-01 03:42 UTC
- OS version and name: macOS Sierra 10.12.1
- Hyper.app version: 0.8.3
- Link of a Gist with the contents of your .hyper.js: https://gist.github.com/cByst/44ad5d6f49de9ace37ebc7f17ce0b922
- Relevent information from devtools (CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere): N/A
- The issue is reproducible in vanilla Hyper.app: Yes

## Issue
When running commands/programs with large console output, hyper begins to print the output in chunks and then becomes unresponsive. This is not the behavior seen in the native mac terminal or other terminal emulators I've used. 

I was abled to reproduce the issue on multiple machines with something as simple as `seq 10000000`

![image](https://cloud.githubusercontent.com/assets/2294736/20781068/bbb866c2-b745-11e6-90ad-e369704e3da3.png)

**Comment by ppot** [comment] 2016-12-01 05:20
@cByst  @matheuss duplicate of #571

**Comment by CodeTheory** [comment] 2016-12-02 22:59
Yup, this is a duplicate of #571.

**Closed by CodeTheory** 2016-12-02 22:59 UTC
