### ISSUE TITLE
"Up" key is not repeating the last command with zsh on Windows

### ISSUE THREAD

**Issue by db2k** [zeit/hyper#1346] opened 2017-01-05 23:30 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Build 14986 released on 16/12/02
- **Hyper.app version**: 1.0.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/db2k/36eac1d677cf36f9f572b5d09a943ceb
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: nothing
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
If I use the *UP*-Key to repeat the last entered command it's not going to put it into the current line. I'm using zsh.

**Comment by ppot** [comment] 2017-01-05 23:31
Closing, duplicate of #1127, thanks!

**Closed by ppot** 2017-01-05 23:31 UTC
Labels: Is Duplicate
