### ISSUE TITLE
Linux Download

### ISSUE THREAD

**Issue by lucaros97** [zeit/hyper#1035] opened 2016-11-23 13:17 UTC
Download link for Linux doesn't work. When you click on it, a new windows display "Version not found: latest" but nothing happen

**Comment by AnwarShahriar** [comment] 2016-11-23 13:21
I'm facing the same problem too :(

**Comment by jamo** [comment] 2016-11-23 13:31
Linux version can be downloaded from: https://github.com/zeit/hyper/releases/latest
The dl link will be fixed soon

**Comment by jamo** [comment] 2016-11-23 13:32
Duplicate of our most duplicated issue: #799

**Closed** 2016-11-23 13:32 UTC
Labels: Is Duplicate
