### ISSUE TITLE
Character padding issue

### ISSUE THREAD

**Issue by ERENKYI** [zeit/hyper#3809] opened 2019-08-30 15:57 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ERENKYI/930a606fd9222156a99079a7fbf16cd3

## Issue
As you can see from the screenshot below, the arrow characters have some sort of space/padding issue. The window below belongs to wsl.exe which doesn't have that problem with the same font.

![wsl_XPNCpN1GZD](https://user-images.githubusercontent.com/29287377/64034782-fe446800-cb57-11e9-93a1-f1b3878b88bc.png)

**Comment by bet4it** [comment] 2019-08-31 03:25
Duplicate of #3617

**Closed** 2019-10-12 15:09 UTC
Labels: 👯‍♀️ Is Duplicate
