### ISSUE TITLE
Text doesn't reflow when window/pane is resized

### ISSUE THREAD

**Issue by ravinggenius** [zeit/hyper#940] opened 2016-10-27 17:55 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.1
- **Hyper.app version**: Version 0.8.3 (0.8.3.873)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ravinggenius/9f253955dcbcaebd1307e89cbe253326
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Printed text doesn't rewrap when window or pane (viewport) is resized (bigger or smaller). When going from a wide viewport to a narrow viewport, existing text that is too wide becomes inaccessible. When going from a narrow viewport to a wide viewport, existing text remains wrapped wherever it was before resizing.

I'm sure maintainers are tired of comparisons to iTerm2, but existing text there is dynamically reflowed whenever a viewport is resized smaller. (Wide text is soft-wrapped.) However existing narrow text is not reflowed when the viewport is widened, unless it was previously soft-wrapped. (This is unfortunate.)

Personally I would like to see all text soft-wrapped and reflowed when windows/panes are resized. To be clear I think text should be soft-wrapped when initially output as well. Then it would reflow correctly when the viewport is widened. At the very least, wide text should not be obscured when the viewport is made smaller.

**Comment by ekmartin** [comment] 2016-10-27 17:57
This is a duplicate of #476 😃

**Closed by ekmartin** 2016-10-27 17:57 UTC
