### ISSUE TITLE
Colon Bug

### ISSUE THREAD

**Issue by tz4678** [zeit/hyper#4398] opened 2020-03-17 22:49 UTC
1)

```zsh
# Edit some file with vim
$ vim /path/to/somefile
```

2) Enter edit mode (`i`) and type colon (`:`)

3) Escape (exit edit mode) doesn't work

 hyper-git-3.1.0.canary.4.r63.g4a3132b8-1

**Comment by bet4it** [comment] 2020-03-18 00:06
Duplicate of #3929

**Closed** 2020-03-18 00:41 UTC
Labels: 👯‍♀️ Is Duplicate
