### ISSUE TITLE
Blank window Ubuntu 18.04

### ISSUE THREAD

**Issue by garyx** [zeit/hyper#2804] opened 2018-04-04 11:17 UTC
- **OS version and name**: Ubuntu 18.04 
- **Hyper.app version**:2.0.0-canary.15
- **The issue is reproducible in vanilla Hyper.app**: Vanilla, no extra themes or plugings. 

## Issue
Hi there, 

I have been testing hyper on a couple of Ubuntu 18.04 machines that I have as well as on 3rd test VM I have. 18.04 is set to release later this month is is overall looking good but 2.0.0-canary.15 is having some draw issues on all machines.  Usually I just get a little text up in the terminal, doing ls on a couple of folders and I start to see a blank window. Usually when I switch focus or move the window or even right click. Happens on all my installed instances and seems to be easily reproducible. 

I cannot see any other open issues on this, hopefully this is not a duplicate. 

my .hyper.js is completely default when this happens, not added any themes/plugins. 

On my work machine running 17.10 I do not have this issue.

**Comment by RyanTheAllmighty** [comment] 2018-04-18 09:41
2.0.0 release no longer shows the black screen for me, but the issue with slowness still persists which seems to be a big issue with 2.0.0 and tracked in #2838

**Comment by lacymorrow** [comment] 2018-04-19 00:52
Have you tried disabling all plugins?

**Comment by garyx** [comment] 2018-04-23 07:40
I have a dual boot with 18.04 on one machine. Started it up and it had canary.15 installed and this behaviour was there. Upgraded 18.04 to latest with around 450 packages updated and rebooted. Started .15 still got it to blank after a few commands. Installed canary.18, same thing. Installed 2.0.0 stable also got it to blank on the window after a few commands. It seemed to be easily reproducible on this machine. and install. Will check my VM later today.

**Comment by garyx** [comment] 2018-04-27 01:09
So I just upgraded to Hyper 2.1.0-canary.1 and this version has no flickering/blank window on my desktop 18.04 that had this issue on 2.0.0. stable. 

I scrubbed the test VM regrettably so can't test that one specifically where I had the issue. 

I set up another clean VM to test and lo and behold. Fresh 18.04 using the new official iso and hyper 2.0.0 stable (no plugins) had blanking issues. Installed 2.1.0-canary.1 and no blanking window anymore.

**Comment by chabou** [comment] 2018-04-27 07:02
@garyx thanks for your feedback
I'm closing this issue.

**Closed by chabou** 2018-04-27 07:02 UTC
Labels: 🐛 Type: Bug, 🐧 Platform: Linux, 🦉 Version: Canary

**Comment by HaykoKoryun** [comment] 2018-05-09 17:25
I had hyper go black after resuming from suspend, running `Hyper 2.1.0-canary.1 (stable)`. I also have the following plugins running:
```
  hypercwd (1.2.3),
  hyperterm-dibdabs (0.0.8),
  hyper-blink (1.1.2),
  hyperterm-cursor (0.0.3),
  hyper-electron-highlighter (4.1.1)
```

Will try and reproduce with no plugins and report back.

**Comment by nicholasnelson** [comment] 2018-07-16 06:33
I was having a similar issue with a fresh install of Hyper on Ubuntu 18.04.

Tried both 2.0.0 and 2.1.0-canary.1, same issue.

Running `hyper -v` gave:

> [4091:0716/155239.931211:ERROR:gl_implementation.cc(246)] Failed to load /opt/Hyper/swiftshader/libGLESv2.so: /opt/Hyper/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory

Searched my / for swiftshader and found this library is included in Chrome, so I did
> sudo cp -r /opt/google/chrome/swiftshader /opt/Hyper/swiftshader

After doing this, I've got Hyper 2.0.0 running with no notable issues. Verbose output of Hyper looks fine, lag is gone, as is the black screen.

**Comment by MarkoCen** [comment] 2018-10-29 22:13
@nicholasnelson Thanks, this is working for me.
And make sure Chrome has been installed, otherwise `/opt/google/chrome/swiftshader` won't be found...
