### ISSUE TITLE
Emojis not displaying correctly.

### ISSUE THREAD

**Issue by winneon** [zeit/hyper#1080] opened 2016-12-04 01:17 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.11.2
- **Hyper.app version**: master branch as of commit [e345ba4](https://github.com/zeit/hyper/commit/e345ba4f6091050991d991594c6fc02d7e534629)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/winneon/a5dc750894bf6b1bc87780392d642c36
- **Relevant information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: ![screenshot](https://i.imgur.com/xrh76EA.png)
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

When inserting or displaying an emoji, the displayed text is instead 6 unidentifiable characters. This is reproducible on both `bash` and `zsh`.

![example](https://i.imgur.com/jRUIfZZ.gif)

**Comment by ppot** [comment] 2016-12-04 01:39
duplicate of #645 @CodeTheory

**Comment by CodeTheory** [comment] 2016-12-04 01:40
Yes, thank you @ppot

**Closed by CodeTheory** 2016-12-04 01:40 UTC
