### ISSUE TITLE
MacOS fullscreen header styling

### ISSUE THREAD

**Issue by jaredramirez** [zeit/hyper#3072] opened 2018-06-07 15:51 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Sierra 10.12.6
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/jaredramirez/3a8366c5da7a392f0ca36a49d5992e14
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: -
- **The issue is reproducible in vanilla Hyper.app**:  Yes

## Issue

This is a styling issue. When I go into fullscreen mode and bring my mouse to the top of the screen to drop the menu bar down, the text from the terminal is visible on the menu bar.

<img width="1280" alt="screen shot 2018-06-07 at 10 43 26" src="https://user-images.githubusercontent.com/8095741/41110958-4b458da2-6a40-11e8-863c-545955d43817.png">
(Top left of photo)

**Comment by timothyis** [comment] 2018-06-07 15:57
This is a duplicate of #5, but thanks for confirming the issue.

**Closed by timothyis** 2018-06-07 15:57 UTC
