### ISSUE TITLE
Border radius

### ISSUE THREAD

**Issue by kodekrendel** [zeit/hyper#1860] opened 2017-05-22 11:56 UTC
Can't set border-radius in Ubuntu.

Tried `borderRadius: '10px'` in `.hyper.js`with no success.

**Comment by albinekb** [comment] 2017-05-26 06:39
Duplicate of #1674

**Closed by albinekb** 2017-05-26 06:39 UTC

**Comment by kodekrendel** [comment] 2017-05-26 08:49
@albinekb how is that duplicate, if that issue is UNSLOVED and CLOSED? Fuckoff hyper.

**Comment by albinekb** [comment] 2017-05-26 08:51
#1674 isn't closed? @kodekrendel 
![image](https://cloud.githubusercontent.com/assets/5027156/26487816/4c58bcf4-4201-11e7-8545-ccd7950cca42.png)
