### ISSUE TITLE
MacOS Accent menu pops when a key is held down

### ISSUE THREAD

**Issue by dusty-stripe** [zeit/hyper#1578] opened 2017-02-23 17:29 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OSX Sierra
- **Hyper.app version**: 1.2.1
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
The MacOS accent bubble pops up intermittently as a key is held down.

![kapture 2017-02-23 at 11 04 16](https://cloud.githubusercontent.com/assets/25311257/23270949/444c8038-f9bb-11e6-8b3e-d74a159a7a46.gif)

**Comment by CodeTheory** [comment] 2017-02-23 17:39
Duplicate of #1337.

**Closed** 2017-02-23 17:39 UTC

**Comment by dusty-stripe** [comment] 2017-02-23 18:26
Ahh... sorry. I searched for "accent pop up". 🤦‍♂️
