### ISSUE TITLE
Drag and drop does not work, in the terminal window anymore

### ISSUE THREAD

**Issue by andrewbaisden** [zeit/hyper#3637] opened 2019-05-08 21:32 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave Version 10.14.4 
- **Hyper.app version**: 3.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/andrewbaisden/e6e01705c8611eb18e916b15bf0da903 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  (re)loading renderer plugins
bundle.js:1 Plugin hyper-material-theme (2.0.7) loaded.
bundle.js:1 Plugin hypercwd (1.2.2) loaded.
bundle.js:1 Plugin hyper-font-ligatures (0.0.6) loaded.
/Users/username…wd/configParse.js:5 hypercwd: no 'config.hypercwd' object found in ~/.hyper.js - see https://github.com/hharnisc/hypercwd#configuration for configuration details 
- **The issue is reproducible in vanilla Hyper.app**: Only tried with add ons

## Issue
Since updating to the latest version 3.0.0 (stable), drag and drop no longer works in the terminal window. It is no longer possible, to drag a folder into the terminal window, which means the ability to quickly change directory is gone. When you drag a folder into the window, it still shows the circle with the plus icon, which means it's allowing you to copy the link over. However when you release it, the link is not added to the terminal window.

**Comment by bzaman** [comment] 2019-05-09 02:35
Exact same things on mine too

**Comment by rikumi** [comment] 2019-05-09 02:37
Same problem here, even with WebGL rendering force-disabled because of window transparency.

**Comment by thibaudalt** [comment] 2019-05-09 06:19
Same here ;(

**Comment by slowtree** [comment] 2019-05-09 08:55
Same here, cannot use drag and drop anymore :(

**Comment by andrewbaisden** [comment] 2019-05-09 12:26
No fix yet, but there is a workaround. 

(CMD+C on macOS, CTRL+C elsewhere): Use that command to copy the folder directory location to your clipboard.
(CMD+V on macOS, CTRL+V elsewhere): Use that command to paste the folder directory location into your terminal window.

I think this action is probably faster than using drag and drop anyway.

**Comment by skllcrn** [comment] 2019-05-09 13:15
Duplicate of #3582

**Comment by xavi-dev** [comment] 2019-05-28 08:38
The fastest way on macOS: **CMD+OPTION+C** This will copy the path of the file.

If you are better with mouse, then right click on the file and press option to see how the "copy file" changes to "copy file as path"

**Closed** 2019-07-03 13:24 UTC

**Comment by TylerBarnes** [comment] 2019-08-01 01:10
So there's a workaround but does anyone know why it stopped working?
It's not very good UX to have to google the problem and read this thread to find a workaround for a behaviour the app used to have.

**Comment by kourindouhime** [comment] 2019-10-03 02:19
it's very convinient to dragndrop files from dock to terminal, please add this feature

**Comment by qweasd1** [comment] 2020-01-11 14:25
guys, I create a plugin for this: https://github.com/qweasd1/hyper-drop-file, just  ```hyper install hyper-drop-file```

**Comment by TylerBarnes** [comment] 2020-01-13 18:08
Amazing, it works!! Thanks @qweasd1 ! I missed this feature

**Comment by bzaman** [comment] 2020-01-14 05:39
Thanks @qweasd1 . It just works!!!. Great

**Comment by jeankvd** [comment] 2020-01-20 20:34
@skllcrn why was this issue closed? drag and drop still doesn't work

**Comment by jaronschulz** [comment] 2020-01-29 10:09
thank you

**Comment by andrewbaisden** [comment] 2020-01-29 12:26
Thanks @qweasd1 i wish we had this solution sooner.

**Comment by egouy** [comment] 2020-04-10 08:17
Thanks @qweasd1 you're a life saver !

**Comment by johnmerrifield** [comment] 2020-05-11 13:28
Thanks been stuck on this for ages, much prefer drag and drop.  Great solution

**Comment by pychap** [comment] 2020-06-03 23:47
Thanks @qweasd1 !!! Works great!

**Comment by racqel** [comment] 2020-06-08 17:43
Thank you @qweasd1

**Comment by michelvoillery** [comment] 2020-09-13 09:44
You Sir are a ⭐  Thank you so much for this! @qweasd1

**Comment by MattEding** [comment] 2021-01-29 05:32
I think many users would find it beneficial if the [official website's plugin list](https://hyper.is/plugins) listed @qweasd1's [hyper-drop-file](https://github.com/qweasd1/hyper-drop-file).

**Comment by LabhanshAgrawal** [comment] 2021-07-21 07:59
Please test the build from #5781 and confirm if it's fixed.
https://github.com/vercel/hyper/actions/runs/1051719012#artifacts
Can be included in next patch release, if working.
