### ISSUE TITLE
hyper 2.1.2.exe won't open on windows 10

### ISSUE THREAD

**Issue by DanielMutu** [zeit/hyper#3514] opened 2019-03-08 10:26 UTC
Hi, in W10,  hyper 2.1.2 won't open.
I tried to delete my .hyper config file but doesn't work.
Any Ideas?
Thanks!

**Comment by cjoshmartin** [comment] 2019-03-12 03:09
@DanielMutu Look at this thread and see if is similar to your issue: #3442

**Comment by DanielMutu** [comment] 2019-03-13 18:04
No, because I don't have the javascript popup, simply won't open, I tried run as administrator and there is no change

**Comment by samharr** [comment] 2019-05-12 18:06
i am having the same issue

**Comment by nickland** [comment] 2019-05-26 11:49
Same issue. The process is running in the background but it just doesn't launch.

What I did before that happen was, installing it for the first time, then replace the config with the config provided for git bash and then close it immediately to restart it. Since then it doesn't launch anymore. Uninstall and reinstall doesn't help either.

**Comment by nickland** [comment] 2019-05-26 11:59
going to %appdata%, finding the Hyper folder and wiping it, then reinstalling, helped me.
Why is that folder not removed when Hyper is uninstalled?

**Comment by nickland** [comment] 2019-05-26 12:09
> No, because I don't have the javascript popup, simply won't open, I tried run as administrator and there is no change

Same issue, caused by changing the config in my case. The Javascript Popup won't appear when Hyper is closed and launched again, it will just not appear at all.

If you changed your config and then opened a new window from within Hyper, you would have probably received the error.

Try going into the directory for hyper, under Windows that should be somewhere under %appdata%
and completely delete it for a proper reinstall.

**Comment by fazi-malik450** [comment] 2019-08-29 10:18
When i open my hyper it open a new window of cmd and deafult hyper window is blank 
plz help me to solve this

**Comment by Stanzilla** [comment] 2019-10-10 19:33
Try a recent version

**Closed by Stanzilla** 2019-10-10 19:33 UTC
