### ISSUE TITLE
Windows 10 text disappears and gets tabbed

### ISSUE THREAD

**Issue by rianquinn** [zeit/hyper#3465] opened 2019-02-07 21:10 UTC
When I open a new Hyper window on Windows 10 and start typing, this is what I get

![image](https://user-images.githubusercontent.com/5932003/52443063-fcdf1f80-2ae1-11e9-8343-b8cdf53b352d.png)

I am running 2.1.2

**Comment by hussainb** [comment] 2019-02-20 13:56
Same issue here.
I can see that the scroll bar is scrolled to the bottom and after scrolling to top I can see the windows version info.

On opening hyper:

![image](https://user-images.githubusercontent.com/4962633/53096386-0d14e700-3545-11e9-8ebb-9b9bd058fa8c.png)


On typing something:
![image](https://user-images.githubusercontent.com/4962633/53096502-5107ec00-3545-11e9-9d20-2166feec93d9.png)

**Comment by sydeslyde** [comment] 2019-03-06 20:40
I confirm the same behaviour (Windows 10 Pro 1809).

After starting Hyper, the cursor is invisible.
When starting to type, the input is shown at the correct horizontal position, but the first outputs are gone.
(Scrolling upwards does not reveal anything for me)

After the first command is committed (via `Enter`) everything seems to work fine.
This happens also after a Full Reload via Menu -> View -> Full Reload.
No errors/warnings on the Console in Developer-Tools.

**Comment by studiochris** [comment] 2019-03-06 23:23
[Windows 10 Pro 1809 - Hyper 2.1.2 (stable)]

Confirming this one as well. Of note the strange behavior only happens in the first default "tab" of a new window. Additional tabs behave correctly.

**Comment by robinnorth** [comment] 2019-04-26 09:36
Looks like a duplicate of #3239, which is in turn a result of https://github.com/Microsoft/console/issues/270

**Comment by Stanzilla** [comment] 2019-10-10 22:02
should no longer happen with CI builds of canary and the next release

**Closed by Stanzilla** 2019-10-10 22:02 UTC
