### ISSUE TITLE
Pasting into nano removes line breaks

### ISSUE THREAD

**Issue by pento** [zeit/hyper#1448] opened 2017-01-24 03:58 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OSX 10.12.3
- **Hyper.app version**: 1.1.0 (1.1.0.1408)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/pento/ec0a96a33be6fc98ec93559ba68ce7fb
- **Relevant information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Reproducible with plugins disabled, didn't try vanilla.

## Issue

When pasting text into nano, newline characters are removed.

To reproduce:

* Copy some text with line breaks in it. It doesn't matter where the text is copied from.
* Open `nano`
* Press Cmd+V

**Comment by galpratama** [comment] 2017-01-31 17:27
Im experiencing the same things

**Comment by timpactera** [comment] 2017-02-08 23:13
I'm experiencing the exact same issue when editing a text file using nano.

Pasting into Nano removes line-breaks (some times?) and also overwrites text (instead of inserting the pasted text and moving all the rest down like what happens if you use the built-in Terminal). 

I'm on a Mac (MacOS Sierra 10.12.3), Hyper 1.1.0.1408
Example text to copy/paste:  Podfile example under "get started" at https://cocoapods.org/

This issue does not happen in vi or vim.

Emacs gives strange indents to each line that you usually don't get when using the built-in terminal.

**Comment by jcoetzee** [comment] 2017-03-13 06:47
A good example of this is pasting a certificate (in PEM format). It seems it ignores newlines until the content would overflow and then it honours them.

![screen shot 2017-03-13 at 8 45 38 am](https://cloud.githubusercontent.com/assets/1784961/23844254/a136dbb0-07c9-11e7-9390-a0de7aed8cc7.png)

**Comment by chlp** [comment] 2017-06-06 06:28
This text is converted after paste in nano in one line:
<pre>
1
2

</pre>

but this text is pasted correctly:
<pre>
1
 2
</pre>

Paste work correctly, If new line has space at first position.

and this text is pasted correctly:
<pre>
1
2
</pre>

Paste work correctly, if copy without last line break (only for the last line).

**Comment by robinbertram** [comment] 2017-06-16 09:56
I just experienced this as well.

If I change the files newline option from `LF` to `CRLF` I get a different result.

Let's use the following text as an example;

```
DB=true
DB_ADAPTER=mysql
DB_HOST=localhost
DB_USERNAME=vagrant
DB_PASSWORD=secret
DB_DATABASE=aware
DB_PORT=3306
DB_CHARSET=utf8
DB_COLLATION=utf8_swedish_ci
```

If the file is set with `LF` I get the following result when pasting my text;
```
DB=true DB_ADAPTER=mysql DB_HOST=localhost DB_USERNAME=vagrant DB_PASSWORD=secret DB_DATABASE=aware DB_PORT=3306 DB_CHARSET=utf8
DB_COLLATION=utf8_swedish_ci
```

If I then change to CRLF I get the following result;
```
DB=true

DB_ADAPTER=mysql

DB_HOST=localhost

DB_USERNAME=vagrant

DB_PASSWORD=secret

DB_DATABASE=aware

DB_PORT=3306

DB_CHARSET=utf8

DB_COLLATION=utf8_swedish_ci
```

None are correct. But this may point someone in the right direction when debugging this issue.

**Comment by harryparkdotio** [comment] 2017-07-18 15:40
macOS El Capitan:

`Menu --> Edit --> Paste` seems to resolve this (not ideal, but hey it works)

**Comment by robinbertram** [comment] 2017-07-19 06:53
@harryparkdotio Does not work for me. I get the same result by copying and pasting my previous example:
```
DB=true
DB_ADAPTER=mysql
DB_HOST=localhost
DB_USERNAME=vagrant
DB_PASSWORD=secret
DB_DATABASE=aware
DB_PORT=3306
DB_CHARSET=utf8
DB_COLLATION=utf8_swedish_ci
```
Everything except the last row, lines up on the same row.

But I'm also running MacOS Sierra.

**Comment by bienvenidosaez** [comment] 2017-08-29 10:24
Me too

**Comment by Scukerman** [comment] 2017-09-13 08:54
same here

**Comment by towicode** [comment] 2017-10-23 18:02
same here.

**Comment by HectorRos** [comment] 2017-10-25 09:25
Same problem here, example pasting:

`# BR Config
# ifcfg-br0
DEVICE=br0
TYPE=Bridge
BOOTPROTO=static`

MacOS High Sierra 10.13 (But happens on Windows 10 and macOS Sierra too).

**Comment by GerManson** [comment] 2017-11-02 19:46
Same problem here typing almost everything with multiple lines into nano

MacOS High Sierra 10.13.1

**Comment by GioLogist** [comment] 2017-11-03 04:45
Same problem as well. 

Mac OS 10.12.6 (16G29)
Hyper 1.4.8

Plugins: None (disabled all to test)

**Comment by Scukerman** [comment] 2017-11-03 08:06
Does anyone care about this issue? We could celebrate a year of inactivity in a couple of months.

**Comment by chabou** [comment] 2017-11-03 09:31
Can you try to reproduce on v2 available on `canary` update channel?

@Scukerman In any case, PRs are very welcome.

**Comment by Scukerman** [comment] 2017-11-03 10:12
@chabou

OS: MacOS High Sierra 10.13.2 Beta
```
Hyper 2.0.4 (stable)
Plugins: 
  hyper-snazzy (1.2.2)
```

Same issue.

**Comment by chabou** [comment] 2017-11-03 10:17
Thank for your feedback 🙏

**Comment by menzow** [comment] 2017-12-09 17:01
For me this issue still occurs on `MacOS 10.12.6` - `2.0.0-canary.8`. For some reason my system wants carriage returns for line breaks. My pastes only contain a `\n` char. After patching https://github.com/xtermjs/xterm.js/blob/master/src/handlers/Clipboard.ts#L23 and replacing \n with \r the pastes worked again.

I think a more permanent solution must be provided through upstream?

**Comment by OmgImAlexis** [comment] 2017-12-29 23:59
This is even weirder than just missing line breaks now. I copied the first section and pasted into nano over ssh and the second code block is the result.

```
  # mongodbexporter:
  #   image: mongodb_exporter
  #   container_name: mongodbexporter
  #   user: root
  #   privileged: true
  #   command:
  #       - '-mongo.uri=mongodb://$${netstat -nr | grep "^0\.0\.0\.0" | awk "{print $$2}"}:2017'
  #   restart: unless-stopped
  #   expose:
  #     - 9001
  #   networks:
  #       - monitor-net
  #   labels:
  #     org.label-schema.group: "monitoring"
```

```
  # mongodbexporter:
  #   image: mongodb_exporter container_name: mongodbexporter user: root privileged: true command:
  #       - '-mongo.uri=mongodb://$${netstat -nr | grep "^0\.0\.0\.0" | awk "{print $$2}"}:2017' restart: unless-stopped expose: - 9001 networks: - monitor-net labels: org.label-schema.group:
  #     "monitoring"
```

**Comment by Kimmax** [comment] 2018-02-06 11:08
Still happening
It makes hyper basically unusable for me

**Comment by bryantAXS** [comment] 2018-02-08 15:42
Same issue, back to terminal it is

**Comment by cclafferty** [comment] 2018-02-13 17:37
This is happening me too. I copied code written in Visual Studio Code over to nano and not only does it paste it in as one big line it also starts to eat other lines making a real mess.

**Comment by chabou** [comment] 2018-02-14 08:29
@cclafferty @Kimmax @bryantAXS What is you Hyper version?
I can't reproduce on `2.0.0-canary.11`

**Comment by Scukerman** [comment] 2018-02-14 08:35
@chabou I just installed it to test. Still happening in nano.

```
Hyper 2.0.0-canary.11 (stable)
Plugins: 
  hyper-snazzy (1.2.2)
```

OS: `macOS High Sierra 10.13.3`
Shell: `zsh 5.3.1 (x86_64-apple-darwin16.6.0)`

**Comment by chabou** [comment] 2018-02-14 08:52
@Scukerman thank you for your feedback.
I'm using zsh too and I can't reproduce :(

**Comment by cclafferty** [comment] 2018-02-14 16:15
```
Hyper 1.4.8 (stable)
Plugins: 
  hyper-darkmatter (0.2.2),
  hyperterm-summon (2.0.5)
```
OS: `macOS High Sierra 10.13.3`
Shell: `zsh 5.4.2 (x86_64-apple-darwin17.3.0)`

**Comment by Kimmax** [comment] 2018-02-14 21:48
@chabou I'm out of office till monday, gonna update you as soon as I can

**Comment by olsonpm** [comment] 2018-02-21 08:09
This issue occurs in [xterm.js' demo](https://github.com/xtermjs/xterm.js#demo) so I imagine it's unrelated to hyper.

**Comment by Kimmax** [comment] 2018-02-21 09:15
@chabou I'm sorry, forgot you. I'm on 2.1.1 stable
@olsonpm I don't see the connection here, mind shining light on me?

**Comment by olsonpm** [comment] 2018-02-21 09:25
I'm still working at debugging this via the xterm.js demo.  There are a decent amount of paste issues on both xterm.js and vscode (which forked xterm.js I believe).  It just seems like the issue is deeper than this client which is built on top of xterm and electron but hopefully I'll have it solved by tomorrow.

**Comment by olsonpm** [comment] 2018-02-23 02:24
Alright - more reading and I finally understand the issue.

**In short**: The fix is to translate `\n` to `\r` as @menzow initially described. I will open a PR in xterm.js.  

*note Hyper uses [a fork of xterm.js](https://github.com/zeit/hyper/blob/canary/package.json#L197) which will need to pull in the fix when it's merged.*
<br>

**In case you want to understand what's going on**:

This seems to be a bug in any program which doesn't implement [bracketed paste mode](https://cirw.in/blog/bracketed-paste) (or properly implement it in the case of [joe](https://joe-editor.sourceforge.io/)).  As noted in [this nano bug](http://savannah.gnu.org/bugs/?49176) other editors which don't paste properly include joe and [dit](http://hisham.hm/dit/).  You'll notice when you paste with newlines, each editor interprets `\n` aka `^J` to a function.  e.g. nano follows pico, and pico decided `^J` should be used to justify content.

**Comment by Kimmax** [comment] 2018-02-24 15:12
Finally some progress on this! Thanks so much for digging into this @olsonpm

**Comment by olsonpm** [comment] 2018-03-08 20:17
@chabou - what branch of [chabou/xterm.js](https://github.com/chabou/xterm.js) should I create a PR for with the [merged fix](https://github.com/xtermjs/xterm.js/pull/1296)?

**Comment by Scukerman** [comment] 2018-04-11 11:49
any news?

**Comment by chabou** [comment] 2018-04-11 13:24
@Scukerman Thank you for your up :)

@olsonpm Sorry I haven't seen your question.
I will merge your xterm PR in my fork ASAP.

**Comment by olsonpm** [comment] 2018-04-11 14:09
no worries - i saw the commit history when i first started using hyper.  You are very busy :)

**Comment by chabou** [comment] 2018-04-11 15:15
It has already been merged in my used fork: https://github.com/chabou/xterm.js/commit/855964fbe10099410edb6dc85ed6b7940130649c

I tried to reproduce without any success.
Can anybody confirm me that it has been fixed in our last canary (v2.0.0-canary.16)?

**Comment by Scukerman** [comment] 2018-04-11 17:36
Yay! It works!
@olsonpm @chabou thank you so much.

**Comment by albinekb** [comment] 2018-04-12 11:25
Thanks for confirming @Scukerman, I'm closing this now! 🎉 Open if you still have this issue in hyper `v2.0.0-canary.16` or higher.

**Closed by albinekb** 2018-04-12 11:25 UTC
Labels: help wanted, 🐛 Type: Bug

**Comment by monksy** [comment] 2025-08-16 18:37
I'm seeing htis issue on mac version 15.6 and the latest version of ghostty from brew.
