### ISSUE TITLE
Cannot drag and drop files/folders to get their paths

### ISSUE THREAD

**Issue by ansidev** [zeit/hyper#3692] opened 2019-05-27 10:12 UTC
- [ x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version 3.0.2 (stable)
- [ x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and I found a relate closed issue #110 

- **OS version and name**: macOS 10.14.5
- **Hyper.app version**: Hyper 3.0.2 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ansidev/f5704c032f3cf15bebf3f3961c67e5ea
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: No console error
- **The issue is reproducible in vanilla Hyper.app**: Is vanilla

## Issue
It relates to #110

**Comment by LaboratoryK** [comment] 2019-05-28 01:00
I also encountered this situation, it nearly drive me crazy.
Is this a designed new "feature" of hyper3? or conflict with some new functions?

**Comment by TheInterwebbers** [comment] 2019-05-28 12:44
+1

**Comment by mihaiserban** [comment] 2019-05-29 08:43
this was super useful, to drag and drop and go to a folder

**Comment by rodolfoviolac** [comment] 2019-05-30 23:24
Duplicate of #3582

**Closed** 2019-05-31 02:35 UTC

**Comment by qweasd1** [comment] 2020-01-11 14:25
guys, I create a plugin for this: https://github.com/qweasd1/hyper-drop-file, just  ```hyper install hyper-drop-file```
