### ISSUE TITLE
Can't exit to nano

### ISSUE THREAD

**Issue by Zagur** [zeit/hyper#1258] opened 2016-12-17 21:32 UTC
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

When I editing a file with nano, i can't to exit with Control + x.

**Comment by timneutkens** [comment] 2016-12-17 22:18
Version: 1.0.0 (latest release)
OS: mac

I tried to reproduce (usually use vim). Steps to reproduce (not always shows)
1. Open window
2. `nano <file>`
3. `cmd + x` (to exit)
4. Output flashes all over te screen, cursor returns but is kinda hard to see. You can't `cmd + k` it wait.

**Comment by timneutkens** [comment] 2016-12-17 22:25
@Zagur could you please update your bug report with all information? Would make debugging so much easier ❤️

**Comment by reddigari** [comment] 2016-12-18 00:17
Try `ctl-SHIFT-x`. On Ubuntu the control keybindings are inconsistent; some require `SHIFT` and others only work without it.

**Comment by jordanarseno** [comment] 2016-12-18 03:01
Was also having this issue. Confirmed that adding `Shift` allows exit.

**Comment by WoodyWoodsta** [comment] 2016-12-19 07:21
Dupe https://github.com/zeit/hyper/issues/1069, https://github.com/zeit/hyper/issues/1132

**Comment by an0nh4x0r** [comment] 2016-12-22 05:56
:+1:  works :100: on using `control + shift + X` in ubuntu. Thanks Guys!

**Comment by albinekb** [comment] 2017-01-04 19:19
Closing, duplicate of https://github.com/zeit/hyper/issues/1069 and https://github.com/zeit/hyper/issues/1132
thanks @WoodyWoodsta

**Closed by albinekb** 2017-01-04 19:19 UTC

**Comment by taufikdev** [comment] 2022-03-18 11:50
Maybe you don't have the permission to modify the file( as hapened to me as a beginner),all you have to do is:
`sudo nano <filename>`  then you can `ctl+o` then `ctl-x`
