### ISSUE TITLE
Can't always close browser with ctrl-c

### ISSUE THREAD

**Issue by midgethoen** [zeit/hyper#392] opened 2016-07-25 10:38 UTC
When the built in browser has focus, I'm unable to close it with `ctrl-c`. 

I have to click the header first, which took me a while to figure out when first using it :)

**Comment by CodeTheory** [comment] 2016-07-26 18:24
Are you on OSX? Does this happen with all sites you visit in HyperTerm? 

Has anyone else experienced this/Can anyone else reproduce this?

**Comment by albinekb** [comment] 2016-07-26 18:58
Yes, if you open a page:
`$ google.com`
then you can close it with `ctrl-c`
but if you click somewhere on the page, it will take the focus,
which makes `ctrl-c` not got to the terminal

**Comment by rauchg** [comment] 2016-07-26 18:59
We can fix this with a global accelerator registration of `ctrl+c` and thusly make the webview great again?

**Comment by midgethoen** [comment] 2016-07-28 08:46
sounds good, I could work on this if you'd like. not sure how difficult it would be :)

**Comment by beane** [comment] 2016-08-31 04:17
I can confirm that this is happening. Would love to see a fix -- this feature is the coolest thing about HyperTerm.

OS X 10.11.6 and HyperTerm 0.7.1.36 installed by homebrew

**Comment by joaosa** [comment] 2016-11-13 16:10
It is indeed a useful feature. Any news? :)

**Comment by vspedr** [comment] 2016-12-16 11:25
Not sure if this is related, but it seems that new tabs don't work as expected when the browser is open... opening a new tab always gives me the same browser view. It's not just a rendering issue, I can interact with the browser normally from any of the new tabs.

<img width="613" alt="screen shot 2016-12-16 at 09 21 15" src="https://cloud.githubusercontent.com/assets/9813942/21261296/9b36eeb8-c371-11e6-9c5f-3fb8e386a089.png">


BTW I just found this built-in browser accidentally, I was trying to clone a repo and somehow it opened the github URL instead

**Comment by rauchg** [comment] 2016-12-16 20:58
That shouldn't be the case since it should have said "command not found". Did you paste the url by mistake?

**Closed** 2016-12-21 15:19 UTC
Labels: Status: Awaiting Response, Status: Help Wanted, Type: Bug
