### ISSUE TITLE
Fish doesn't start properly

### ISSUE THREAD

**Issue by jkanche** [zeit/hyper#1963] opened 2017-06-29 17:10 UTC
sometimes, hyper doesn't load and won't initialize the prompt.. 

screenshot - ![Fish](https://i.gyazo.com/adfbc92b99f497b3ad5be4f72d31a8db.png)

I see this error when i open developer tools - 

> bundle.js:47 Uncaught TypeError: Cannot read property 'substr' of null

**Comment by CodeTheory** [comment] 2017-06-29 19:26
Hi, this looks like a duplicate of an really recent issue. Can you tell us if it's different than #1961?

**Comment by jkanche** [comment] 2017-06-30 14:51
I have no plugins installed but still see the error...

**Comment by CodeTheory** [comment] 2017-06-30 23:41
Right, the error is the same as the issue I linked, hence the assumption.
What operating system are you on? Which Hyper version are you on? Are you sure you have no plugins/themes? Hyper should be black by default and it looks like yours is themed.

**Comment by rwwagner90** [comment] 2017-07-03 02:10
Does it load after a few minutes? I'm seeing a startup time of several minutes all the sudden and I'm on fish too.

**Comment by jkanche** [comment] 2017-07-10 16:05
@CodeTheory 

> What operating system are you on? 

Ubuntu 16.04

> Which Hyper version are you on? 

hyper 1.3.3

> Are you sure you have no plugins/themes? 

When i first posted the issue, i had a theme installed. but I removed all themes and plugins but the issue still persists

Hyper should be black by default and it looks like yours is themed.

**Comment by doughsay** [comment] 2017-07-23 19:09
Hello!  Happening to me too, on a fresh install of ubuntu + hyper (no plugins installed).

* Ubuntu 17.04
* installed fish through apt and set as my default shell (chsh)
* installed hyper using latest .deb file 1.3.3
* won't start, console shows above mentioned error (Uncaught TypeError: Cannot read property 'substr' of null)

**Comment by whitelynx** [comment] 2017-08-10 18:50
I'm also experiencing this, probably 75% of the times I start the app. Sometimes it works fine, other times it just freezes there and shows that error in the console.

I added some debugging `console.log()` calls before line 14037 of `node_modules/hterm-umdjs/dist/index.js` to see what the values involved were:
```
index.js:14037 this.foreground: ""
index.js:14038 this.defaultForeground: null
index.js:14039 colorToMakeFaint: null
index.js:463 Uncaught TypeError: Cannot read property 'substr' of null
    at Object.lib.colors.crackRGB (index.js:463)
    at Object.lib.colors.mix (index.js:445)
    at hterm.TextAttributes.syncColors (index.js:14040)
    at hterm.TextAttributes.setDefaults (index.js:13978)
    at hterm.VT.CSI.m (index.js:16324)
    at hterm.VT.dispatch (index.js:14853)
    at hterm.VT.parseCSI_ (index.js:14701)
    at hterm.VT.interpret (index.js:14612)
    at hterm.Terminal.interpret (index.js:11698)
    at __WEBPACK_IMPORTED_MODULE_2_runes___default.forEach.rune (hterm.js:134)
```

It seems like the `foreground` and `defaultForeground` properties of that particular `hterm.TextAttributes` instance aren't getting set before the `syncColors` method is called.

I also added a `throw` there if `colorToMakeFaint` is `null`, and was able to get a bit more of the stack:
```
Uncaught Error: colorToMakeFaint is null!
    at hterm.TextAttributes.syncColors (file:///home/whitelynx/Development/Other/hyperterm/app/dist/bundle.js:49056:13)
    at hterm.TextAttributes.setDefaults (file:///home/whitelynx/Development/Other/hyperterm/app/dist/bundle.js:48993:8)
    at hterm.VT.CSI.m (file:///home/whitelynx/Development/Other/hyperterm/app/dist/bundle.js:51342:9)
    at hterm.VT.dispatch (file:///home/whitelynx/Development/Other/hyperterm/app/dist/bundle.js:49871:11)
    at hterm.VT.parseCSI_ (file:///home/whitelynx/Development/Other/hyperterm/app/dist/bundle.js:49719:10)
    at hterm.VT.interpret (file:///home/whitelynx/Development/Other/hyperterm/app/dist/bundle.js:49630:27)
    at hterm.Terminal.interpret (file:///home/whitelynx/Development/Other/hyperterm/app/dist/bundle.js:46713:11)
    at __WEBPACK_IMPORTED_MODULE_2_runes___default.forEach.rune (file:///home/whitelynx/Development/Other/hyperterm/app/dist/bundle.js:16489:20)
    at Array.forEach (native)
    at hterm.Terminal.IO.component___WEBPACK_IMPORTED_MODULE_0_react___default.a.PureComponent.__WEBPACK_IMPORTED_MODULE_1_hterm_umdjs__.hterm.Terminal.IO.writeUTF8 (file:///home/whitelynx/Development/Other/hyperterm/app/dist/bundle.js:16487:57)
```

I'm not sure how to proceed in debugging this past this point... any ideas?

**Comment by DanielRamosAcosta** [comment] 2017-09-11 06:50
Problem still persists in 1.4.3

**Comment by Stanzilla** [comment] 2018-04-24 01:03
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Closed by Stanzilla** 2018-04-24 01:03 UTC
