### ISSUE TITLE
High power usage

### ISSUE THREAD

**Issue by k1sul1** [zeit/hyper#1040] opened 2016-11-24 19:35 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Sierra 10.12.1
- **Hyper.app version**: 0.8.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/k1sul1/736cb5dfd7809533ca9b1e0533bbe75d
- **Relevent information from devtools**: N/A

## Issue
Hyper is using quite a bit of battery power to operate. When I'm safely plugged in at my desk, this is not an issue, but on the go it seems to drain my battery pretty fast. 

I'm not sure if this is an issue with Hyper directly, or should I blame Electron. Few tabs, one instance of Browsersync and two Vim instances is what I usually roll with, so it's not like I'm doing any heavy lifting. 

Is this something that we just have to cope with, or could something be done for this? Here's my power activity: 

![power usage](http://i.imgur.com/82THHlz.png)

Chrome is usually doing a lot more, but uses less power. Slack, being the power hungry monster is also doing ok. 

I'd test without the few plugins I use ("hyperline", "hyperterm-atom-dark", "hyperterm-blink", "hypercwd"), but I kinda need those plugins (at least the theme and blink), and power usage isn't something that you just test for five minutes.

**Comment by audunolsen** [comment] 2016-11-24 19:44
I had/occationally still have this issue. I used the "hyperpower" plugin and removing it has helped. I believe it may be at least partially plugin related.

**Comment by luisrudge** [comment] 2016-11-24 20:49
how ironic, the hyperpower plugin using so much power 😝

**Comment by matheuss** [comment] 2016-11-27 17:15
I'm almost sure this is related to Sierra – not sure if there's something we can do about it 😕

**Comment by cyle** [comment] 2016-12-02 17:39
I'm having this same issue and it's really annoying. I love Hyper but having 4 Hyper windows open drains my battery faster than Chrome with 30 tabs open or Atom with lots of files open. Having Atom and Hyper open at the same time (both use Electron), and Atom doesn't use nearly as much power according to Activity Monitor. 😭

**Comment by hpohlmeyer** [comment] 2016-12-06 21:29
Same here. Hyper in idle is using more energy than Illustrator and Photoshop with multiple open documents.

---

__Specs__

MacOS Sierra 10.12.1
Hyper 0.8.3

Hyper plugins: hyper-snazzy (Tested without it and there was no change in energy consumption)

Shell: Oh-my-zsh
Zsh-plugins: zsh-syntax-highlighting
Zsh-prompt: pure-prompt

**Comment by hpohlmeyer** [comment] 2016-12-13 15:57
Seems to be gone after updating to Hyper 1.0.0.  
Can you confirm that?

**Comment by marclundgren** [comment] 2016-12-17 02:46
is it related to this? https://github.com/zeit/hyper/issues/474

**Comment by k1sul1** [comment] 2016-12-19 12:29
Yes. That topic just [doesn't come up on the issue tracker](https://github.com/zeit/hyper/issues?utf8=%E2%9C%93&q=is%3Aissue%20power) with the keyword `power`, hence this topic. 

Also my numbers are much greater (which is a bad thing) than any of the responses. I went back to using iTerm 2 as Hyper just doesn't work well enough to be used with anything serious.

**Comment by marclundgren** [comment] 2016-12-19 20:08
IMO this should be closes as a duplicate of #474

**Comment by hpohlmeyer** [comment] 2016-12-19 20:12
I think so too, but maybe we can close it alltogether.
@k1sul1 do you still have those issues with the 1.0.0 version?

**Closed** 2018-04-22 23:59 UTC
Labels: 📊 Type: Performance
