### ISSUE TITLE
Hyper support for hotexit?

### ISSUE THREAD

**Issue by hanishassim** [zeit/hyper#1819] opened 2017-05-13 07:07 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.11.6, OS X El Capitan
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/hanishassim/5cca0f9763218347a5e9457bc5c73445
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: is Vanilla

## Issue
Hi Do Hyper support hotexit like on the stock Terminal & Sublime Text? Hotexit as in when user reopen the app after closing/terminate, it will restore to the previous state.

**Comment by albinekb** [comment] 2017-05-13 14:26
duplicate of https://github.com/zeit/hyper/issues/567

**Closed by albinekb** 2017-05-13 14:26 UTC
