### ISSUE TITLE
Arrow keys don't work when using Bash on Windows

### ISSUE THREAD

**Issue by erickmarsh** [zeit/hyper#1404] opened 2017-01-13 17:45 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 - Aninversery Edition
- **Hyper.app version**: 1.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/erickmarsh/86394eb506c6c473de987a661399564e
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**:  `Is Vanilla`

## Issue

The arrow keys don't do anything. For example, I open the app and type
`> 12345678`
I press the left-arrow 3 times and I would expect to have my cursor between the 5 and 6. However, my cursor stays at the end of the line. 

My relevant hyper.js config
 `shell: 'c:\\windows\\System32\\bash.exe'`

**Comment by zbuttram** [comment] 2017-01-13 18:40
Duplicate of #1127, real issue is with the WSL itself at Microsoft/BashOnWindows#111

**Comment by matheuss** [comment] 2017-01-15 16:02
Thank you @zbuttram 🙌

**Closed by matheuss** 2017-01-15 16:02 UTC
