### ISSUE TITLE
Ctrl + W closes the terminal 

### ISSUE THREAD

**Issue by misgeatgit** [zeit/hyper#1199] opened 2016-12-14 07:28 UTC
When typing Ctrl + W inside vim, the terminal closes.

**Comment by annnoo** [comment] 2016-12-14 15:17
At least it would be a good idea to be able to switch the shortcuts via config-file. I just edited the accelerators.js file manually (removed the 'W' at Close Session)

**Comment by misgeatgit** [comment] 2016-12-15 07:01
Also
- Opening the terminal and typing Ctrl + d closes the terminal.
- Unable to delete the last line with Ctrl + k as in bash shell.

**Comment by annnoo** [comment] 2016-12-15 07:23
Are you using Windows? 

I have the strange feeling that no shortcut with the Ctrl key is working..

**Comment by misgeatgit** [comment] 2016-12-15 08:25
@annnoo I'm on ubuntu 14.04.

**Comment by annnoo** [comment] 2016-12-15 09:08
@misgeatgit Oh okay. I just thought that this is maybe a Windows only problem.

**Comment by parro-it** [comment] 2016-12-15 09:15
> Opening the terminal and typing Ctrl + d closes the terminal.

This is a standard shortcut on all terminal emulators I'm aware of...

**Comment by jlobos** [comment] 2016-12-15 11:05
In `Arch` + `Hyper` & `nvim` Ctrl+w close terminal 😓

**Comment by misgeatgit** [comment] 2016-12-15 11:35
@parro-it You are correct about Ctrl + d, my bad.

**Comment by annnoo** [comment] 2016-12-15 11:58
Ctrl + W is closing the current session. If you have only one session/window open it will close the whole program, because there aren't any other sessions left.

I guess the two main problems are 
1. Making it possible to change the shortcuts via settings file 
2. Ctrl-key is not working in applications inside of Hyper

**Comment by nbolten** [comment] 2016-12-16 21:17
Hi, I've put in a pull request that hopefully addresses this issue here: https://github.com/zeit/hyper/pull/1191 . It would make the default `mod` key into <kbd>Ctrl</kbd>+<kbd>Shift</kbd> on Windows and Linux so that there are no longer conflicts with CLI apps using <kbd>Ctrl</kbd> shortcuts.

It does not make the `mod` key configurable in `hyper.js`, but I think there's another patch in the works for that.

Feedback is helpful! The pull request is surely not perfect.

**Comment by ppot** [comment] 2017-02-12 22:47
I would request you to add desired keybinding for linux in comments at https://github.com/ppot/hyper/issues/11
```
{
 "window:devtools":"Cmd+Alt+I",
 "window:reload":"Cmd+R",
 "window:reloadFull":"Cmd+Shift+R",
 "window:preferences":"Cmd+,",
 "zoom:reset":"Cmd+0",
 "zoom:in":"Cmd+plus",
 "zoom:out":"Cmd+-",
 "window:new":"Cmd+N",
 "window:minimize": "Cmd+M",
 "window:full": "Cmd-Ctrl-F",
 "window:close":"Cmd+Shift+W",
 
 "tab:new":"Cmd+T",
 "tab:next":"Cmd+shift+]",
 "tab:prev":"Cmd+shift+[",
 "pane:next":"Cmd+]",
 "pane:prev":"Cmd+[",
 "pane:left":"Cmd+Alt+Left",
 "pane:right":"Cmd+Alt+Right",
 "pane:up":"Cmd+Alt+Up",
 "pane:down":"Cmd+Alt+Down",
 "pane:vertical":"Cmd+D",
 "pane:horizontal":"Cmd+Shift+D",
 "pane:close":"Cmd+W",
 
 "editor:undo":"Cmd+Z",
 "editor:redo":"Cmd+Shift+Z",
 "editor:cut":"Cmd+X",
 "editor:copy":"Cmd+C",
 "editor:paste":"Cmd+V",
 "editor:selectAll":"Cmd+A",
 "editor:clearBuffer":"Cmd+K",
 
 "plugins:update": "Cmd+Shift+U"
}
```

**Comment by hf** [comment] 2017-02-18 15:43
Again, this happens on my Windows too.

**Comment by grafa** [comment] 2017-06-02 08:26
Hi guys,

I'm just sayin this is pretty much crucial thing. If I could somehow (read quickfix) disable all hyper shortcuts, that would do the trick (for now).

+1

**Comment by Juicy45** [comment] 2017-06-05 17:36
Ctrl W close the terminal also on fedora 25 in nano.

**Comment by jnardiello** [comment] 2017-07-08 00:25
I agree, this is a real issue for any linux power user. Expected behaviour for ctrl + w is to cancel latest word, not to end the session.

**Comment by ppot** [comment] 2017-08-15 00:07
close in #1876

**Closed by ppot** 2017-08-15 00:07 UTC
Labels: Status: Help Wanted, Type: Compatibility
