### ISSUE TITLE
Hyper crashes on launch on recent Windows 10 builds

### ISSUE THREAD

**Issue by cerebrate** [zeit/hyper#1959] opened 2017-06-27 17:47 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro Insider Preview, build 16215
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/cerebrate/ac9aa51a9dfa641a23fe1881f3be449a
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes. Removing plugins has no effect on problem.

## Issue
Hyper crashes on launch with the following error:

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: EINVAL: invalid argument, lstat 'C:\Users\avatar\OneDrive'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Gaze._addToWatched (C:\Users\avatar\AppData\Local\hyper\app-1.3.3\resources\app\node_modules\gaze\lib\gaze.js:292:14)
    at Gaze.add (C:\Users\avatar\AppData\Local\hyper\app-1.3.3\resources\app\node_modules\gaze\lib\gaze.js:190:8)
    at new Gaze (C:\Users\avatar\AppData\Local\hyper\app-1.3.3\resources\app\node_modules\gaze\lib\gaze.js:74:10)
    at gaze (C:\Users\avatar\AppData\Local\hyper\app-1.3.3\resources\app\node_modules\gaze\lib\gaze.js:86:10)
    at watch (C:\Users\avatar\AppData\Local\hyper\app-1.3.3\resources\app\config.js:44:3)
    at Object.exports.init (C:\Users\avatar\AppData\Local\hyper\app-1.3.3\resources\app\config.js:130:3)
    at Object.<anonymous> (C:\Users\avatar\AppData\Local\hyper\app-1.3.3\resources\app\index.js:62:8)

[OK]

I believe this may relate to the changes to OneDrive in Windows 10 build 16215 and higher, in which placeholders are once again available in place of conventional files, although I don't know why Hyper is attempting to access that folder in the first place.

**Comment by cerebrate** [comment] 2017-06-27 18:20
Confirmed : hacking config.js at line 20 to use an arbitrary temporary directory rather than homedir() - parent of the problematic OneDrive directory - makes the problem go away.

**Comment by DuIslingr** [comment] 2017-06-28 14:31
I don't experience this issue on Build 16226.

**Comment by srimajji** [comment] 2017-06-29 04:24
@cerebrate  thanks for the tip! I feel like this might have something to do with the new OneDrive "files on demand" feature that Microsoft recently released with the new insider builds.  

Hyper starts up without any issues if i turn off that feature within OneDrive settings.

**Comment by UsmanMohammad** [comment] 2017-06-29 11:05
@DuIslingr Did you enable OneDrive files on demand?

**Comment by DuIslingr** [comment] 2017-06-29 15:47
@UsmanMohammad I did actually. I'm gonna turn it off and see if that solves it

**Comment by cerebrate** [comment] 2017-06-29 15:52
Yeah, the fundamental problem is that node.js lstat() doesn't understand NTFS reparse points, which the OneDrive "folder" is.

**Comment by Florian-R** [comment] 2017-06-29 15:52
@UsmanMohammad Are you thinking it's due to nodejs/node#12737

**Comment by ddemaree** [comment] 2017-07-14 12:54
Same bug, same solution (turning off Files on Demand allowed Hyper to launch).

<img width="418" alt="2017-07-14" src="https://user-images.githubusercontent.com/965/28212964-eb5ccbd8-6871-11e7-9411-85cb425e6b45.png">

**Comment by HotelCalifornia** [comment] 2017-08-26 18:43
I just updated to windows 16725 and started getting this issue.

I looked at my OneDrive settings, and `Files On-Demand` is not enabled.

**Comment by eamodio** [comment] 2017-08-26 19:05
For now I just commented out line 130 in `config.js` (`%userprofile%\AppData\Local\hyper\app-1.3.3\resources\app\config.js`)
```js
  // watch();
```

You will lose the auto-detect of config changes, but at least it works :)

**Comment by athosbr99** [comment] 2017-08-29 01:23
I'm on 16251 build and I'm having this issue. I disabled Files On-Demand and it fixed it for a while but it returned today for some reason.

**Comment by eamodio** [comment] 2017-08-31 13:38
This seems to have been resolved in either the latest Windows fast-ring or the hyper upgrade

**Comment by danielsada** [comment] 2017-09-06 05:49
Confirmed #fixed for Build 16278 (Latest slow release) and for Hyper 1.4.3

**Comment by chabou** [comment] 2017-09-06 06:02
Great! Thank you!

**Closed by chabou** 2017-09-06 06:02 UTC
Labels: Platform: Windows, Priority: High, Type: Bug
