### ISSUE TITLE
Inverted colors repeat first character of the string

### ISSUE THREAD

**Issue by dcalhoun** [zeit/hyper#3314] opened 2018-12-07 18:20 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.14.1 (18B75)
- **Hyper.app version**: 2.1.0-canary.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  TBD
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  n/a
- **The issue is reproducible in vanilla Hyper.app**:  Have not tested it yet.

## Issue

Originally reported in [#3255](https://github.com/zeit/hyper/pull/3255#issuecomment-429627599), strings that are highlighted (i.e. the background/foreground colors are inverted), the first character of the string is repeated instead of the entire string.

The following is example output from running `jest#23.6.0`.

### Expected (macOS Terminal)

<img width="440" alt="jest-inverted-correct" src="https://user-images.githubusercontent.com/438664/49665310-20221b80-fa1a-11e8-8df2-f97012e21f18.png">

### Actual (hyper#2.1.0-canary.3)
<img width="369" alt="hyper-inverted-repeated-characters" src="https://user-images.githubusercontent.com/438664/49665235-dfc29d80-fa19-11e8-9d3a-0615c8eac352.png">

**Comment by chabou** [comment] 2018-12-07 19:09
I noticed that inverted color doesn't work at all if background is not opaque:
![image](https://user-images.githubusercontent.com/4137761/49667670-073a5a00-fa5c-11e8-9e51-ad569ae3acd9.png)

**Comment by dcalhoun** [comment] 2018-12-07 19:15
@chabou I wonder if it is [related to the fact that Jest inverts the "default terminal font color"](https://github.com/facebook/jest/issues/6494#issuecomment-398363637)? It's possible that it is unrelated and still an issue with xterm. I have no idea.

**Comment by chabou** [comment] 2018-12-07 19:24
Repeated char is certainly related to their dynamic atlas.
But I can't reproduce it in VSCode.

So maybe, Hyper initializes `xterm` badly.

**Comment by chabou** [comment] 2018-12-07 19:58
Repeated char on paste doesn't happen with `xterm` v3.7.0

Transparent inverted char still happens but happened with previous `hyper` release.
Understandable because `xterm` is using background color and `hyper` force `transparent` background colorfor term if user bg color is not opaque (and set background color to its own body). It prevents some overlapping between non-opaque layers.

**Comment by edsu** [comment] 2018-12-08 12:04
I'm seeing this when using the Unix utility`less` as well:

<img width="1002" alt="screen shot 2018-12-08 at 7 02 48 am" src="https://user-images.githubusercontent.com/33829/49685755-5f527a00-fab7-11e8-9cc5-e35e55a8f9c9.png">

I tried disabling my theme and color configuration but still see the same behavior.

**Comment by olivier-w** [comment] 2018-12-10 16:32
Did a little digging, looks like https://github.com/xtermjs/xterm.js/releases/tag/3.9.0 merged 30mins ago, would that fix this issue? Based on this comment: https://github.com/zeit/hyper/issues/3316#issuecomment-445837330

**Comment by chabou** [comment] 2018-12-10 17:21
@olivier-w thank you! I will try it ASAP!

**Closed** 2018-12-11 01:22 UTC
