### ISSUE TITLE
Window background opacity does not work (regression)

### ISSUE THREAD

**Issue by 01binary** [zeit/hyper#1799] opened 2017-05-08 17:08 UTC
I just updated Hyper this morning, and it seem to have kept my previous settings which made Hyper window translucent (.9 alpha) but the window renders opaque. I went back to settings and set the alpha in "rgba" for the background to .5, but window remains opaque. Looks like there's a regression on background styles being applied. Haven't double-checked on the Mac yet. Perhaps this is an issue with OS windows flags and the alpha channel for the window is being ignored.

-

Hyper 1.3.1
Electron 1.4.15
win32 x64 6.1.7601

**Comment by albinekb** [comment] 2017-05-20 03:52
Duplicate of #1638, see https://github.com/zeit/hyper/issues/1638#issuecomment-287377439
tl;dr, problem with electron + windows + transparency, maybe it's fixed in latest electron 🤔  #1848

**Closed by albinekb** 2017-05-20 03:52 UTC
