### ISSUE TITLE
Long lines wrap problem

### ISSUE THREAD

**Issue by Rawnly** [zeit/hyper#1566] opened 2017-02-21 08:52 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS: macOS 10.12.3**: 
- **Hyper Version: 1.2.1**: 
- **[Gist Link Here](https://gist.github.com/Rawnly/c5753383af37e486483e0dc4c4940cc7)**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: I've tried to disable all my plugins / my theme but the problem persist.
## Issue

The shell is **zsh**, with **oh-my-zsh** 
![bugged term](https://cloud.githubusercontent.com/assets/16429579/23157343/1549b950-f81b-11e6-8e4b-07169c2edf63.gif)

**After some tests, i think is a "compatibility" bug of hyper with the zsh shell, i've tried to completly uninstall Hyper and remove its files but the problem is still here**

> On the *regular* **terminal application** works all well
![schermata 2017-02-21 alle 09 55 55](https://cloud.githubusercontent.com/assets/16429579/23157544/053837fc-f81c-11e6-956d-96951489e379.png)

**Comment by gsklee** [comment] 2017-02-21 09:10
I don't think there is sufficient information here to help people pinpointing the bug. You may wanna do some of the following actions to increase the likelihood of your issue being successfully tackled:

* Disable your plugins one by one and see if a plugin is responsible
* Disable your Zsh theme and see if it's responsible
* Detail your actions that have led to this buggy behavior in the first place

**Comment by Rawnly** [comment] 2017-02-21 09:16
@gsklee Whe the strin is too long to enter in the window it delete the line and overwrite it. I've tested it in **vanilla** hyper but it doesn't changes nothing..

**Comment by Rawnly** [comment] 2017-02-22 21:31
No ideas?

**Comment by thasmo** [comment] 2017-02-25 21:39
Cannot reproduce this on Windows 10 using `zsh` and `oh my zsh` with hyper 1.2.1. Long lines wrap properly.

**Comment by matheuss** [comment] 2017-02-25 22:09
@Rawnly could you try to reproduce it with `bash` or even with `zsh` but without the _special_ chars in your `PS1`? We have a lot of problems with unicode 😕

**Comment by Rawnly** [comment] 2017-02-25 22:14
Ok @matheuss i think the problem is with unicode i've tried to reproduce it without *specia chars* and also with bash and it works as expected

**Comment by cfjedimaster** [comment] 2017-03-11 14:52
I'm having this as well on Win10 using Bash. I'm not really a bash expert myself, are you saying settings used for path or for updating the title (both of which I've done recently) are the problem and it is *not* a Hyper bug?

**Comment by Rawnly** [comment] 2017-03-11 14:56
This problem happen if you have some unicode special chars in your `ps1` 

> The ps1 is the string before the input, the classic `macbook@rawnly $  ..`

So we need to wait a fix from the *:zap: hyper team* ...

**Comment by cfjedimaster** [comment] 2017-03-11 15:04
Thanks @Rawnly - I appreciate that.

**Comment by CodeTheory** [comment] 2017-06-30 00:32
👋  I believe this is the same issue as #283 so I'm going to close this as a duplicate. 
#283 was believed fixed but clearly isn't so I've re-opened is and will try and keep all conversation in that issue.

**Closed by CodeTheory** 2017-06-30 00:32 UTC
