### ISSUE TITLE
Shortcuts don't work in Linux Mint with Cinnamon	

### ISSUE THREAD

**Issue by dleitee** [zeit/hyper#499] opened 2016-07-29 12:48 UTC
I'm trying to use the shortcuts, example, ctrl + n or ctrl + k, and nothing happens.

What can be the cause?

Thank you.

-

HyperTerm 0.7.1
Electron 1.2.8
linux x64 3.19.0-32-generic

**Comment by reflog** [comment] 2016-07-29 12:51
same goes for plugin shortcuts. I used visor plugin, added Ctrl-` shortcut and it doesn't respond

**Comment by albinekb** [comment] 2016-07-29 22:58
That's because it only gets sent to the terminal
https://github.com/zeit/hyperterm/blob/master/lib/hterm.js#L32
I'm working on a fix for this, hopefully done soon 👼

**Comment by brycepj** [comment] 2016-08-02 03:40
Not unique to your distro (Mint) as far as I can tell -- I'm experiencing the same thing on Ubuntu 14.04.

**Comment by flybayer** [comment] 2016-10-06 18:38
You currently have to add `Super` to key combo for it to work.

**Comment by flybayer** [comment] 2016-10-06 18:42
@CodeTheory this is a duplicate of #274

**Closed** 2016-10-11 15:12 UTC
Labels: Platform: Linux, Type: Question
