### ISSUE TITLE
app title snipped baddly

### ISSUE THREAD

**Issue by guy-kdm** [zeit/hyper#2906] opened 2018-04-23 07:14 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Ubuntu 17.10 
- **Hyper.app version**:2.0 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

![image](https://user-images.githubusercontent.com/5744717/39111765-fac2a42a-46de-11e8-8cd3-d3ca0758c363.png)

App title shouldn't be snipped when it's short.

**Comment by timothyis** [comment] 2018-04-23 15:08
Duplicate of #2641. Thanks for the confirming.

**Closed by timothyis** 2018-04-23 15:08 UTC
