### ISSUE TITLE
Command clear not working properly

### ISSUE THREAD

**Issue by samuelmrp** [zeit/hyper#1809] opened 2017-05-10 13:23 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.3.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

I am using Hyper with git-bash (if you don't know how to, see [this issue](https://github.com/zeit/hyper/issues/1773))

In previous version the command clear was working, but now it is not clearing screen, see the picture bellow:

![capture_hyper](https://cloud.githubusercontent.com/assets/1356481/25900611/641342a4-356a-11e7-96be-09dfa3cd0c0b.PNG)

as you can see there is two problems in this picture:
* first I tried to use the command vi on .hyper.js (preference file)
* second after the vi fail, I quit and then tried to use the command clear

Things got real messy :)

Thanks in advance

**Comment by zusamann** [comment] 2017-05-10 14:30
I'm on the exact same environment. Windows 10, Hyper 1.3.2, git-bash.


![may 10 2017 7-53 pm - edited](https://cloud.githubusercontent.com/assets/12589797/25903829/26da34a0-35bb-11e7-99a1-aef6fe3b2e57.gif)

**Comment by icidasset** [comment] 2017-05-10 14:44
Same here, CMD + K returns `^L` when a command is running, works fine otherwise.

Environment: macOS v10.12.4 using fish shell.

**Comment by saadq** [comment] 2017-05-10 15:05
I think this can be considered a duplicate of the [issue](https://github.com/zeit/hyper/issues/1808) I posted a few hours ago, so might be better to post there and close this one.

**Comment by meoknu** [comment] 2018-01-24 15:34
// for environment variables
    env: {
		TERM: "cygwin"
	},

**Comment by meoknu** [comment] 2018-01-24 15:34
in hyper.js file put
    // for environment variables
    env: {
		TERM: "cygwin"
	},

**Comment by Stanzilla** [comment] 2018-04-24 00:52
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Closed by Stanzilla** 2018-04-24 00:52 UTC

**Comment by tracker1** [comment] 2019-01-25 00:05
@Stanzilla I'm having the same issue, I added the following (noting a similar issue in VS Code and the above... clear is still not working.

```
    shell: 'C:\\Program Files\\Git\\bin\\bash.exe',
    env: {
      CHERE_INVOKING: "1",
      TERM: "cygwin",
    },
    shellArgs: ['-i'],
```
