### ISSUE TITLE
Fonts are Heavier in v2.0

### ISSUE THREAD

**Issue by cgilmore** [zeit/hyper#2856] opened 2018-04-17 17:21 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X 10.11.6
- **Hyper.app version**: 2.0

## Issue
After updating to v2.0 I noticed that the font rendering is heavier than before. I've tried changing the `fontWeight` setting to either `"light"` or "`thin`" and there's no change. Below I've included a screen shot of how Hyper compares to iTerm and Terminal.

<img width="329" alt="screen shot comparing iTerm, Terminal, and Hyper" src="https://user-images.githubusercontent.com/17103088/38885591-0df00ae2-4239-11e8-9130-72e13c857bc6.png">

*(iTerm/Terminal/Hyper)*

Editing other font values in my `.hyper.js` file does seem to work appropriately (`fontSize`, `fontFamily`…), so Hyper is responding to my `.hyper.js`.

Thanks

**Comment by Tyriar** [comment] 2018-04-19 16:54
@sikthought could you try setting it to `100` or `lighter` and let me know if that works? It should take a CSS [`<font-weight>`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) value.

**Comment by francisdb** [comment] 2018-04-20 11:06
there are a bunch of similar tickets like #2505, #2714 and #51

**Comment by ButchMonkey** [comment] 2018-04-20 11:47
I found that my fonts are thinner since updating, and the fontWeight options are having no effect.

**Comment by Tyriar** [comment] 2018-04-20 16:01
From https://github.com/zeit/hyper/issues/2714#issuecomment-370184761 it sounds like `100` works, please confirm 😃

**Comment by francisdb** [comment] 2018-04-20 16:09
The `fontWeight` setting seems to be ignored. Tried hyper, preferences... and then changing `fontWeight` to different values. Restarting hyper but still the same font in use.

Maybe related to old files from a previous release?

**Comment by sikthought** [comment] 2018-04-20 18:10
@Tyriar — Sorry, it doesn't seem to be effecting anything (`'lighter'` also didn't seem to have any effect).

<img width="572" alt="screen shot to show font weight settings and results" src="https://user-images.githubusercontent.com/17103088/39066697-8ce859da-449b-11e8-954f-ca1ebdcbdea1.png">

*(`.hyper.js`/Hyper/Terminal/iTerm)*

**Comment by Tyriar** [comment] 2018-04-20 18:34
@sikthought Hyper in the screenshot is using a different font though (look at the `l`).

**Comment by sikthought** [comment] 2018-04-20 18:53
@Tyriar — Hmmmm…

Here's what I have, tho:

Hyper:
<img width="294" alt="screen shot of Hyper" src="https://user-images.githubusercontent.com/17103088/39068049-930cec54-44a0-11e8-8930-7435f8b9c180.png">

Terminal:
<img width="356" alt="screen shot 2018-04-20 at 13 39 25" src="https://user-images.githubusercontent.com/17103088/39068068-a456af54-44a0-11e8-9d67-6f7e07ad48ee.png">

iTerm:
<img width="388" alt="screen shot 2018-04-20 at 13 39 53" src="https://user-images.githubusercontent.com/17103088/39068081-ae41fef6-44a0-11e8-95d9-ae98303f2232.png">

I also just checked VSCode, it is also set with IBM Plex Mono and is showing what the iTerm and Terminal is showing.

So, it looks like Hyper isn't loading Plex Mono at all and is falling back to Fira Code (I also tried `"IBMPlexMono"` without spaces like in VSC). However, that weight issue still applies:

<img width="351" alt="screen shot 2018-04-20 at 13 48 24" src="https://user-images.githubusercontent.com/17103088/39068364-b1522ef8-44a1-11e8-8ecb-c7f235f096b8.png">

*(all with Fira Code this time)*

**Comment by Tyriar** [comment] 2018-04-20 19:00
Fira Code in VS Code (size 11, weight "100") and Terminal.app (size 11pt, weight "Light") seem fine:

<img width="271" alt="screen shot 2018-04-20 at 11 58 54 am" src="https://user-images.githubusercontent.com/2193314/39068770-4979eb36-4492-11e8-8dcb-bd213ee0ffba.png">

Maybe it's related to Hyper if my screenshot looks fine to you.

**Comment by neeklamy** [comment] 2018-04-20 19:35
@sikthought – I *hate* to do this, but your Hyper config is calling for “IMB Plex Mono”.

**Comment by Tyriar** [comment] 2018-04-20 19:36
Eagle eye @neeklamy 🦅

**Comment by sikthought** [comment] 2018-04-21 06:41
@neeklamy — FML 🤣

Well, it worked itself out in the end anyway. 👍🏼

**Comment by igoticecream** [comment] 2018-04-23 11:55
I'm having this issue, i just can't change the weight of the font since v2.0... it's always bold. Any solution?

**Comment by albinekb** [comment] 2018-04-23 12:59
You can disable updates for stable by adding `releases.hyper.is` to your `hosts` file, you can google how to do this.

**Comment by albinekb** [comment] 2018-04-24 11:46
https://github.com/zeit/hyper/blob/bba14f6324b0fbc0a25601a82ef3652638d43d56/lib/components/term.js#L33

We need to double check that this is actually set and is getting forwarded to xterm 👍

**Comment by chabou** [comment] 2018-05-10 11:34
@rfgamaral Not exactly. My fork has an unmerged PR for huge performance gain. And this is this xterm PR that introduced this regression. But It has been fixed in this PR after my feedback: https://github.com/xtermjs/xterm.js/pull/1327#issuecomment-383811161

I'll update my fork ASAP.

**Comment by rfgamaral** [comment] 2018-05-10 12:17
Huge performance gain? Awesome!

Thanks for the clarification on the issue :)

**Comment by rfgamaral** [comment] 2018-05-21 11:25
@chabou Just wondering if you got to update your fork and consequentially Hyper xterm dependency?

**Comment by jcrben** [comment] 2018-05-29 15:48
I loaded up xterm 3.4.1 and it seems to work pretty well.

For those who stumble across this, don't make my mistake: keep in mind that there's also `fontWeightBold` for text bolded by the shell. Also I imagine this depends on the font - some fonts have light shades and others don't, right? It might be helpful to point users to guidance on picking fonts, loading lighter shades, and so on.

For example, with Menlo from the default fontFamily ("Menlo, DejaVu Sans Mono, Lucida Console, monospace") I tried and only noticed a difference between normal (300) and bold (600). 'Light' seems to be unrecognized - I see the same thing that I see with 'aweklfajw':

'Light':
![image](https://user-images.githubusercontent.com/5614134/40669449-d82aaf3a-631b-11e8-8938-22cc9ed59637.png)

The one I'm using, Source Code Pro, also doesn't recognize 'light' and shows the same weirdness. But it does have different shades for 400 and 500

**Comment by chabou** [comment] 2018-05-29 15:58
Will be fixed by #3032

**Comment by thedonquixotic** [comment] 2018-07-22 09:41
@albinekb Is there a way to block updates of Hyper on Linux? Hosts file is a windows thing right?

**Comment by igoticecream** [comment] 2018-07-30 10:20
Any update on this? even on latest canary the problem is there

**Comment by jcrben** [comment] 2018-08-24 16:36
This discussion in xterm.js seems possibly related: [Font rendering weight heavier than in 2.x  ](https://github.com/xtermjs/xterm.js/issues/1429)

**Comment by zhoupro** [comment] 2018-10-11 01:48
I use FiraCode-Retina.ttf,the font is heavier. After use FiraCode-Light.ttf, All is normal.

**Comment by poige** [comment] 2019-01-04 04:39
Oh, found that issue ticket. Yep, all the fonts are heavy / gravy meanwhile in iTerm2 you can get "retina" mod which makes them even more slim (I wish it would also trim down bold weights a little bit correspondingly but I've planted a ticket in regards already).

All-in-all: Hyper is close to be unusable due to this.

**Closed** 2019-10-10 19:57 UTC
Labels: ⚡ Type: Regression
