### ISSUE TITLE
Can't adjust cursor speed

### ISSUE THREAD

**Issue by r0fls** [zeit/hyper#1236] opened 2016-12-15 22:09 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OSX Sierra
## Issue
The cursor goes much slower in Hyper than the mac Terminal and I can't find any way to adjust it. Is this configurable somewhere?

**Comment by anthonyettinger** [comment] 2016-12-15 23:35
I am not seeing this issue on a mac.

**Comment by r0fls** [comment] 2016-12-15 23:38
@anthonyettinger well, I have adjusted my regular terminal to go faster... I can't recall how I did that. I will see if I can find out exactly what I've done.

**Comment by r0fls** [comment] 2016-12-15 23:41
My key repeat is set to full speed in system preferences but I believe I also modified it with something like (not sure if 0 is the value that I set though, it may have been 1):

```
defaults write NSGlobalDomain KeyRepeat -int 0
```

**Comment by r0fls** [comment] 2016-12-16 03:09
Also the issue is that the cursor speed is not adjustable -- i would expect that from an extensible terminal.

**Comment by funnell** [comment] 2016-12-16 18:59
I'm having this issue using vim on hyper. Using the arrow keys, the cursor moves at an acceptable speed, but holding one of the movement keys results in the cursor moving quite slowly. Terminal and iTerm both don't have this issue.
Perhaps this was intentional, but having the ability to adjust the speed would be great!

**Comment by albinekb** [comment] 2017-01-04 19:26
To read what you set it as:
```sh
defaults read NSGlobalDomain KeyRepeat
```
@r0fls 

I can't reproduce this, my KeyRepeat is set as `1``

**Comment by r0fls** [comment] 2017-01-04 21:20
@albinekb mine is set to 2, but key repeat and delay are set all the way up (see screenshot). 

I realize now that the arrow keys work fine, the issue is actually only with the vim keys (h, j, k, l). This happens both in vim, or in the terminal when using vim mode.

**Comment by funnell** [comment] 2017-01-06 01:58
@albinekb when you hold h,j,k,l or the arrow keys your cursor always moves at the same speed?

**Comment by washt** [comment] 2017-01-13 16:58
I'm having the same issue. h,j,k,l are noticeably slower when using vi, less, or terminal vim mode. Arrow keys respond with the expected speed.

**Comment by pringshia** [comment] 2017-01-31 22:16
This is one of my biggest complaints with Hyper. Also when I hold down a key, for example, L in vim I get the accent flyout flash.

[](
![image](https://cloud.githubusercontent.com/assets/425059/22486808/041edd1a-e7d9-11e6-989c-1d2306644aff.png)
)

**Comment by lyndsysimon** [comment] 2017-02-17 18:35
I was having this problem, but finally resolved it.

I fixed it by turning off Apple's "press and hold" functionality, which is what powers the flyout that @pringshia showed: `defaults write -g ApplePressAndHoldEnabled -bool false`.

You can also adjust the speed with which keys with this command: `defaults write -g KeyRepeat -int 0.02`. The number at the end can be adjusted for personal preference.

**Comment by chadlavi** [comment] 2017-02-19 17:50
nth-ing this problem. @lyndsysimon's solution does work, but it's not cool to have to do this system-wide workaround just to fix a problem that only happens in one app. Neither terminal.app nor iterm2.app have this problem, so it's clearly possible to prevent this from happening. This should be fixed by the hyper team.

**Comment by mikker** [comment] 2017-02-19 20:03
`defaults write co.zeit.hyper ApplePressAndHoldEnabled -bool false` will disable the setting only for Hyper

**Comment by lyndsysimon** [comment] 2017-02-20 14:25
I'm not well-versed enough with Electron to know for sure, but I _think_ this might be what's needed to turn this off by default for Hyper only: http://electron.atom.io/docs/api/system-preferences/#systempreferencessetuserdefaultkey-type-value-macos

**Comment by kristojorg** [comment] 2017-03-29 18:01
I had to do the above from mikker, plus change the key repeat rate for hyper. Like so:

```
defaults write co.zeit.hyper ApplePressAndHoldEnabled -bool false
defaults write co.zeit.hyper InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
defaults write co.zeit.hyper KeyRepeat -int 1 # normal minimum is 2 (30 ms)
```

**Comment by mohammedri** [comment] 2017-08-21 11:58
Having the same issue, @mikker 's solution didn't work for me, couldnt get the press and hold functionality to stop for some reason on my Mac

**Comment by joedborg** [comment] 2018-04-05 08:13
I've got the same issue, but the fixes from @mikker and @kristojorg don't work either.  It's really annoying whilst trying to navigate in Vim.

**Comment by chabou** [comment] 2018-04-05 13:29
@joedborg same issue? which one?
Because fixes that you pointed are intended to fix key repeating, not cursor speed (original issue)

**Comment by joedborg** [comment] 2018-04-06 13:08
@chabou It's that the cursor doesn't blink when it's moving.  E.g when typing or navigating a Vim buffer.  This makes it difficult to see where you are as you have to keep stopping and wait for the first blink.

**Comment by chabou** [comment] 2018-04-06 13:28
@joedborg which Hyper version do you use?

**Comment by chabou** [comment] 2018-04-06 13:39
This is resolved in our canary (our upcoming v2): https://zeit.co/blog/canary#hyper

**Closed** 2018-04-23 00:08 UTC
Labels: 📊 Type: Performance, 😰 Can't Reproduce

**Comment by mcandre** [comment] 2025-04-17 22:58
The link lands on a broken anchor on the Vercel homepage.
