### ISSUE TITLE
Ctrl+C, Ctrl+V shortcuts no longer working in v1.1.0

### ISSUE THREAD

**Issue by cjb5790** [zeit/hyper#1458] opened 2017-01-26 21:34 UTC
- **OS version and name**: Windows 10 Pro v1511
- **Hyper.app version**: v1.1.0

## Issue
Ever since updating to v1.1.0, I can no longer use Ctrl+C to copy or Ctrl+V to paste. The context menu options still work, but the shortcuts do nothing.

**Comment by therealscottcarlow** [comment] 2017-01-27 05:55
Can confirm, keyboard shortcuts for copy/paste are not functional in hyper. It's fine in other terminals.

Running on GNU/Linux with zsh. Hyper version 1.1.0

**Comment by yonson2** [comment] 2017-01-27 07:39
I can also reproduce this issue on my machine.
Running 1.1.0 on a fresh Arch install.

**Comment by maxknu** [comment] 2017-01-27 19:09
Confirming on windows 10, shortcuts do not work.

**Comment by therealscottcarlow** [comment] 2017-01-27 21:03
Actually, should have looked at other open issues. I'm pretty sure this is related to #1452. This issue should probably be merged or closed as a duplicate.

**Comment by atulodra** [comment] 2017-01-30 06:58
Yeah this should be merged to #1452 and hopefully the fix will be applied in v1.2.0  or smth. Paste via Ctrl+C works for me if at first I select all with Ctrl+A and then do the paste shortcut.

**Comment by jacola** [comment] 2017-01-31 02:57
Same problem on W7. I can paste when the turquoise install window is still being displayed, but once the install is done, I cannot paste.

```
Hyper 1.1.0
Electron 1.4.7
win32 x64 6.1.7601
```

**Comment by Seminioni** [comment] 2017-02-01 21:31
Thats why I dont use Hyper anymore...

**Comment by mykytanikitenko** [comment] 2017-02-06 08:40
I have the same problem in Windows 10

**Comment by kleinfreund** [comment] 2017-02-07 08:16
This issue is still around. When will this be fixed? Copying stuff from the command line is kinda critical.

**Comment by renanpvaz** [comment] 2017-02-09 12:15
Same problem here using Windows 8

**Comment by nealoke** [comment] 2017-02-12 13:36
Same problem (windows 10)

**Comment by Kev-CS** [comment] 2017-02-14 03:15
Same problem on Linux Mint 18.1 with zsh

**Comment by Zignd** [comment] 2017-02-14 16:07
Same problem on Ubuntu 16.04.1 LTS with zsh.

**Comment by cjb5790** [comment] 2017-02-15 14:27
This appears to be related to some focus issues. Even though the window has focus, the cursor does not. If I double click a few times on the cursor, focus comes back to the line and the Ctrl+V shortcut works again.

**Comment by AWulkan** [comment] 2017-02-16 21:27
This still doesn't work with Windows 10 in the new Hyper 1.2.1 version. I thought it was fixed.

**Comment by cjb5790** [comment] 2017-02-17 01:44
v1.2.1 actually has resolved this for me on Windows 10.

**Comment by kleinfreund** [comment] 2017-02-17 07:00
> v1.2.1 actually has resolved this for me on Windows 10.

@cjb5790 Can confirm this, too, on Ubuntu. Should be in the changelog.

**Comment by StandardNerd** [comment] 2017-03-25 18:56
I use Hyper version 1.3.1 on Arch Linux and pasting still doesn't work.

**Comment by kleinfreund** [comment] 2017-04-03 09:39
To clarify, <kbd>Ctrl</kbd><kbd>C</kbd> still does not copy but deselect the selected text. <kbd>Ctrl</kbd><kbd>V</kbd> does work.

**Comment by benjamin-rood** [comment] 2017-06-14 23:10
I'm not trying to pile on, but I just want to point out that in **all flavours of Ubuntu 16 when using Zsh**, the only keyboard shortcuts I can reliably get to work in the expected fashion is <kbd>Ctrl</kbd>+<kbd>N</kbd> and <kbd>Ctrl</kbd>+<kbd>R</kbd>. 

Using <kb>Super</kbd> plus the documented shortcuts makes no difference.

I'm a regular user of hyper on macOS where it works exactly as expected, so I know what a great little terminal emulator this is.

Update: Changed scope to properly include currently supported versions of Ubuntu.

**Comment by ppot** [comment] 2017-06-15 01:03
#1509

**Comment by ppot** [comment] 2017-08-15 00:24
closed in #1876

**Closed by ppot** 2017-08-15 00:24 UTC
