### ISSUE TITLE
git bash clear command not working on windows again!

### ISSUE THREAD

**Issue by seriiix** [zeit/hyper#3641] opened 2019-05-09 08:26 UTC
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- **OS version and name**: Windows 10 v1809
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/seriiix/4d1a4750b08f6355f0fb9b727d082e36) with the contents of your .hyper.js**: https://gist.github.com/seriiix/4d1a4750b08f6355f0fb9b727d082e36

## Issue
There was a well-known issue with `clear` command with bash on windows. It seems with v3 there is another issue related to this.

![image](https://user-images.githubusercontent.com/16124619/57438466-3d714500-7259-11e9-92ec-1fa49dc19bb8.png)

When I write `clear` it does clear some upper parts of the terminal but not all of it. I was using this config with v2, and everything was working as expected.
```
shell: 'C:\\Program Files\\Git\\git-cmd.exe',
shellArgs: ['--command=usr/bin/bash.exe', '-l', '-i'],
env: { TERM: 'cygwin' },
```

**UPDATE:** I noticed when I'm facing a situation like the above picture, Resizing the terminal will clear the bottom parts as well.

**Comment by SidneyNemzer** [comment] 2019-05-09 17:50
I suspect this is because Hyper is using the default config now. Hyper 3 uses a different config location and ships with a default config, effectively ignoring settings from the old config. https://github.com/zeit/hyper/issues/3605

**Comment by spences10** [comment] 2019-05-09 19:00
I set up my `.hyper.js` setting from scratch and get the same issue.

![gif](https://user-images.githubusercontent.com/234708/57479348-1a648680-7295-11e9-9941-8305128440e3.gif)

**Comment by SidneyNemzer** [comment] 2019-05-09 19:15
@spences10 can you confirm that you've updated the config in the new location? I'm using Hyper 3 with Git Bash, and `clear` seems to work after I've re-applied my config.

**Comment by spences10** [comment] 2019-05-09 19:47
@SidneyNemzer yes, confirmed. So setting up from scratch would be using the shortcut Ctrl+, to open the configuration file and edit it from there, like you would if you were setting up from scratch (like a fresh install with no preconfigured options).

**Comment by seriiix** [comment] 2019-05-11 05:59
> 
> 
> I suspect this is because Hyper is using the default config now. Hyper 3 uses a different config location and ships with a default config, effectively ignoring settings from the old config. #3605
> 
> Try copying your old config to the new location as described in that issue.

No, as you can see (themes and fonts are not default), I already re-applied my old config.

**Comment by SidneyNemzer** [comment] 2019-05-11 06:48
Do you guys have the Web GL render enabled?

The `clear` command works for me, I'm on Windows 10, Hyper 1.0.2, using Git Bash. I've got the WebGL renderer enabled.

**Comment by seriiix** [comment] 2019-05-11 07:53
Yes. I have WebGL enabled. Sharing ` .hyper.js` file is part of the issue template. You can easily see my config in the mentioned gist. Also, we are talking about Hyper V3, not V1.

**Comment by seriiix** [comment] 2019-05-11 08:13
I noticed when I'm facing this problem, Resizing the terminal will clear the bottom parts as well.

**Comment by spences10** [comment] 2019-05-11 08:28
>Do you guys have the WebGL renderer enabled?

I haven't touched that setting so mine is whatever the default is.

**Comment by rob32** [comment] 2019-05-13 19:44
I did a fresh install today. No issues with clear

My Settings with win10 and Hyper.app version: 3.0.2:

```
    shell: 'C:\\Program Files\\Git\\git-cmd.exe',
    shellArgs: ['--command=usr/bin/bash.exe', '-l', '-i'],
    env: { TERM: 'cygwin'},
```

**Comment by Glenn-Jaya** [comment] 2019-05-14 15:40
Honestly i still can't clear properly.

**Comment by SidneyNemzer** [comment] 2019-05-14 16:53
What versions of Git Bash is everyone using? I just remembered that I'm using an older version because the newer one had issues. (I'll edit this with my version when I get to my home PC).

**Comment by seriiix** [comment] 2019-05-15 07:47
> 
> 
> What versions of Git Bash is everyone using? I just remembered that I'm using an older version because the newer one had issues with Hyper. (I'll edit this with my version when I get to my home PC).

@SidneyNemzer I believe it's not related to git bash because when I force re-render the terminal by minimizing and maximizing the window or resizing it, It'll get entirely clear.

**Comment by sambrainerd** [comment] 2019-05-18 14:25
This is happening to me with Bash on Windows 10. I'm using Hyper 3.0.2. I uninstalled and reinstalled Hyper and the problem still persists.

**Comment by XinRoom** [comment] 2019-07-04 07:56
My main problem is the residue after executing `htop`.

![捕获](https://user-images.githubusercontent.com/32238570/60648731-1909a180-9e73-11e9-900b-5f22a54fc586.PNG)

But when I merged this code change, it worked fine.

- https://github.com/xtermjs/xterm.js/pull/2149

When it detects my input, it draws the full screen.

![image](https://user-images.githubusercontent.com/32238570/60648986-aea53100-9e73-11e9-9154-b490d6b334eb.png)

![image](https://user-images.githubusercontent.com/32238570/60649125-ff1c8e80-9e73-11e9-83f0-4b0f745325f9.png)

Now, if you don't compile by yourself, you need to wait for upstream updates.

**Comment by evsar3** [comment] 2019-10-03 15:55
This doesn't happen if the `windowSize` config is exacly `[540, 380]` (the default value).
Of course, this size is very small for daily operations like edit files and long/wide lists viewing.

**Comment by Stanzilla** [comment] 2019-10-06 19:31
Test again with a canary CI build please

**Closed by Stanzilla** 2019-10-06 19:31 UTC
