### ISSUE TITLE
Alt + click in nano not working

### ISSUE THREAD

**Issue by robindboer** [zeit/hyper#811] opened 2016-10-07 15:52 UTC
When you alt + click in nano you go to the desired line would be nice to have this feature in Hyperterm aswel since it is working in standart terminal on OSX

**Comment by flybayer** [comment] 2016-10-07 17:54
Can you elaborate on how this works? Maybe create a gif showing what it is?

This is probably something that could be added with a plugin.

**Comment by yaycmyk** [comment] 2016-10-13 16:08
Duplicate of https://github.com/zeit/hyper/issues/316

**Comment by matheuss** [comment] 2016-10-13 16:09
Thank you @yaycmyk!

**Closed by matheuss** 2016-10-13 16:09 UTC
Labels: Status: Awaiting Response
