### ISSUE TITLE
[WIN] Webview doesn't work, command not found. 

### ISSUE THREAD

**Issue by stefanivic** [zeit/hyper#1403] opened 2017-01-13 17:22 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/stefanivic/72716e463b639a136c338330d44c58b2
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
-**The issue is reproducible in vanilla Hyper.app**: Yes.

## Issue
Trying to open a webpage on Windows 10 will result in an error depending on the shell type. 

![](https://i.imgur.com/ynQ20Ww.png)

![](https://i.imgur.com/pCPA9Vu.png)

**Comment by DroWnThePoor** [comment] 2017-01-13 22:26
Having this issue on Ubuntu as well, however I get a blank white screen that I can't get out off, have to restart the app.

**Comment by ppot** [comment] 2017-01-14 00:30
@DroWnThePoor  click and then `ctrl+c`

**Comment by KuroTsuto** [comment] 2017-08-08 02:11
Also having this issue. Windows 10, clean install, no configuration options modified.

**Comment by KuroTsuto** [comment] 2017-08-09 23:30
This isn't really elaboration on the issue so much as what I've discovered regarding the implementation... I haven't been able to locate any cases for handling URLs in the cmd or powershell shells - It looks like hyper matches url-formatted strings in the error messages that shells return when you attempt to execute a URL. The patterns which match these errors are in `lib/utils/url-regex.js` and keyed by shell identifier - but there is no pattern for either built-in Windows shell, nor does the file history show there ever was... As a result the `isUrlCommand()` function always returns `null`.

Unless there's special logic for the Windows shells that exists outside the url `utils` files, it looks to me that hyper doesn't currently support URLs in webviews on Windows - if this is the case though, the documentation and website should be updated to reflect as much.

I'll come back to update this issue if I figure out anything interesting.

**Comment by KuroTsuto** [comment] 2017-08-10 00:21
I can confirm at this point that webview itself works fine on Windows, as does the actual mechanism which would open a URL in it.

Looks like the `cmd` and `powershell` cases may have been omitted since the URL matches against the "invalid command" shell error, and in the case of protocol-prefixed URLs, `cmd`'s error message is to the effect of `'https:' is not recognized as an internal or external command, operable program or batch file.` - since this error does not contain the full address, the current mechanism cannot obtain the URL.

The `cmd` regex could match strings in the format of `foo.bar` without the schema prefix - but that would have the unfortunate side-effect of launching webview every time you fat-finger some executable name.

I think there are definitely possible fixes to get URL handling up and running for the Windows shells; quite possibly by examining state or adding meta-data to the relevant actions in order to obtain the URL from user input, which could then be used in the case of a Windows shell-error.

**Comment by ppot** [comment] 2017-08-10 14:46
closed in #2070

**Closed** 2017-08-10 14:46 UTC
