### ISSUE TITLE
Displays issues occur when setting the shell to Bash by default on Windows

### ISSUE THREAD

**Issue by JacobDB** [zeit/hyper#1949] opened 2017-06-19 21:42 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro 64-bit 1703
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/JacobDB/baaf01a2cdfd1ab7d37806a27aa8f1e4
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

When changing the shell to `C:\\Windows\\System32\\bash.exe` in `.hyper.js`, display issues occur, such as text disappearing, lines wrapping too early, or text not being removed. None of this happens when entering "bash" manually in the terminal. Screenshots below.

**Broken (set to use bash `.hyper.js`:**

![image](https://user-images.githubusercontent.com/1123997/27307135-e7fde700-550d-11e7-87d4-1b9179faae2f.png)

![image](https://user-images.githubusercontent.com/1123997/27307167-0f96b256-550e-11e7-89cf-8b6e3ed75ca8.png)

**Working (shell configuration left as default, entering `bash` in the terminal):**

![image](https://user-images.githubusercontent.com/1123997/27307215-4188e0b8-550e-11e7-80d3-acb86a22d63f.png)

**Comment by JacobDB** [comment] 2017-06-20 04:02
This could theoretically be fixed by passing an argument to the call to cmd.exe rather than calling bash directly. For example, it could be possible to set `shell` to `'C:\\Windows\\System32\\cmd.exe' /C bash`, but in practice that causes crashes. I've tired escaping the `/C` as `\/C` as well, still crashes.

**Comment by JacobDB** [comment] 2017-06-20 04:07
Okay, I figured out that I can set `shellArgs` to `\/C bash`, but that results in the exact same issue as described above. Doesn't make a whole lot of sense to me.

**Comment by JacobDB** [comment] 2017-06-21 13:39
Here's a GIF demonstrating the issue a bit more clearly.

![hyper](https://user-images.githubusercontent.com/1123997/27387016-212f0d2e-565d-11e7-990d-76242c9a7b14.gif)

**Comment by CodeTheory** [comment] 2017-06-22 18:17
@rauchg @chabou hterm issue?

**Comment by JacobDB** [comment] 2017-06-22 19:03
Some more detail:

- This has happened on every Windows machine I've ever tried it on (at least 4 separate devices), across multiple versions on Hyper
- I had a similar issue today when using my "workaround" method, but it does seem to be much rarer when invoking bash after launch.

**Comment by chabou** [comment] 2017-06-24 17:31
I'll try to reproduce

**Comment by JacobDB** [comment] 2017-06-27 14:38
Related, sometimes the entry line goes off the end of the page, without any way to fix it other than restarting. Not sure if that's affected by one of my plugins, though.

**Comment by thijsvdv** [comment] 2017-07-11 14:18
@JacobDB I have all the same issues you are describing, with only 2 plugins: 'hypercwd' and 'hyper-snazzy'

**Comment by JacobDB** [comment] 2017-07-11 14:30
@thijsvdv yea, plugins don't seem to be affecting it; I did get it to behaving nicely once with no plugins installed, but upon relaunch (still with all plugins disabled), it freaked out again.

**Comment by JacobDB** [comment] 2017-07-26 00:52
@chabou any status update on this?

**Comment by chabou** [comment] 2017-08-14 13:07
Can you try to resize Hyper before typing?

From your gif, my hypothese is:
`cmd` fit correctly hterm/hyper size at startup. After that, you launch `bash` and everything is ok.
`bash` doesn't fit correctly at startup. Resizing window could be a workaround.

**Comment by JacobDB** [comment] 2017-08-14 13:24
@chabou after a brief test that does seem to work. I'll try it out while I work today and report back if anything weird continues to happen.

**Comment by JacobDB** [comment] 2017-08-14 13:50
@chabou after a bit more testing, this doesn't really seem to be an effective workaround. It solves it for one  line, sometimes, but then continues being wonky with subsequent lines.

**Comment by chabou** [comment] 2017-08-14 14:26
@JacobDB So you have to resize window before each new line! Easy fix 😝  
Thank you to have tested it. We'll try to find a real solution/workaround. 😥

**Comment by nesl247** [comment] 2017-08-14 14:35
I have to resize when starting hyper to get my shell prompt to display correctly, so there's a bunch of stuff broken when using bash/fish/etc. by default I think.

**Comment by chabou** [comment] 2017-08-14 16:09
@nesl247 This issue concerns Windows. Are you using `fish` on Windows?

**Comment by nesl247** [comment] 2017-08-14 16:25
Yes via WSL.

**Comment by chabou** [comment] 2017-08-14 16:39
@nesl247 thank you for your feedback!

**Comment by Mohamed3on** [comment] 2017-08-24 11:34
Duplicate of #283 ?

**Comment by chabou** [comment] 2017-09-02 10:19
I think this is not exactly the same than #283.
Seems specific to Windows.

@nesl247 @Mohamed3on Can you test this issue with our last v1.4.2 release?

**Closed** 2018-04-23 00:02 UTC
Labels: 🐛 Type: Bug, 🖼 Platform: Windows
