### ISSUE TITLE
Themes Not Working Fully

### ISSUE THREAD

**Issue by SkyHacks** [zeit/hyper#294] opened 2016-07-19 18:31 UTC
If I add a plugin for a theme like "hyperterm-oceanic-next" or "hyperterm-spacegray" in the .hyperterm.js file, it will download the package and refresh the terminal but only some of the styles are applied. I have tried several themes and they all seem to have the same issue. The background colors are applied but none of the font colors seem to work. Any advice?

**Comment by insanityfarm** [comment] 2016-07-19 22:39
I think I experienced this myself but when I opened a new window the theme was correctly applied to it. Is that the same thing you're seeing? So the problem is specifically that the theme is not applying to the _current_ window, if that helps anyone troubleshoot.

**Comment by SkyHacks** [comment] 2016-07-19 22:48
I'm sorry I forgot to mention that I tried that as well. Unfortunately, it didn't resolve the issue for me.

**Comment by zanedev** [comment] 2016-07-21 05:34
Seeing same thing theme not applied, in fact everything went monochrome and can't get back to original colors removing the themes from the plugin list.

**Comment by zanedev** [comment] 2016-07-26 17:23
Still a problem with latest  0.7.0 (0.7.0.26)

**Comment by mhocalc** [comment] 2016-11-29 14:02
I'm having the same issue with `hyperterm-atom-dark`. Tried restarting various times but nothing changes.

**Comment by alo** [comment] 2016-12-13 11:34
Same problem with hyperseti, hyperterm-monokai, ... always same font

**Comment by haluvibe** [comment] 2017-01-23 04:38
Same problem with hyper-seti - actually nothing changes for me. Here is my .hyper.js file which is the default with hyper-seti added....

```
module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 12,

    // font family with optional fallbacks
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BLOCK',

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // set to `true` if you're using a Linux set up
    // that doesn't shows native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: '',

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    shell: '',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false,

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg

    // theme overrides
    themeOptions: {
      accentColor: 'lightBlue'
    }
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  // add the theme
  plugins: [
    'hyper-seti'
  ],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
};
```

**Comment by haluvibe** [comment] 2017-01-23 09:59
I just realised my themes aren't working in iTerm either, so must be something other than Hyper causing my issue. Maybe this will help others?

**Comment by jacoboAR** [comment] 2017-03-15 16:27
I have the same problem. Only the background-color changed. Any solution?

Hyper 1.3.1
Windows 10 x64

**Comment by lucamezzalira** [comment] 2017-03-23 22:10
I added on `.bash_profile` the command `export CLICOLOR=1`
then I reload Hyper and it was working

**Comment by jacoboAR** [comment] 2017-03-25 10:40
Thanks. I'll try it

**Comment by CyrisXD** [comment] 2017-03-31 07:34
I'm having this same problem. 

Windows 10 x64

Can someone please let me know if you've gotten it fixed and how I can achieve that?

**Comment by jacoboAR** [comment] 2017-03-31 08:17
It doesn't work. Sorry

**Comment by chabou** [comment] 2017-04-13 23:46
Can you give a specific theme name and a screenshot?

**Comment by leojcollard** [comment] 2017-05-30 03:00
I had a similar problem and it turned out that Hyper was not the issue; both my regular Terminal.app and Hyper did not properly show font colours. The solution provided [here](https://github.com/lysyi3m/osx-terminal-themes/issues/1/#issuecomment-148635036) fixed the issue for me. It turns out my `~/.bash_profile` file had gotten messed up somehow. Hope this helps someone!

**Comment by jrichard8** [comment] 2017-08-31 08:51
You have to change the default shell to : 

_shell: 'C:\\Windows\\System32\\bash.exe',_

Enjoy

**Comment by schmittyjd** [comment] 2017-10-09 16:31
I am currently having a similar issue. Tried changing themes to `hyperterm-solarized-light` and the background colors were applied but my font colors haven't changed from their previous `atom-dark` values. Here is a screenshot.... ouch my eyes

<img width="708" alt="screen shot 2017-10-09 at 9 29 54 am" src="https://user-images.githubusercontent.com/3849309/31348480-9feb0a0a-acd4-11e7-8e9f-15c931048c8c.png">

**Comment by albinekb** [comment] 2017-10-09 20:26
What version of hyper? @schmittyjd

**Comment by schmittyjd** [comment] 2017-10-10 19:56
@albinekb version 2.0.4

**Comment by kingmomo** [comment] 2017-10-12 14:05
I tried [hyper-one-light](https://github.com/andrepolischuk/hyper-one-light) and this is what it looks like
![hyper-one-light](https://user-images.githubusercontent.com/10886770/31500012-5567eec8-af34-11e7-8618-0ffa993c1b9c.png)

This is my hyper version:
![hyper-vresion](https://user-images.githubusercontent.com/10886770/31500051-77c671a6-af34-11e7-924b-6e348da7081c.png)

I also did what @leojcollard mentioned but it didnt help.

I personally prefer light theme, but stuck using default dark theme that hyper comes with.

Any pointers to what the issue might be is much appreciated.

**Comment by kingmomo** [comment] 2017-10-23 15:25
Seeing the same issue on Hyper 2.0.4 as well.
<img width="427" alt="screen shot 2017-10-23 at 10 20 03 am" src="https://user-images.githubusercontent.com/10886770/31897585-d5510990-b7e4-11e7-846b-f09c3cd7ca1a.png">

**Comment by kingmomo** [comment] 2017-12-01 15:39
Update: the reason none of the themes were working was because of "hyper-border" plugin.
Removing it fixed my theme. 

Raised an issue on hyper-border https://github.com/webmatze/hyperborder/issues/38

**Comment by webmatze** [comment] 2017-12-04 12:46
Author of [hyperborder](https://github.com/webmatze/hyperborder) here. Thanks for the reports. I will investigate this issue.

**Comment by webmatze** [comment] 2017-12-05 14:33
@kingmomo I looked into the issue with your *hyper-one-light* theme together with the **hyperborder** plugin.

For **hyperborder** to work correctly it is essential to set a **backgroundColor** in your `.hyper.js` config. So **hyperborder** will use that value to set your background.

When **hyper** generates that configuration for the first time, it always sets the **backgroundColor** to `#000` so it will be **black** by default.

When a theme uses a different background color, then you have to explicitly set your `backgroundColor` value to the color used in that theme to work together with **hyperborder**.

**hyper-one-light** uses `#fafafa`.

So it is not really an error but just the way **hyperborder** works as it uses background gradients and colors to generate the desired effects.

But I am not sure if this solves the problem of this issue, as not everyone here seems to use **hyperborder**.

**Comment by kingmomo** [comment] 2017-12-05 18:02
@webmatze you are right, my issue with theme+hyperborder may not be the same as others in this thread. It just might be a case where the final outcome looked similar. 

And thanks for the info on bg color with your plugin.

**Comment by kuntashov** [comment] 2018-01-12 20:00
I'm faced with the same issue using 'hyper-solarized-light' ver. 0.1.2 plugin.

See screenshot: 
* on the left is Hyper with 'hyper-solarized-light' plugin enabled: background is from solirized theme but font colors are wrong (it is default colors);
* on the right is xterm with Solirezed theme - all colors are just as expected

![screenshot_20180112_233716](https://user-images.githubusercontent.com/1042299/34892780-fa841762-f7f3-11e7-967a-a98c779813d2.png)

My environment:

- [x] OS: Linux Mint 17.3 Rosa with Xfce 4.12
- [x] Hyper 2.0.0-canary.9 (canary)
- [x] Plugins: 
  * hyper-solarized-light (0.1.2),
  * hyper-native-window-decoration (0.0.4),
  * hyper-tab-icons (2.1.0),
  * hypercwd (1.1.1)

How can I help to localize the reasons of this issue?

**Comment by kingmomo** [comment] 2018-01-12 20:49
@kuntashov remove all other plugins and keep only "hyper-solarized-light" and see if you still have the issue. Then add one plugin at a time. Most likely one the plugins is clashing with hyper-solarized-light and causing the issue.

**Comment by kuntashov** [comment] 2018-01-12 20:58
@kingmomo I've removed all plugins except hyper-solarized-light and restarted hyper but colors still are wrong

**Comment by kingmomo** [comment] 2018-01-12 21:59
@kuntashov im not sure what the issue is then. Have you tried other actions mentioned in this thread? Like setting the shell in your .hyper.js, that seems to have worked for few.

**Comment by kuntashov** [comment] 2018-01-12 22:47
I've checked several different themes from the [bnb/awesome-hyper](https://github.com/bnb/awesome-hyper#themes):

  * an-old-hype 
  * hyper-adventure-time 
  * hyper-atom-dark-transparent 
  * hyper-aurora
  * hyper-ayu
  * hyper-ayu-light
  * hyper-ayu-mirage

up to 'hyper-monochrome' and all they work as expected.

Then I compare `index.js` from 'hyper-solarized-light' and other themes.
Most of the themes [use object map to define colors](https://github.com/poeti8/hyper-theme/blob/master/index.js#L13), i.e.

```javascript
const colors = {
    black: '#000000',
    red: '#ff0000',
    // etc ...
}
```

And  'hyper-solarized-light' [uses array do define colors](https://github.com/ghosh/hyper-solarized-light/blob/master/index.js#L6), i.e. 

```javascript
const colors = [
  backgroundColor,
  '#dc322f', // red
  // etc ...
]
```
I've just changed colors const from array to color map object ([kuntashov/hyper-solarized-light/commit/f63c8d8](https://github.com/kuntashov/hyper-solarized-light/commit/f63c8d8849335458291ae3b391180216d99a2f44)) and then I've got what I want (hyper is on the left and xterm on the right):

![screenshot_20180113_023501](https://user-images.githubusercontent.com/1042299/34898034-71a6597a-f80a-11e7-91b5-67493f8e4541.png)

In `~/.hyper.js` I can see comment before color map:

```javascript
    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
```
I'm not familiar with Hyper architecture and can't figure out what difference between array and map object in context of defining theme colors.

Can anyone help to figure out does it 'hyper-solarized-light' bug or something wrong with Hyper when colors defined as array 'including the 6 x 6 color cubes and the grayscale map'?

**Comment by methodbox** [comment] 2018-01-16 02:28
I too am having this issue. Trying Hyper for the first time, new install, one plugin - hyperterm-monokai - no dice.

The background changed to grey (vs. black) and that's it - still stupid white text, no highlighting, etc.

I installed this app to check out the customization options - was hoping it would be like Atom where there are names & classes assigned to every element, making it easy to target in JS and CSS only to find out this is not the case.

Not really sure how you can call it highly customizable if you need to insert target IDs or classes just to change the text color. It's nifty that you can add plugins so easily, but they don't seem to work correctly, and I'm not really looking for exploding text or animations.

I really just want to be able to customize the different context of texts like my name in terminal, SSH, SSH, file types, folder types, etc. but it seems maybe this isn't the write app for that.

**Comment by kuntashov** [comment] 2018-01-16 21:19
@methodbox 
> As an example, this is .hyper.js viewed in Vi:

Hyper is not responsible for syntax highlighting in text editors.
Are you sure you've enabled syntax highlighting in Vi (`set syntax=on`)?

All other things you are described are offtopic for this issue.

Please try to be more patient and constructive. 
I've managed to solve all issues I wrote about recently and now I see that Hyper is really great software.

**Comment by methodbox** [comment] 2018-01-17 01:14
@kuntashov

1) The other issues are absolutely on-topic. The same thing is still happening.

2) I was trying to be constructive by proposing a sane way of customization (classes and ids for each element and a separate element for dynamically typed text a la Atom).

3) Syntax highlighting is enabled in Vi and works in Terminal.

Again, the theme gets applied, it doesn’t work other than changing the background color. ALL text is white. There’s really no theme at all.

I am going to try my hand at isolating the cause when I get some free time.

But I still think addressing the fact that customization without writing a theme as a plugin is sorely lacking when the app itself is dynamic HTML markup without basic classes and ids on the primary elements.

There are classes on many elements but not, for example, on an x-row generated element.

There is no element separating typed text from the static shell text of user@host. It’s bad design.

**Comment by rafmjr** [comment] 2018-01-21 05:40
@leojcollard thanks a lot! Adding the following to my **~/.bash_profile** did the trick for me:

**export** PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
**export** CLICOLOR=1
**export** LSCOLORS=ExFxBxDxCxegedabagacad
**alias** ls='ls -GFh'

Then you do you **source ~/.bash_profile**, reload hyper and my life is back in technicolor :)!

**Comment by chabou** [comment] 2018-04-16 22:00
Please retry with our v2 and open a new issue if it is relevant

**Closed by chabou** 2018-04-16 22:00 UTC
Labels: help wanted, 🐛 Type: Bug, 👀 Awaiting Response, 😰 Can't Reproduce

**Comment by AriPal** [comment] 2018-06-30 19:39
Here is a solution that worked for me. What seemed to be the problem lies in `.bashrc` file, and since I cannot exactly identify what command causes the theme error, I decided to restore the whole file. 

Restore .bashrc file, added by [souravc](https://askubuntu.com/questions/404424/how-do-i-restore-bashrc-to-its-default). 
1. `/bin/cp /etc/skel/.bashrc ~/` 
2. `source ~/.bashrc`

Now that you've restored the file, the next step is to follow what @lucamezzalira has commented. 

> I added on .bash_profile the command export CLICOLOR=1
> then I reload Hyper and it was working


Remember, after you've restored .bashrc, remember to update it by running `source .bashrc`, exit and re-enter the terminal.

**Comment by methodbox** [comment] 2018-06-30 23:47
What you guys are referring to is bash and LS colors; they work in and out of Hyper (theoretically).

If Hyper is only allowing customization through the .bash files then it isn’t really customizing Hyper at all; you can do this in the native terminal.

For example, on macOS install the Monokai.terminal theme and then set this in ~/.bash_profile:

```bash
alias ls=‘ls —color=auto’
```

Then source the .bash_profile. You’ll have colorized output in LS.

If not, the LSCOLORS value above will set your BSD colors in bash.

This isn’t the same as being able to manage customization by managing this through CSS (like Atom) ... which is kind of the whole point of Hyper, isn’t it?

**Comment by bryonion** [comment] 2018-07-11 16:46
This fixed the issue for me. 
https://github.com/zeit/hyper/issues/2942

**Comment by sfskysf** [comment] 2020-12-24 17:53
I'm having the same problem tried all fixes over the past 90 minutes. time to remove this garbage!

**Comment by ErikHoffmanWave** [comment] 2021-02-22 05:53
Tried everything in this thread and nothing worked.

**Comment by LabhanshAgrawal** [comment] 2021-02-22 08:18
@ErikHoffmanWave can you elaborate a bit on the issue you're facing, there seems to be lot of different things described here.

**Comment by sudocraftio** [comment] 2021-09-27 18:36
Latest put in ~/.zshrc

export CLICOLOR=1

**Comment by itsmechyanit** [comment] 2022-08-31 16:39
Yes, it is not working.

The font colours are not changing

Chyanit

**Comment by Luvous** [comment] 2024-05-26 01:47
Is there an actual useful way of solving this? nothing in here is working

**Comment by ramarivera** [comment] 2025-04-28 14:36
any update?
