### ISSUE TITLE
Vim not detecting terminal colors

### ISSUE THREAD

**Issue by samirotiv** [zeit/hyper#1583] opened 2017-02-25 07:37 UTC
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X 10.11
- **Hyper.app version**: 1.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default file, with solarized theme installed
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Hi,

I have a fresh install of Hyper, and I've installed the solarized light theme. Everything works perfectly except Vim. I have the solarized light theme installed on vim as well - the 16 colour version.

My Hyper terminal shows up correctly in the solarized colors, but Vim doesn't seem to be reading the colors correctly. I confirm my configuration is correct because it works perfectly in iTerm.

Here are two screenshots:

![screen shot 2017-02-25 at 12 43 12 pm](https://cloud.githubusercontent.com/assets/4405935/23329250/060dfe04-fb5b-11e6-9840-6f615a07ee9b.png)
![screen shot 2017-02-25 at 1 06 03 pm](https://cloud.githubusercontent.com/assets/4405935/23329263/32175608-fb5b-11e6-8354-8160262ef775.png)

I couldn't find any documentation, and couldn't find this in issues.

Best,
Samir.

**Comment by jameslintaylor** [comment] 2017-02-25 15:53
possible duplicate of [155](https://github.com/zeit/hyper/issues/155)?

**Closed** 2018-04-24 00:08 UTC

**Comment by Delfador42** [comment] 2020-12-04 04:29
Here are 2 workarounds: https://github.com/vercel/hyper/issues/155#issuecomment-738556676
