### ISSUE TITLE
Use `.json` instead of `.js` for config

### ISSUE THREAD

**Issue by leo** [zeit/hyper#289] opened 2016-07-19 15:47 UTC
In the beginning, @rauchg suggested https://github.com/zeit/hyperterm/issues/14 as a technique for allowing devs to extend HyperTerm using plugins. Within this issue, he also suggested that the file should be called `hyperterm.json` (and not `*.js`, like it's currently the case).

I have no idea why we made the switch to `.js`, but the reason is probably related to the comments: In a JSON file, everything needs to be data (so no space for comments outside of the key/value pairs).

However, in my opinion, we should still use JSON instead, because it leaves much less room for errors.

**Comment by nfcampos** [comment] 2016-07-19 16:18
yeah the reason for going with `js` was to allow comments

**Comment by leo** [comment] 2016-07-19 16:22
Forgot to add that the comments are now part of the documentation on [the site](http://hyperterm.org). So technically, I don't think they need to be in there as well.

**Comment by cuth** [comment] 2016-07-19 16:52
The `js` file allows you to do fun things. You could use the date or `Math.random()`. Also, the multi-line template literals are nice for CSS.

Better yet, why not export a promise instead of an object? Then you can make async calls before determining your config values.

**Comment by leo** [comment] 2016-07-19 16:58
@cuth In my opinion, these things don't belong in there. It's what local plugins are made for. Of course we could just let the user to everything everywhere, but if you ask me, we should be a little more explicit when it comes to defining where to put thing.

Why? Because it avoids a lot of errors, like I said.

**Comment by hharnisc** [comment] 2016-07-20 14:30
Comments are a huge win here, and moving to a `.json` format feels like a regression there. However it feels like the static-ness encourages people do either build a plugin or update the core. So it's kind of a trade off between flexibility and predictability. It seems odd that I would need anything other than a parser to debug a config file, but hey, I could be totally wrong about this.

If comments are enough why not use **YAML**? It seems to be right in the sweet spot for what we're trying to accomplish.

**Comment by sindresorhus** [comment] 2016-07-20 14:39
I think having the config as JavaScript is awesome. There's also no real value of having the config be statically serializable anyways.

-


> If comments are enough why not use YAML?

YAML is a horribly over-spec'd (80 pages! JSON is 1 page) and bloated format. If you just want comments with JSON, check out [`strip-json-comments`](https://github.com/sindresorhus/strip-json-comments).

**Comment by leo** [comment] 2016-07-20 14:55
> YAML is a horribly over-spec'd (80 pages! JSON is 1 page) and bloated format. If you just want comments with JSON, check out strip-json-comments.

Exactly! No YAML, please... 🙈 


> There's also no real value of having the config be statically serializable anyways.

Let's assume there will be a feature that lets you set a certain config key to a specific value (like with `git config`): We would then have to parse the JS file and replace certain values with others. In my opinion, that's way too hacky compared to just reading a JSON file into an object, modifying it and then stringifying it back out.

Also think about requiring packages, for example: We can't just allow people to require packages and the next time they'll move their HyperTerm config to a different device, the only thing HyperTerm will do is install the plugins, not randomly required packages. Yes, we could probably implement that! But like I said, this looks way too hacky in my mind.

All in all, simply staying with `.js` spawns hundreds of edge cases for which would have to find solutions, fix bugs and answer questions because of some users who're doing the weirdest, most complicated stuff right in their HyperTerm config file.

**Comment by iamstarkov** [comment] 2016-07-28 10:06
config in js is better than in json — more flexible, plus comments

**Comment by iamstarkov** [comment] 2016-07-28 10:08
> In my opinion, that's way too hacky compared to just reading a JSON file into an object, modifying it and then stringifying it back out.

I guess you can always parse `require('~/.hyperterm.js').config`

**Comment by leo** [comment] 2016-07-28 10:10
@iamstarkov Sure! But what about saving it? 😉

**Comment by iamstarkov** [comment] 2016-07-28 10:28
[config-hyperterm](https://github.com/hemanth/config-hyperterm) is doing that as well

**Comment by iamstarkov** [comment] 2016-10-13 00:36
shall we keep configs in `.js` and close this issue?

**Comment by rauchg** [comment] 2016-10-13 00:41
Yes. The reason for `.js` is a very practical one. Much easier to make changes than JSON, comments, etc.

Even in terms of error handling there's no advantage to using .json. In my anecdotal experience, it's in fact much easier to make a mistake when hand-writing JSON.

In both cases if the file fails to parse / evaluate we have to display a message and let the user know, so there's no change there.

**Closed by rauchg** 2016-10-13 00:41 UTC
Labels: Status: Awaiting Response, Type: Enhancement

**Comment by leo** [comment] 2016-10-13 07:33
Agreed!

**Comment by dkfiresky** [comment] 2017-02-28 17:49
Why if you store your configuration in `.js` file, Hyper simply crashes and resets the configuration when you use `require` statements within the configuration?

Just interesting how this behavior is misleading.
