### ISSUE TITLE
Possible to improve borders?

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#245] opened 2016-07-18 16:41 UTC
![image](https://cloud.githubusercontent.com/assets/13041/16922716/b0284212-4ccb-11e6-9ef9-ecbad1c8352a.png)
![image](https://cloud.githubusercontent.com/assets/13041/16922769/e2c8ef96-4ccb-11e6-9da7-3e9b669916bc.png)
![image](https://cloud.githubusercontent.com/assets/13041/16922808/06aa23e4-4ccc-11e6-8ea0-eabec42b4a15.png)
![image](https://cloud.githubusercontent.com/assets/13041/16922821/137c43d6-4ccc-11e6-83d2-19fcf796acf5.png)

I notice our borders are kinda funky. I imagine there's something we can do about this, possibly related to applying the border to a surrounding element, since we apply the background color to the body.

**Comment by alanhussey** [comment] 2016-07-20 20:05
I played around a bit with [`background-clip`](https://css-tricks.com/transparent-borders-with-background-clip/). Applying it to `.hyperterm_main` didn't seem to do anything, but `.tab_tab` had some effect (but still not fixed).

**Comment by cilice** [comment] 2016-07-21 07:13
Could be related to this https://github.com/zeit/hyperterm/issues/332, which also has a PR https://github.com/zeit/hyperterm/pull/333

**Comment by itswil** [comment] 2016-07-21 11:00
So I think I have a very crude (not to be merged) fix: https://github.com/zeit/hyperterm/compare/master...itswil:fix-rounded-corners?expand=1
Screenshot: http://i.imgur.com/7cNwgTu.png

I believe the issue is that no`border-radius` value is able to match the macOS border-radius, so it keeps being cut off.
So instead of using a border, I gave `<body>` a background color and padded all the elements with `1px`. Is this solution ok? Also, any elements that touch the corners, will need a `border-radius: 5px`.

The positioning of the elements needs more work.

**Comment by chabou** [comment] 2017-04-13 22:47
Fixed by #333

**Closed by chabou** 2017-04-13 22:47 UTC
Labels: Status: Help Wanted, Type: Enhancement
