### ISSUE TITLE
Tab title switching between two different titles

### ISSUE THREAD

**Issue by tjgillies** [zeit/hyper#948] opened 2016-11-01 17:23 UTC
When I run emacs [spacemacs]  in the terminal, the tab title switches between bash and emacs, back and forth. It's kind of annoying/distracting

-

Hyper 0.8.3
Electron 1.4.0
darwin x64 15.4.0

**Comment by OJFord** [comment] 2016-11-09 14:35
Duplicate of #912; solved by #892.

**Comment by ppot** [comment] 2016-11-17 23:30
@matheuss Can be closed since #892

**Comment by matheuss** [comment] 2016-11-17 23:33
Thank you @ppot 😄

**Closed by matheuss** 2016-11-17 23:33 UTC
Labels: Is Duplicate
