### ISSUE TITLE
Rendering text with blending colors?

### ISSUE THREAD

**Issue by joannesalfa** [zeit/hyper#2933] opened 2018-04-25 09:46 UTC
I'm too lazy to fill the text here, but I can post 2 pictures to compare:

![alt text](https://i.imgur.com/zBFUiOx.png "Hyper 2 blend colors")

![alt text](https://i.imgur.com/XEVhR1J.png "Powershell blend colors")

First one, it looks is not blending the colors, it seems separated.

Second one, it does blend the colors.

**Comment by albinekb** [comment] 2018-04-25 09:57
Duplicate of https://github.com/zeit/hyper/issues/1968

**Closed by albinekb** 2018-04-25 09:57 UTC
