### ISSUE TITLE
Help with 256 color support on Windows

### ISSUE THREAD

**Issue by LukeFlynn** [zeit/hyper#1968] opened 2017-07-02 04:47 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS 10.0.15063 and Windows**: 
- **Hyper.app 1.3.3**: 
- **Link of my [.hyper.js](https://gist.github.com/LukeFlynn/e621f0cc039bbf1f772b54939cfa01bf)**
- **The issue is reproducible in vanilla Hyper.app**:

## Issue

Hi,

I would like to be able to use full 256color in Hyper. Setting the env variable TERM to xterm-256color displays colors perfectly.. but it breaks the functionality of the "clear" command. Is there some other way I can accomplish displaying the colors properly while retaining functionality of clear?

**Comment by lijunle** [comment] 2017-07-21 07:43
Another issue with `TERM=xterm-256color`, the vim will mess the screen content with the editing content.

**Comment by sanguine8082** [comment] 2017-08-01 13:57
Windows Command Prompt does not support 256 colors :cry: 

You will need to use a different terminal, like Git For Windows or Msys2 to get 256 color support, and then point hyper.js to their respective executable.

**Comment by thisguychris** [comment] 2017-08-14 19:51
I thought they supported 24-bit already?

related links:
https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/6509361-provides-support-for-ansi-colors-like-in-bash

https://blogs.msdn.microsoft.com/commandline/2016/09/22/24-bit-color-in-the-windows-console/

**Comment by sanguine8082** [comment] 2017-08-15 03:16
I think Windows 10 might have support, but not before that.

**Comment by Xapphire13** [comment] 2017-08-23 01:44
Windows 10 *does* support 256 colors as of TH2, see [here](http://www.nivot.org/blog/post/2016/02/04/Windows-10-TH2-(v1511)-Console-Host-Enhancements)

When running [AnsiColors256.ans](https://github.com/Maximus5/ConEmu/blob/master/Release/ConEmu/Addons/AnsiColors256.ans) via `type AnsiColors256.and` in PowerShell I get:

![image](https://user-images.githubusercontent.com/3392349/29595043-d5094f16-8769-11e7-9cf1-3146a8f88f50.png)

But running the same command in Hyper I get:
![image](https://user-images.githubusercontent.com/3392349/29595053-dffbfac2-8769-11e7-902b-f48345d310ed.png)

**Comment by tdurand** [comment] 2018-01-22 22:55
Same issue here, is a fix underway ?

I have issue with this git config for diffs

```
[color "diff-highlight"]
        oldNormal = red bold
        oldHighlight = red bold 52
        newNormal = green bold
        newHighlight = green bold 22
```

![terminaldiff](https://user-images.githubusercontent.com/533590/35248769-233bb996-ffae-11e7-9b40-95861cc57efe.jpg)

**Comment by chabou** [comment] 2018-01-23 09:22
@tdurand can you confirm me that you are on Windows?

**Comment by chabou** [comment] 2018-01-23 09:30
Using GitBash with Hyper (2.0.0-canary.10), this is what I get when running AnsiColors256.ans :
![image](https://user-images.githubusercontent.com/4137761/35267957-2a97cf02-0028-11e8-9258-6814f20c229d.png)

And WTF, my mouse pointer goes UNDER the grey zones... 😱 

(It works well on macOS)

**Comment by tdurand** [comment] 2018-01-23 10:07
Yes, i'm on Windows 10 using WSL with Ubuntu. And the color works well if you use the powershell terminal, so I'm pretty sure it's an issue of hyper.

**Comment by chabou** [comment] 2018-01-23 10:27
Yes, an issue with Hyper (but only on Windows, from my testing).

**Comment by kaminooni** [comment] 2018-02-22 12:09
I ran into the same problem. And since I use vim (with a lot of color schemes) for coding, it makes hyper almost unusable 😞

![shot](https://user-images.githubusercontent.com/2164861/36537826-525ce60e-17e2-11e8-9874-de8c17564528.png)

**Comment by dougmaitelli** [comment] 2018-02-26 09:46
Even worse here:

![image](https://user-images.githubusercontent.com/1277391/36663583-5b6cdf76-1ae2-11e8-992e-3ffcd110d3cb.png)

**Comment by Macmee** [comment] 2018-02-27 06:37
any movement on this issue?

**Comment by dougmaitelli** [comment] 2018-02-27 06:54
I did a lot and research, testing. It seems it is not a Hyper issue. It is a node-pty issue because of a limitation in the way they interact with processes on Windows. So basically it seems to be still a Windows limitation.

You can even confirm this because the integrated shell in vs code has exactly the same issue, and they even use winpty instead of node-pty.

**Comment by scottbilas** [comment] 2018-02-27 15:11
ConEmu supports 256 and true color. Needs a bit of config.

https://conemu.github.io/en/Xterm256Colors.html

It works via a hook dll that monitors direct calls to write to the console, processing escape codes etc. There's also quite a lot of special case code, including detection of the vim process and powershell. 

https://github.com/Maximus5/ConEmu/blob/master/src/ConEmuHk/hkConsoleOutput.cpp

**Comment by szmarczak** [comment] 2018-04-14 15:43
Any news?

**Comment by florisvaneck** [comment] 2018-04-14 20:07
Update on this please! Really harming my Hyper experience on Windows!

I am using the hyper-solarized-dark-highcontrast theme to make it slightly less worse.

**Comment by albinekb** [comment] 2018-04-16 08:25
This is a windows issue @florisvaneck, not much we can do.

**Comment by szmarczak** [comment] 2018-04-23 13:26
Hyper 2.0.0 stable:

![image](https://user-images.githubusercontent.com/36894700/39129182-1d6fe930-470a-11e8-849d-b4d61d696428.png)

**Comment by Stanzilla** [comment] 2018-04-23 17:30
That's https://github.com/xtermjs/xterm.js/issues/484

**Comment by Tyriar** [comment] 2018-04-24 18:13
@Stanzilla this is not actually xtermjs/xterm.js#484, that's for truecolor (16 million) color support. 256 color support in Windows is due to winpty: https://github.com/Microsoft/vscode/issues/45693

**Comment by Xapphire13** [comment] 2018-06-12 00:49
@dvf, nope the issue is still repro

**Comment by panda2134** [comment] 2018-07-01 10:50
repro again on windows 10 build 1803 with hyper 2.1.0-canary2

**Comment by jasonxoc** [comment] 2018-07-14 23:36
Ohh I should have searched for this issue before taking the time to make this: 
![hyperjs-colors_messed_up](https://user-images.githubusercontent.com/595326/42729150-d9dc13b4-8783-11e8-910d-629fadf85664.jpg)

Man, windows terminal emulation sucks _SOOO_ bad. Nothing but issues with drawing, color support, mouse support with tmux and vim. ... Hoping I can finally get gnome-terminal to work at some point.

**Comment by Josema** [comment] 2018-08-21 20:35
Any news?

**Comment by monsterkodi** [comment] 2018-08-22 08:00
This is related news: https://github.com/Microsoft/console/issues/57
A lot of console problems will probably be solved this fall/winter.

**Comment by Tyriar** [comment] 2018-08-22 18:00
More specifically for hyper: https://github.com/Microsoft/node-pty/issues/216

**Comment by monsterkodi** [comment] 2018-08-22 18:42
Better 30 years late than never :-)

**Comment by printempw** [comment] 2018-09-07 05:35
Same issue here, Hyper 2.0.0 on Windows 10 1803. Any news?

![screenshot](https://i.loli.net/2018/09/07/5b920de50834d.png)

**Comment by Tyriar** [comment] 2018-09-08 20:37
@printempw I'm working on Microsoft/node-pty#216 which is expected to fix this, ETA is still a while off though.

**Comment by dp97** [comment] 2019-01-01 14:39
Pardon me, but why SSH to virtual machine also doesn't display colors?
I don't think it's WSL specific bug.

![untitled](https://user-images.githubusercontent.com/20670448/50573818-b4965880-0de3-11e9-9bbd-b9d91e3abc69.png)

**Comment by Tyriar** [comment] 2019-01-02 14:53
This can be marked as fixed when Hyper adopts node-pty@0.8.0 https://github.com/Microsoft/node-pty/releases/tag/0.8.0. To be clear, it will never work for < Windows 10 1809 and non-WSL may or may not work.

**Comment by dp97** [comment] 2019-01-06 21:58
Thank you very much for hinting.
Updated windows and on Terminus terminal show all 256 colors.
For those wondering, install it with npm: 
`npm i terminus-terminal`

**Comment by MegaCookie** [comment] 2019-01-07 08:46
> Thank you very much for hinting.
> Updated windows and on Terminus terminal it show all 256 colors.
> For those wondering, install it with npm:
> `npm i terminus-terminal`

That's not a solution for hyper though.   Anyway thanks for pointing out a nice alternative.

**Comment by auslander** [comment] 2019-02-03 19:10
Updated to Hyper 3.0.0 Canary 6 and still having the issue. Been fighting this off and on for months and just found this thread today. Thought I was just doing something wrong. 
![cat AnsiColors256.ans](https://user-images.githubusercontent.com/2781409/52181180-de60e780-27b4-11e9-94bc-6d2eb7799dac.PNG)

**Comment by szmarczak** [comment] 2019-02-03 19:35
Yup, still doesn't work. Latest Windows 10 and canary 6:

![image](https://user-images.githubusercontent.com/36894700/52181515-243ca080-27f3-11e9-98e5-0d7409285fa8.png)

**Comment by dp97** [comment] 2019-02-03 20:04
Actually it works. Probably you need to update your Windows 10 to build 1809 or higher.


![image](https://user-images.githubusercontent.com/20670448/52181855-5c49e080-27ff-11e9-98c2-8acb8f66de1d.png)

**Comment by szmarczak** [comment] 2019-02-03 20:11
> Probably you need to update your Windows 10 to build 1809 or higher.

I'll give it a try. I've been putting off some updates for a few days due to some important work. I'll inform you later, thanks :)

**Comment by Tyriar** [comment] 2019-02-04 15:46
FYI there are several issues in Windows 1809 and I moved the default minimum version in node-pty to what is the current fast ring Windows Insiders build, so you should get this in windows 190*.

**Comment by szmarczak** [comment] 2019-02-04 16:24
So we have to wait a lil bit more...

**Comment by heamaral** [comment] 2019-02-05 23:13
I've updated my windows to test it, and it works. But clear isn't cleaning the buffer.

**Comment by szmarczak** [comment] 2019-02-08 12:14
After I've updated my Windows it works as expected :tada:

![image](https://user-images.githubusercontent.com/36894700/52477774-6a9f5000-2ba3-11e9-9f83-bbf830a80e10.png)

**Comment by MortezaRamezani** [comment] 2019-10-01 12:42
It still doesn't work with msys2 on the latest version, mintty with msys2 works fine.

**Closed** 2019-10-06 19:32 UTC
Labels: 👆 Is Upstream, 🖼 Platform: Windows
