### ISSUE TITLE
Error after closing the app using extension for URL's - Hyper Version: 1.0.0 (1.0.0.1303)

### ISSUE THREAD

**Issue by iam-phild** [zeit/hyper#1154] opened 2016-12-13 00:53 UTC
### The problem
Error after closing the app using extension for URL's.

### The problem explained
After I use the URL extension with Hyper and close it, I receive the following JavaScript error message.

<img width="547" alt="error" src="https://cloud.githubusercontent.com/assets/23381199/21123072/b63f7614-c0d6-11e6-95a5-94c72535b8c2.png">

### Versions
Macbook Pro Retina, 13', macOS Sierra: Version 10.12.1
Hyper Version: Version 1.0.0 (1.0.0.1303)

**Comment by CodeTheory** [comment] 2016-12-13 00:58
Duplicate of #631.

**Closed by CodeTheory** 2016-12-13 00:58 UTC
