### ISSUE TITLE
Resizing window should update terminal display

### ISSUE THREAD

**Issue by dotlouis** [zeit/hyper#476] opened 2016-07-28 09:08 UTC
As a GIF is worth a thousand words:

Default OSX terminal:
![terminal-resize](https://cloud.githubusercontent.com/assets/1891109/17207137/6327abc0-54b3-11e6-9e5a-d88946e18f10.gif)

Hyperterm:
![hyperterm-resize](https://cloud.githubusercontent.com/assets/1891109/17207150/6e2a8ba0-54b3-11e6-8e9d-6cd60555cc46.gif)

**Comment by sifex** [comment] 2016-09-12 04:30
Any update on this?

**Comment by matheuss** [comment] 2016-10-08 22:22
Bumped to `high` since this is very annoying 😛

**Comment by realogicbcleary** [comment] 2016-12-12 21:45
I think this issue is related to an issue I noticed with panes (#56), so +1.  

> [...w]hen my window manager (amethyst) shrinks Hyper, it seems like it doesn't redraw, so the lower pane gets hidden. My work-around is to do a quick CMD+SH+D + CMD+W, but that hinges on remembering a pane just got hidden.

**Comment by sifex** [comment] 2016-12-12 22:27
@realogicbcleary Yea, because Hyper uses divs/containers (I'm not too sure, but some sort of HTML Block) for each line. Might have a look how to reflow before Christmas.

**Comment by realogicbcleary** [comment] 2016-12-12 22:39
@sifex Mine isn't really reflow issue -- rather a more basic `window.onResize(redraw)` type thing -- but I think it'll be resolved as a subset of this issue.

**Comment by wmertens** [comment] 2016-12-29 09:02
@realogicbcleary I think your issue is separate. This reflow issue is about redrawing all the visible lines so they match the screen width, as well as storing the history in such a way that that is possible. Your issue sounds like a missing resize event…

**Comment by virtualbeck** [comment] 2017-03-30 15:41
Is there still a pulse on this issue?

**Comment by malonehedges** [comment] 2017-05-02 01:40
Haven't spent much time with the source code here, but it seems like this could be fixed using the `line-overflow="true"` property on `x-row`s.

![screenshot](http://i.imgur.com/WnyHM0p.png)

**Comment by liwsakilive** [comment] 2017-05-27 15:00
If OS windows 10 ?

**Comment by baptistebriel** [comment] 2017-06-19 19:38
+1

**Comment by yjkimjunior** [comment] 2017-07-05 22:58
+1

**Comment by DreierF** [comment] 2017-08-01 16:44
+1

**Comment by malonehedges** [comment] 2017-08-01 21:27
@matheuss is there any development on this? Accepting PRs?

**Comment by epan** [comment] 2017-08-24 18:06
@malonehedges the issue is labeled `Priority: OMG Maximum` and `Status: Help Wanted` can you save us 💃

**Comment by tjfwalker** [comment] 2017-12-27 17:44
> _[pokes issue #476 with a stick]_
> I can't tell; is it dead or alive. It's not moving.

ヾ(×_× ) ﾂ

**Comment by malonehedges** [comment] 2018-05-04 04:29
To clarify, not currently working on this. Don't have the time right now

Still very much in support of this issue though, this is a deal killer for me when I get a stacktrace logged in a small window.

**Comment by controversial** [comment] 2018-08-02 16:50
Is this planned, even with xterm in Hyper 2.0?

**Comment by dontsave** [comment] 2018-10-04 17:39
Checking out Hyper for the first time and I have to say that while it's a very cool terminal, it's kind of shocking that it fails to properly resize previous output. It would be great if this got fixed

**Comment by bwobst** [comment] 2018-10-24 19:11
I'd love to use Hyper but not having this feature is a deal breaker.

**Comment by gixlg** [comment] 2018-10-25 08:31
> I'd love to use Hyper but not having this feature is a deal breaker.

Same here.

**Comment by ClearCarbon** [comment] 2018-10-25 09:31
I think hyper is beautiful terminal and I've been watching this issue for a long time, its the last thing I'd need fixing before switching to it.

**Comment by jmordica** [comment] 2018-12-05 16:30
Love Hyper! Don't love window resize issue.

**Comment by jubby2000** [comment] 2019-03-15 16:38
I was forced to move to iTerm because of this issue - but would love to come back. Any progress here?

**Comment by ppot** [comment] 2019-03-16 16:21
@jubby2000 this is now integrated onto xtemrjs which will be available into future releases.

**Comment by nervewax** [comment] 2019-05-07 09:53
After updating to 3.0.0 it's looking like this is now fixed, thanks to whoever did the hard work and sorted this 👌✨

**Comment by gabrielseibel1** [comment] 2019-05-07 23:59
Using 3.0.0 and the bug is still there 😞

**Comment by ppot** [comment] 2019-05-08 00:07
@gabrielseibel1 did you install or update?

**Comment by gabrielseibel1** [comment] 2019-05-08 00:09
@ppot Fresh install. First time ever using Hyper.

**Comment by gabrielseibel1** [comment] 2019-05-08 00:12
@ppot Come to think of it, my bug may be slightly different. I'll try to diagnose it more precisely tomorrow, maybe add a gif as OP did.

**Comment by gabrielseibel1** [comment] 2019-05-08 00:17
@ppot I actually have #1566, not this one.

**Comment by bwobst** [comment] 2019-05-17 18:58
This is fixed now in 3.0.2.

**Closed** 2019-05-17 20:54 UTC
Labels: help wanted, 🎨 Type: Enhancement
