### ISSUE TITLE
Hyper becomes unresponsive when command writes large amount of text quickly

### ISSUE THREAD

**Issue by rzeigler** [zeit/hyper#1981] opened 2017-07-07 17:33 UTC
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.2.5
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [My .hyper.js](https://gist.github.com/rzeigler/24923083ee9376a7548b1008a7c42227#file-hyper-js)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Reproduced by backing up my .hyper.js and allowing hyper to reload.

## Issue
As an example consider a command like `tree -fi` on a hierarchy containing ~10000 leaves (i.e. a node_modules directory for a non-trivial project). Hyper will become unresponsive for several seconds even though the command shouldn't take that long to run and Hyper Helper will consume a CPU core's worth of CPU %. This means I can't do things like tail logs or run webpack --watch on very complex projets in the background because my terminal will randomly become unresponsive for several seconds while I'm doing other things.

**Comment by geoffrepoli** [comment] 2017-07-12 18:31
Possible dupe of [687](https://github.com/zeit/hyper/issues/687)

**Comment by ppot** [comment] 2017-08-08 01:15
Closing in favor of #687

**Closed by ppot** 2017-08-08 01:15 UTC
Labels: Is Duplicate
