### ISSUE TITLE
terminal size wrong on startup

### ISSUE THREAD

**Issue by m4r1vs** [zeit/hyper#1790] opened 2017-05-06 10:22 UTC
As you can see in this screenshot the Terminal size is not correct on startup. When I nano or vim something its adjusted right. 
![image](https://cloud.githubusercontent.com/assets/26097311/25771610/b0ef3c98-3256-11e7-878d-1697464e5e17.png)
I'm using bash for windows with oh my zsh.

- OS version and name: Windows 10 build 15063
- Hyper.app version: 1.3.1
- Link of a Gist with the contents of your .hyper.js:  Looks worse with "hyperfull" plugin, but is also reproducible without.
- Relevant information from devtools: no
- The issue is reproducible in vanilla Hyper.app: yes

**Comment by m4r1vs** [comment] 2017-05-09 15:12
it's also correct when switching to fullscreen

**Comment by MartyGentillon** [comment] 2017-05-17 07:57
So, the second issue that you are suffering RM-Jamotion is caused by windows itself and how the windows terminal is handling multibyte characters in the most recent update, and affects multiple terminal emulators. (see https://github.com/Microsoft/vscode/issues/19665; https://github.com/rprichard/winpty/issues/105 for more details)  Apparently, this will be fixed with the next windows update later this year.

**Comment by ppot** [comment] 2017-08-15 00:58
Based on https://github.com/Microsoft/vscode/issues/19665 I will mark this as fixed.

**Closed by ppot** 2017-08-15 00:58 UTC
Labels: Is Upstream, Platform: Windows
