### ISSUE TITLE
Can't display chinese in right way

### ISSUE THREAD

**Issue by wzjing** [zeit/hyper#1757] opened 2017-04-22 03:10 UTC
-

Hyper 1.3.1
Electron 1.4.15
win32 x64 10.0.16179

My system language is Chinese. I got those problems:
* The chinese words overlap each other, can't see anything.
* And when I use the "cls" command, the chinese words is still on it's last position, not disappear.

>You can see both problems in this screenshot.

![ScreenShot](http://i2.muimg.com/567571/69ef9731fea62828.png)

**Comment by LitoMore** [comment] 2017-04-22 06:50
duplicate of #1535

**Comment by albinekb** [comment] 2017-04-23 16:27
Closing as duplicate of #1535

Thanks for the info

**Closed by albinekb** 2017-04-23 16:27 UTC
