### ISSUE TITLE
Cannot install plugins using hpm

### ISSUE THREAD

**Issue by ronag** [zeit/hyper#1573] opened 2017-02-22 09:59 UTC
When trying to install e.g. "hyper layout" using `hpm i hyperlayout` I just received the hpm help print out?

```
Roberts-MBP-2:~ ronagy$ hpm i hyperlayout

  Usage: hpm [options] [command]
  
  Commands:
  
    d, docs, h, home               Open the npm page of a plugin
    f, fork                        Fork a plugin from npm into your ~/.hyper_plugins/local
    help                           Display help
    i, install                     Install a plugin
    ls, list                       List installed plugins
    lsr, list-remote, ls-remote    List plugins available on npm
    s, search                      Search for plugins on npm
    u, uni, uninstall, rm, remove  Uninstall a plugin
  
  Options:
  
    -h, --help     Output usage information
    -v, --version  Output the version number
```

Running version 1.2.1

**Comment by Equinox** [comment] 2017-02-22 10:01
Dupe of https://github.com/zeit/hpm/issues/72.

**Closed** 2017-02-22 10:06 UTC
