### ISSUE TITLE
Support for font ligatures, i.e. in Fira Code

### ISSUE THREAD

**Issue by con-ssc** [zeit/hyper#1246] opened 2016-12-16 08:19 UTC
- [X ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/con-ssc/26cd65a2888cf26953a801e0799a9ae4
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: no errors
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Feature Request: Support for font ligatures.

**Comment by chrisnojima** [comment] 2016-12-18 04:12
This workaround works for me : https://github.com/zeit/hyper/issues/914#issuecomment-255292136

**Comment by albinekb** [comment] 2017-01-04 19:23
Duplicate of  #914 closing :)

**Closed by albinekb** 2017-01-04 19:23 UTC
