### ISSUE TITLE
Can't type ~ character

### ISSUE THREAD

**Issue by sergiovilar** [zeit/hyper#466] opened 2016-07-27 20:22 UTC
Hello guys,

I can't type the ~ character in Hyperterm in 0.7.1 as in the previous versions. Could someone help me? Thank you so much!

**Comment by albinekb** [comment] 2016-07-27 20:25
Hello! 

if you try doing
`echo $LANG`
What do you get?

Probably related to #441

**Comment by sergiovilar** [comment] 2016-07-27 20:26
@albinekb hello! That's what I get:

```
❯ echo $LANG
en_US.UTF-8
```

**Comment by hoffi** [comment] 2016-07-27 21:09
Can't type the "~" char as well in the latest version.

I'm using fish and locale is set to german:
```sh
LANG=de.UTF-8
```

**Comment by fecabianchi** [comment] 2016-07-27 21:27
same here... can't type any of those special characters like ~ ' " `

```
❯ echo $LANG       
en_US.UTF-8
```

**Comment by CodeTheory** [comment] 2016-07-27 21:50
Is it a foreign keyboard? Possibly related/duplicate of #29.

**Comment by fecabianchi** [comment] 2016-07-27 21:52
nop, a macbook en_us keyboard. but the layout in osx is U.S. International.

**Comment by sergiovilar** [comment] 2016-07-27 22:22
Tested with CODE Keyboard US International, Pok3r Keyboard US International and Macbook Keyboard En US both with US International layout and DVORAK-QWERTY, same problem.

**Comment by Rickgbw** [comment] 2016-07-27 23:29
same for me... chars like ~ ' " not work.
US International key board on macbook 15'
`$LANG` returns: `en_US.UTF-8`

**Comment by sergiovilar** [comment] 2016-07-28 10:12
Maybe somenone at #214 could help us?

**Comment by albinekb** [comment] 2016-07-28 10:57
@sergiovilar I'm currently rewriting #214... hopefully done soon ™️ I'll ping you when it's ready to test

**Comment by sergiovilar** [comment] 2016-07-28 10:58
@albinekb Thank you!

**Comment by MrRio** [comment] 2016-07-30 18:34
This is a good temporary fix until 214 is ready to land. https://github.com/zeit/hyperterm/pull/521

**Closed** 2016-11-16 18:44 UTC
Labels: Status: In Progress, Type: Bug
