### ISSUE TITLE
JavaScript Error occurred in the main process.

### ISSUE THREAD

**Issue by obrassard** [zeit/hyper#1193] opened 2016-12-14 02:45 UTC
Each time I open a web page with the terminal (ex: when writing google.ca), when I want to quit the app an error message popup " 

>**A JavaScript error occurred in the main proccess**
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at WebContents.send (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/web-contents.js:93:15)
    at sendToEmbedder (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/guest-view-manager.js:121:16)
    at WebContents.<anonymous> (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/guest-view-manager.js:128:7)
    at emitOne (events.js:101:20)
    at WebContents.emit (events.js:188:7)

<img width="416" alt="capture d ecran 2016-12-13 a 21 40 16" src="https://cloud.githubusercontent.com/assets/17227551/21167846/5db7b7d4-c17d-11e6-889b-545e2e777953.png">

Mac OS Sierra
-
Hyper 1.0.0
Electron 1.4.7
darwin x64 16.1.0

**Comment by CodeTheory** [comment] 2016-12-14 02:48
Duplicate of #631

**Closed by CodeTheory** 2016-12-14 02:48 UTC
