### ISSUE TITLE
Drag & drop a folder does not work on CD command

### ISSUE THREAD

**Issue by tadeha** [zeit/hyper#3657] opened 2019-05-11 11:26 UTC
- [ ] Your Hyper.app version is **3.0.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

 - **Hyper version**: undefined "3.0.2"

 - **OS ARCH VERSION:** darwin x64 18.2.0
 - **Electron:** 3.1.3  **LANG:** undefined
 - **SHELL:** /bin/bash   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#ff0000",
    "green": "#33ff00",
    "yellow": "#ffff00",
    "blue": "#0066ff",
    "magenta": "#cc00ff",
    "cyan": "#00ffff",
    "white": "#d0d0d0",
    "lightBlack": "#808080",
    "lightRed": "#ff0000",
    "lightGreen": "#33ff00",
    "lightYellow": "#ffff00",
    "lightBlue": "#0066ff",
    "lightMagenta": "#cc00ff",
    "lightCyan": "#00ffff",
    "lightWhite": "#ffffff"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false
}

          {
  "plugins": [],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by pcnate** [comment] 2019-05-11 17:14
looks to be a duplicate of #3582

**Closed** 2019-07-03 13:24 UTC
