### ISSUE TITLE
Failed to open Hyper on Win10

### ISSUE THREAD

**Issue by cybertk** [zeit/hyper#3529] opened 2019-03-21 05:08 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Win10 1709 Build: 16299.1029
- **Hyper.app version**: 2.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Yes 

## Issue

![image](https://user-images.githubusercontent.com/455809/54734382-0330e300-4bda-11e9-836e-cd4a43554b3b.png)

**Comment by basteez** [comment] 2019-03-21 06:52
Same issue here, but on Windows 8.1

**Comment by arsari** [comment] 2019-04-01 00:54
Same issue with Windows 10.  I have searched the repo for possible solutions but have been unsuccessful.

![image](https://user-images.githubusercontent.com/22566231/55297746-36078200-53f7-11e9-81e1-f7038bcf95af.png)

**Comment by IvanBernatovic** [comment] 2019-04-01 09:07
This is a duplicate of #3442 so this should be closed. Basically the issue is caused by antivirus software and Microsoft's node-pty package that Hyper uses. Easy fix is to exclude some files in your antivirus software, more info [here](https://github.com/Microsoft/node-pty/issues/208#issuecomment-465624603).

**Closed** 2019-04-04 00:12 UTC
