### ISSUE TITLE
esc key not working

### ISSUE THREAD

**Issue by mpeven** [zeit/hyper#4374] opened 2020-03-11 14:41 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

This might be a duplicate of this: https://github.com/zeit/hyper/issues/3929
If it is, feel free to remove.

- **OS version and name**: Mac OS Mojave (10.15.3)
- **Hyper.app version**: 3.1.0-canary.4
- **The issue is reproducible in vanilla Hyper.app**: No

## Issue
The escape key doesn't work on the canary version for my MacBook Pro 15" 2017. I noticed this in vim at first but tested it by typing `python -c "import time; time.sleep(2)"` and pressing on the esc key a bunch. 

In the canary version (3.1.0-canary.4) I see this:
```
python -c "import time; time.sleep(2)"
```

When I downgrade to the stable version (3.0.2) I see this:
```
python -c "import time; time.sleep(2)"
^[^[^[^[^[^[^[^
```

**Comment by bet4it** [comment] 2020-03-11 14:53
Duplicate of #3929

**Closed** 2020-03-11 14:57 UTC
