### ISSUE TITLE
Incorrect Cursor Location When Using Avenir Font Family

### ISSUE THREAD

**Issue by planetpratik** [zeit/hyper#2808] opened 2018-04-05 12:28 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.6
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  https://gist.github.com/planetpratik/fe56d0aba785c02c83fb44d16ca16fdb
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes. Tried but same error occurs.

## Issue
Hello There,
I am trying to use Avenir Next font which is already included in macOS. But actual position of mouse cursor and the cursor position showed on screen differs. There's large gap between typed letters and cursor. When I use default fonts provided in hyper.js, it works fine ( e.g., Menlo, monospace etc ). But when I add existing font family "Avenir Next" in hyper.js, this issue occurs. If anyone could help to fix this issue. It would be helpful.
Thank You.
<img width="689" alt="problem in cursor position" src="https://user-images.githubusercontent.com/12500760/38365382-b91bedee-38f9-11e8-9214-35ffc84d07b5.png">

**Comment by albinekb** [comment] 2018-04-05 12:58
Duplicate of #2525

https://github.com/zeit/hyper/issues/2525#issuecomment-349736985
`Avenir Next` is not a monospace font and shouldn't be used inside your terminal,

The reason why terminals and editors use monospaced font is so that the code will line up, if you have 1.5x chars, it will shift that row by 0.5x char widths, which will make two lines that have the same amount of characters in them, not line up:

```
this line has 23 chars.
this lime has 23 chars.
```
the line with `m` 1.5x spaced will render kinda like this:
```
this line has 23 chars.
this lim e has 23 chars.
```

So even if we supported it, it wouldn't make sense? 🤔 Navigation up/down would be "skewed", pressing up would move the cursor .5 char widths to the left/right in this simple case

**Closed by albinekb** 2018-04-05 12:58 UTC

**Comment by planetpratik** [comment] 2018-04-05 14:01
Thanks for the reply. It was really helpful. I didn't knew the technical details behind this. I'll try other good looking monospace fonts.

**Comment by albinekb** [comment] 2018-04-05 14:02
No problem, good luck ! 😊 You could try running our canary version (https://zeit.co/blog/canary), which has better support for fonts.

**Comment by planetpratik** [comment] 2018-04-05 14:04
Thanks. I will switch to Canary build. :)
