### ISSUE TITLE
Using "clear" with cygwin in Hyper causes strange behavior, requiring closing and opening a tab.

### ISSUE THREAD

**Issue by Didey** [zeit/hyper#1741] opened 2017-04-12 00:35 UTC
http://i.imgur.com/NOObzM0.png (screenshot is me doing ls, then clear, and pressing enter a bunch of times).
-

Hyper 1.3.1
Electron 1.4.15
win32 x64 6.1.7601

**Comment by jkornblum** [comment] 2017-04-12 16:09
This issue has been reported, duplicate of #1559 .
This fixed it for me (running win7 x64)
Set your env variable in your `~/.hyper.js` file

Mine looks like
`env: {TERM: 'cygwin'}`

**Comment by albinekb** [comment] 2017-04-12 16:10
Thanks @jkornblum, closing as it's a duplicate of #1559

**Closed by albinekb** 2017-04-12 16:10 UTC
