### ISSUE TITLE
Cannot update plugins

### ISSUE THREAD

**Issue by Jamesking56** [zeit/hyper#1537] opened 2017-02-17 11:47 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X El Capitan (10.11.6)
- **Hyper.app version**: 1.2.1 (1.2.1.1528)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Jamesking56/2836782ef1bd91403df720752cc9c730
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Was doing it before I installed plugins too.

## Issue
When I run Hyper terminal, I get a notification:

````
Error updating plugins.
Check `~/.hyper_plugins/npm-debug.log` for more information.
````

When I look for `npm-debug.log` it doesn't exist in that directory.

The same error also appears when clicking `Plugins -> Update All Now`

**Comment by henrikdahl** [comment] 2017-02-17 13:04
Duplicate #1513

**Comment by zackrabie** [comment] 2017-02-18 18:40
@Jamesking56 I was having this exact same issue. As @henrikdahl mentioned in #1513, a temporary fix is to set your shell of choice in the config file. I set mine to `shell: 'bash'`.

**Comment by philkunz** [comment] 2017-02-19 03:05
true, setting the shell helps

**Comment by joshbuchea** [comment] 2017-02-21 17:21
Set mine to `shell: 'zsh'` and all is well. Thanks!

**Comment by Zx-EvM** [comment] 2017-02-22 14:36
I use Windows 10 Build 14393.693 and Hyper 1.2.1 and `shell: 'C:\\Windows\\System32\\cmd.exe',` in `.hyper.js` config file fix startup error http://imgur.com/a/e1cid `Error updating plugins`

**Comment by sumnermic** [comment] 2017-02-25 22:33
@Jamesking56 the solution will be:

* Go to another terminal app, and type `echo $0`. Take note of the returned output.
* Go back to HyperTerm, ignoring all those errors. Open your file `.hyper.js`, scroll down to `shell: '',`, and replace it with what was outputted from above.

Please see Issue [#312](https://github.com/zeit/hyper/issues/312#issuecomment-281407215), I have &#35;anchored the solution for you there.

**Comment by CodeTheory** [comment] 2017-02-25 23:31
Closing as a duplicate of #1513. The fix for this bug will be released very soon.

**Closed by CodeTheory** 2017-02-25 23:31 UTC
