### ISSUE TITLE
Window startup position is out of screen

### ISSUE THREAD

**Issue by enzy** [zeit/hyper#2561] opened 2017-12-25 15:25 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Home 1709 (16299.125)
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/enzy/ed9e531ec60ea28ea97596af9e13fef2
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

Multiple monitors setup: Monitor 1 (left, notebook screen) beside Monitor 2 (right, external monitor).

Opened and used Hyper on the M1, then closed. Unplugged M2, opened Hyper and the app window is unreachable in the void.

The window doesn't respond to Dock to the left/right commands, but is visible in a Win+Tab overview.

![hyper](https://user-images.githubusercontent.com/809888/34341074-1e9f507a-e990-11e7-8bbb-0ac8bbd6e083.png)

%appdata%\Hyper\config.json:
```json
{
	"windowPosition": [
		-1928,
		108
	],
	"windowSize": [
		700,
		500
	],
	"hyper": {
		"plugins": "{\"plugins\":[\"hyper-clean\"],\"localPlugins\":[]}",
		"plugin-versions": "[[\"hyper-clean\",\"1.0.2\"]]"
	}
}
```

After manually edited above config.windowPositon to [0, 0] the app window did appear. But that's not sustainable in everyday workflow with a notebook and an external screen.

**Comment by amaechler** [comment] 2018-01-01 23:18
Duplicate of #1869.

**Comment by chabou** [comment] 2018-01-03 16:22
Thanks for the report 🙏 . 
We're tracking this work over here: #1869

**Closed by chabou** 2018-01-03 16:22 UTC
