### ISSUE TITLE
Error updating plugins on Sierra

### ISSUE THREAD

**Issue by RobbertWolfs** [zeit/hyper#1592] opened 2017-03-01 08:00 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
 
- **OS version and name**: Sierra v10.12.3
- **Hyper.app version**: v1.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default hyper.js
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Used hyper.js before and it worked fine (on El Capitan), last weekend I did a clean install (Sierra) and now I try to download hyper.js but when I opened it (without any changes in .hyper.js) it constantly crashes and notifies me with **Error updating plugins**

**Comment by timneutkens** [comment] 2017-03-01 08:04
Temporary fix: `cd ~/.hyper_plugins` `npm install`

**Comment by RobbertWolfs** [comment] 2017-03-01 08:06
@timneutkens still get the error :/

**Comment by timneutkens** [comment] 2017-03-01 08:45
😞

**Comment by gsklee** [comment] 2017-03-01 09:22
@RobbertWolfs Dupe of #1513; please search for open/closed issues prior to reporting, thanks

**Closed** 2017-03-01 11:15 UTC
