### ISSUE TITLE
Disable notifications completely

### ISSUE THREAD

**Issue by bootstraponline** [zeit/hyper#2431] opened 2017-11-05 19:34 UTC
Editing `~/.hyper.js` with Save on Change produces an endless stream of notifications and bell sounds. There should be an option to completely disable notifications, not just the sound. `bell: false,` does nothing.

<img width="399" alt="work_around" src="https://user-images.githubusercontent.com/1173057/32418391-d3aebfc2-c236-11e7-9c90-987f97d7e823.png">

**Comment by chabou** [comment] 2017-11-05 19:53
Hi there, thanks for reporting an issue!
Unfortunately, we need the information that was listed out in template when you created the issue to really help solve your problem. For now, we'll close your issue and wait for you to comment/re-open the issue with the template information filled out from https://github.com/zeit/hyper/issues/new

**Comment by tborychowski** [comment] 2017-12-10 00:25
@chabou 

After your comment I doubt the guy would use your app again :-)
Have you tried it on mac? 
Were you able to disable notifications?
Well we weren't.

Still need more info from your template?
Here you are:
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **latest macos**
- **Hyper 1.4.8 (stable)**
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default.
- **Relevant information from devtools** nothing
- **The issue is reproducible in vanilla Hyper.app**: YES

And now, don't be a **** and fix the notifications :-)

**Comment by albinekb** [comment] 2017-12-11 09:35
I'm with you @tborychowski 👍 We don't need more info other than that:

- Happens on mac (probably windows too, needs confirmation)
- Only gets annoying because of "save on change"

So we have a couple options:

- Add a config option to disable notifications?
- Debounce the notification
- Close this issue and tell users not to use save on change when editing hyper config

Save on change is not a good idea with hyper config as we parse it and do a couple things with the config every time we detect a change, so personally I think it's best just to tell the author and similar here not to use save on change with hyper 👍

**Comment by bootstraponline** [comment] 2017-12-11 14:20
A config option to disable notifications would be nice.

**Comment by tborychowski** [comment] 2017-12-15 02:58
Actually I don't mind notifications when they are useful (e.g. when a command exited with status !== 0).
But there's one showing up when I even open the settings file (in ST3).

**Comment by bootstraponline** [comment] 2017-12-15 03:02
If we go with log level, there should be `NONE` as an option to completely disable notifications.

**Comment by tborychowski** [comment] 2017-12-15 03:09
thanks @bootstraponline, updated my comment :-)

**Comment by bootstraponline** [comment] 2018-03-07 17:06
> Does this mean that there is currently no way to stop or silence Hyper notifications?

Right

**Comment by albinekb** [comment] 2018-03-26 20:07
PR welcome @BrainInBlack 😊

**Comment by sgarcia-dev** [comment] 2018-09-09 18:17
So...does someone have an update on this? Doesn't look like this had any resolution, and I'm kind of surprised a simple `updateNotifications: false` flag still doesn't exist...

**Comment by bootstraponline** [comment] 2018-09-11 01:51
The issue is tagged as `awaiting response`. A boolean flag that disables all notifications will resolve the issue. It sounds like someone will have to submit a PR.

**Closed** 2019-09-30 20:23 UTC
Labels: 👀 Awaiting Response, 💬 Feedback Wanted

**Comment by olealgoritme** [comment] 2019-11-16 10:17
This is clearly a much needed feature. It seems to have a multitude of implications, like with my Window Manager in Linux - which does not run a Notification Daemon Service - which is needed to display notifications.

Without the Notification Daemon Service you will encounter a lot of lockup and freezes with Hyper.
For now, I'll just disable the notifications entirely.

https://github.com/zeit/hyper/blob/canary/app/notify.js#L8-L11
:laughing: 

https://electronjs.org/docs/api/notification#notificationissupported
Yes, Electron has it's own Notifications. Maybe use that instead of this "hack"?

https://github.com/zeit/hyper/blob/canary/app/notify.js#L33-L45
For those who want to remove it, just disable this / comment out / replace, whatever.

**Comment by Place1** [comment] 2020-05-04 00:57
I was about to try out Hyper on macos but everytime i saved my config file I got a notification. Hyper looks really cool but this isn't a great first impression.

Perhaps I can contribute a flag if someone can point me in the right direction?

**Comment by proteriax** [comment] 2020-08-24 01:59
@Stanzilla Why is this issue closed?

**Comment by JuanVqz** [comment] 2020-08-24 03:37
@proteriax Are you having this problem? or Do you solve it?
because I set `bell: false` and it still doing the "Beem" sound

**Comment by muellerto** [comment] 2024-07-05 05:37
I have this still, and it's 2024 now. Would it be possible to provide a solution for this case please? Hyper alone notifies 10 times more than all other software on my machine together.

**Comment by fa7ad** [comment] 2024-10-26 19:59
Hi @Stanzilla seems like you marked this as completed, but I couldn't find any configuration option for disabling notifications on the website. Was this ever implemented? Or is this a "wontfix" situation?
